import { get } from "noname";

const translates = {
    mjs_old_huoguang: "旧霍光",
    mjs_old_huoguang_prefix: "旧",
    mjsoldmangcizaibei: "芒刺在背",
    mjsoldmangcizaibei_info: "回合结束时，与你距离为1并且体力值≥你的其他角色失去1点体力。",

    mjs_old_yanghu: "旧羊祜",
    mjs_old_yanghu_prefix: "旧",
    mjsoldqingqiuhuandai: "轻裘缓带",
    mjsoldqingqiuhuandai_info: "你的每个阶段结束时：若你的装备区没有牌，则你的装备上限-1并且下一轮的同名阶段改为出牌阶段；若你的装备区有牌，则你的装备上限+1并且下一轮的同名阶段改为摸牌阶段。",
    mjsolddeguansihai: "德冠四海",
    mjsolddeguansihai_info: "出牌阶段限1次，当你选择其他角色为牌的目标时，你可以令你与所有此牌的目标分别展示2张手牌（不足则全展示），并且你选择其中一名其他角色，交换你与其展示的牌，若交换后你的手牌总点数全场最大，添加1张装备牌至手牌并且装备上限+1。",
    mjsoldqianmouyuanji: "潜谋远计",
    mjsoldqianmouyuanji_info: "回合结束时，你选择一名其他角色，你本回合每弃置1张牌，就随机削弱其1张牌。",

    mjs_old_lvmeng: "旧吕蒙",
    mjs_old_lvmeng_prefix: "旧",
    mjsoldshujunkeji: "束军克己",
    mjsoldshujunkeji_info: "每个回合结束时，若你此回合没有打出过牌，你获得1张杀；回合开始时，你每拥有2张杀，随机添加1张战法牌到你的手牌。",
    mjsoldduzhifenxue: "笃志奋学",
    mjsoldduzhifenxue_info: "你每获得3张战法牌，手牌上限+2。",

    mjs_new_zhaoweihou: "旧赵威后",
    mjs_new_zhaoweihou_prefix: "旧",
    mjsnewzhiziweibing: "质子为兵",
    mjsnewzhiziweibing_info: "每个回合限1次，当你即将受到伤害时，你可以令一名其他角色获得自己任意区域的一张牌，然后交给你另外任意张牌，并抵消此次伤害。",

    mjs_old_xusheng: "旧徐盛",
    mjs_old_xusheng_prefix: "旧",
    mjsoldbailiyicheng: "百里疑城",
    mjsoldbailiyicheng_info: "当你成为其他角色打出牌的目标时，你可以将一名角色装备区的1张牌收回其手牌，然后若此牌是其装备区最后1张牌，随机添加1张装备牌至其手牌。",

    mjs_old_jiangwei: "旧姜维",
    mjs_old_jiangwei_prefix: "旧",
    mjsoldyijihaisanxian: "一计害三贤",
    mjsoldyijihaisanxian_info: "当你的体力上限首次变为1时，你可以将所有牌交给一名其他角色，令其对另外一名其他角色打出所有杀，然后你与其受到其当前手牌数的伤害。",

    mjs_old_luzhonglian: "旧鲁仲连",
    mjs_old_luzhonglian_prefix: "旧",
    mjsoldyibudiqin: "义不帝秦",
    mjsoldyibudiqin_info: "其他角色无法改变你的势力。当你打出牌后，若此牌的花色是你在当前回合首次打出，你可以将此牌放入牌堆底，然后摸1张牌。",

    mjs_old_lifuren: "旧李夫人",
    mjs_old_lifuren_prefix: "旧",
    mjsoldqingguoqingcheng: "倾国倾城",
    mjsoldqingguoqingcheng_info: "出牌阶段限2次，你可以令一名其他角色查看并选择添加1张你的手牌的复制，直到你的下个回合开始，若其没有对其他角色造成过伤害，则弃置这些牌，并失去1点体力。",

    mjs_old_zhuowenjun: "旧卓文君",
    mjs_old_zhuowenjun_prefix: "旧",
    mjsoldyebenxiangru: "夜奔相如",
    mjsoldyebenxiangru_info: "出牌阶段开始时，你可以翻开牌堆底的5张牌，将其中的♠牌交给一名角色，然后可以将剩余牌按原顺序放回牌堆顶。",

    mjs_old_simaxiangru: "旧司马相如",
    mjs_old_simaxiangru_prefix: "旧",
    mjsoldfengqiuhuang: "凤求凰",
    mjsoldfengqiuhuang_info: "出牌阶段开始时，你可以翻开牌堆顶的5张牌，将其中的♥牌交给一名角色，然后可以将剩余牌按原顺序放回牌堆底。",

    mjs_old_baqing: "旧巴清",
    mjs_old_baqing_prefix: "旧",
    mjsolddanshanvwang: "丹砂女王",
    mjsolddanshanvwang_info: `你的${get.poptip("mjsdansha")}不计入手牌上限。每个回合限1次，当你即将受到伤害时，你可以将1张${get.poptip("mjsdansha")}交给伤害来源，并令此伤害-1。`,

    mjs_old_wangyi: "旧王异",
    mjs_old_wangyi_prefix: "旧",
    mjsoldzhongzhenganglie: "忠贞刚烈",
    mjsoldzhongzhenganglie_info: "回合结束时，你可以令一名其他角色的手牌数或者体力值变为与你相同，若其手牌数或者体力值因此改变>=2，你受到1点伤害。",

    mjs_old_houying: "旧侯嬴",
    mjs_old_houying_prefix: "旧",
    mjsoldshijingyinzhe: "市井隐者",
    mjsoldshijingyinzhe_info: "你打出目标唯一的战法牌在生效前暗置。你每打出1张战法牌，你可以令一名其他角色从弃牌堆获得1张装备牌。",

    mjs_old_pangtong: "旧庞统",
    mjs_old_pangtong_prefix: "旧",
    mjsyuhuochongsheng: "浴火重生",
    mjsyuhuochongsheng_info: `阵亡，若你的阵营未失败，你进入${get.poptip("mjsyuhuochongsheng_faq")}。`,
    mjsyuhuochongsheng_faq: "涅槃状态",
    mjsyuhuochongsheng_faq_info: "每个回合开始时，卜卦，若为♥️，则你重新登场。",

    mjs_old_zhanghan: "旧章邯",
    mjs_old_zhanghan_prefix: "旧",
    mjsoldshetushoubing: "赦徒授兵",
    mjsoldshetushoubing_info: "你可以消耗1次出杀次数，将弃牌堆中的所有杀洗回牌堆，然后摸牌直到摸到的牌不是杀或装备牌。",

    mjs_old_junwanghou: "旧君王后",
    mjs_old_junwanghou_prefix: "旧",
    mjsoldshiqinjinshen: "事秦谨慎",
    mjsoldshiqinjinshen_info: "每个回合各限1次，体力值>你的角色对你造成伤害后，你可以令一名角色摸1张牌；手牌数>你的角色对你造成伤害后，你可以令一名角色回复1点体力值。",
    mjsoldqiaojieyuhuan: "巧解玉环",
    mjsoldqiaojieyuhuan_info: "当你成为其他角色打出的战法牌目标时，你可以将其转化为杀并对你打出。",

    mjs_old_zhaoji: "旧赵姬",
    mjs_old_zhaoji_prefix: "旧",
    mjsoldjuehaoshanwu: "绝好善舞",
    mjsoldjuehaoshanwu_info: "当你打出牌时，你可以弃置1张牌，然后摸1张牌。当你打出最后1张手牌时，摸2张牌。",
    mjsoldyinguiganquan: "迎归甘泉",
    mjsoldyinguiganquan_info: "限定，获得弃牌堆中所有你弃置的牌。",

    mjs_old_fazheng: "旧法正",
    mjs_old_fazheng_prefix: "旧",
    mjsoldqihuacesuan: "奇画策算",
    mjsoldqihuacesuan_info: "当你打出牌时，若此牌点数等于你本回合累计打出的牌数，则你摸2张牌。",
    mjsoldyazibibao: "睚眦必报",
    mjsoldyazibibao_info: "受伤，你可以查看并打出伤害来源的1张手牌，若其手牌均无法打出，你对其造成1点伤害。",

    mjs_old_caopi: "旧曹丕",
    mjs_old_caopi_prefix: "旧",
    mjsoldyangexingyin: "燕歌行吟",
    mjsoldyangexingyin_info: `每个回合限1次，当你选择杀的目标时，你可以弃置目标2张牌，若此杀造成伤害，令其摸2张牌，并获得${get.poptip("mjs_debuff_zhongdu_faq")}+1，否则你回复1点体力值。`,

    mjs_old_weizifu: "旧卫子夫",
    mjs_old_weizifu_prefix: "旧",
    mjsoldpingyanouzhe: "平阳讴者",
    mjsoldpingyanouzhe_info: "当你打出牌后，弃置1张牌；当你失去最后的手牌后，添加你当前回合弃置牌的复制，并且将此技能改为“当你打出牌后，令一名其他角色添加1张此牌的复制”。",

    mjs_old_zhengxiu: "旧郑袖",
    mjs_old_zhengxiu_prefix: "旧",
    mjsoldyinduquanshi: "因妒劝释",
    mjsoldyinduquanshi_info: "出牌阶段限1次，你可以交给一名其他角色任意张牌，然后令一名角色回复等量体力，并且其下回合出杀次数+1。",

    mjs_old_zhangjiao: "旧张角",
    mjs_old_zhangjiao_prefix: "旧",
    mjsoldtaipingdao: "太平道",
    mjsoldtaipingdao_info: "其他角色出牌阶段限1次，其可以交给你2张牌，然后你可以令其回复1体力。",

    mjs_old_suqin: "旧苏秦",
    mjs_old_suqin_prefix: "旧",
    mjsoldhezong: "合纵",
    mjsoldhezong_info: "出牌阶段限1次，你可以查看并增强一名角色的1张牌。场上每存在1种势力，此技能的发动次数+1。",

    mjs_old_lianpo: "旧廉颇",
    mjs_old_lianpo_prefix: "旧",
    mjsoldfujingqingzui: "负荆请罪",
    mjsoldfujingqingzui_info: "出牌阶段限1次，你可以获得一名其他角色的2张牌，其下个回合开始时，你失去1点体力，然后将因此获得的牌交回。",

    mjs_old_ximenbao: "旧西门豹",
    mjs_old_ximenbao_prefix: "旧",
    mjsoldhouminboku: "厚民薄库",
    mjsoldhouminboku_info: "每回合限1次，你可以弃置2张相同花色的牌，令任意名角色各获得1张此花色的牌。",

    mjs_old_lisi: "旧李斯",
    mjs_old_lisi_prefix: "旧",
    mjsoldfanshumingfa: "燔书明法",
    mjsoldfanshumingfa_info: "当你成为其他角色打出牌的目标时，你可以弃置1张牌，令其无法再次打出同名牌直到当前回合结束。当你弃牌后，直到你的下回合开始，其他角色打出与你弃牌同名的牌时，你可以令其随机弃置1张牌。",

    mjs_old_yanzhaowang: "旧燕昭王",
    mjs_old_yanzhaowang_prefix: "旧",
    mjsoldqiangbingfaqi: "强兵伐齐",
    mjsoldqiangbingfaqi_info: "当你获得增强牌时，你回复1点体力。你每累计获得3张增强牌时，之后每回合的摸牌数+1，出杀次数+1。",

    mjs_old_zhaoweihou: "牢赵威后",
    mjs_old_zhaoweihou_prefix: "牢",
    mjsoldzhiziweibing: "质子为兵",
    mjsoldzhiziweibing_info: "当你即将受到伤害时，你可以令一名其他角色获得你任意区域的1张牌，然后交给你另外任意张牌，并令你回复1点体力。",

    mjs_old_zhugeliang: "旧诸葛亮",
    mjs_old_zhugeliang_prefix: "旧",
    mjsoldjinnangmiaoji: "锦囊妙计",
    mjsoldjinnangmiaoji_info: `出牌阶段开始时，选择1张${get.poptip("mjsjinnangmiaoji_faq")}添加到手牌。`,

    mjs_old_chenping: "旧陈平",
    mjs_old_chenping_prefix: "旧",
    mjsoldliuchuqiji: "六出奇计",
    mjsoldliuchuqiji_info: `${get.poptip("rule_mjs_yingzhan")}，每个回合限1次，你可以选择1张${get.poptip("mjsliuchuqiji_faq")}添加到手牌，并可以立即打出。`,

    mjs_old_zhangyi: "旧张仪",
    mjs_old_zhangyi_prefix: "旧",
    mjsoldzhezhu: "折竹",
    mjsoldzhezhu_info: "每轮结束时，你可以用1张手牌刻写其他角色本轮发动过的1个技能。之后你可以弃置此牌，获得此技能，直到你的下个回合开始。",
    
    mjs_old_shenbuhai: "旧申不害",
    mjs_old_shenbuhai_prefix: "旧",
    mjsoldjuncaoqibing: "君操其柄",
    mjsoldjuncaoqibing_info: `游戏开始时，你可以令一名角色获得${get.poptip("mjsyishuyuguo")}。当你或者其阵亡时，未阵亡的角色也失去${get.poptip("mjsyishuyuguo")}。`,

    mjs_old_ziying: "旧子婴",
    mjs_old_ziying_prefix: "旧",
    mjsoldmodaiqinwang: "末代秦王",
    mjsoldmodaiqinwang_info: "你的初始手牌×2。在你的回合开始时，你弃置手牌至手牌上限。当你弃置牌时，你可以将弃置的牌交给任意一名其他角色。",
    mjsoldtuimiaozhujian: "推庙诛奸",
    mjsoldtuimiaozhujian_info: "出牌阶段限1次，你可以减少1点装备上限，摸3张牌，手牌上限+1；当你的装备上限首次为0时，你可以弃置所有杀，并选择一名其他角色，对其造成等量伤害。",

    mjs_old_sunce: "旧孙策",
    mjs_old_sunce_prefix: "旧",
    mjsoldxiaobawang: "小霸王",
    mjsoldxiaobawang_info: "出牌阶段与弃牌阶段开始时，如果你的手牌数为全场最多，你可以选择一名其他角色进行阵前对决，若因此击杀目标，可以再选择一名其他角色进行阵前对决。",

    mjs_old_yueyi: "旧乐毅",
    mjs_old_yueyi_prefix: "旧",
    mjsoldgujunlianke: "孤军连克",
    mjsoldgujunlianke_info: "出牌阶段开始时，你可以对自己翻出牌堆顶的5张牌，并可以打出其中任意花色各1张牌，然后将剩余的牌放入牌堆底。",
    mjsoldbaohuiwangshu: "报惠王书",
    mjsoldbaohuiwangshu_info: "每轮开始时，你可以弃置你的所有手牌，然后选择一名其他角色，将势力改为与其相同，并获得其手牌的复制。",

    mjs_old_pingyuanjun: "旧平原君",
    mjs_old_pingyuanjun_prefix: "旧",
    mjsoldzhanxiaolixin: "斩笑立信",
    mjsoldzhanxiaolixin_info: "每回合限1次，你可以销毁一名其他角色的1张牌，然后令所有与你势力相同的其他角色依次摸1张牌，并交给你1张牌。",
    mjsoldlilingzhihun: "利令智昏",
    mjsoldlilingzhihun_info: "其他角色受到伤害时，你可以将其势力改为与你相同；其他角色回合开始时，若你在其攻击范围内，则其本回合打出的杀无法选择与你势力相同的其他角色为目标。",

    mjs_old_chunshenjun: "旧春申君",
    mjs_old_chunshenjun_prefix: "旧",
    mjsoldyihuajiemu: "移花接木",
    mjsoldyihuajiemu_info: "每个回合限1次，其他角色主动打出战法牌时，你可以将其转化为任意战法牌，并由该角色继续执行转化后牌的效果，然后你获得1张转化后牌的复制并增强。",

    mjs_old_zhoubo: "旧周勃",
    mjs_old_zhoubo_prefix: "旧",
    mjsoldxuepingzhulv: "削平诸吕",
    mjsoldxuepingzhulv_info: "每回合限1次，摸牌至与全场手牌最多的角色相同，下一次造成的伤害+1，出牌阶段结束时，将因此技能获得的牌交给一名其他角色。",

    mjs_old_caiwenji: "旧蔡文姬",
    mjs_old_caiwenji_prefix: "旧",
    mjsoldliluanduanchang: "离乱断肠",
    mjsoldliluanduanchang_info: "受伤，你可以选择与一名其他角色交换位置。",

    mjs_old_mengyi: "旧蒙毅",
    mjs_old_mengyi_prefix: "旧",
    mjsoldneimoufazhi: "内谋法治",
    mjsoldneimoufazhi_info: `${get.poptip("rule_mjs_yingzhan")}，你随机弃置目标1张手牌或装备牌，若你未受到此杀伤害，令此技能可以弃牌的数量+1，否则-1。`,

    mjs_old_mengtian: "旧蒙恬",
    mjs_old_mengtian_prefix: "旧",
    mjsoldzhuchenshoufan: "筑城守藩",
    mjsoldzhuchenshoufan_info: `${get.poptip("rule_mjs_yingzhan")}，你摸1张牌，若你未受到此杀伤害，令此技能可以摸牌的数量+1，否则-1。`,
    mjsoldzhongxin: "忠信",
    mjsoldzhongxin_info: "每个回合限1次，当一名其他角色成为其他角色杀的目标时，若你与其距离为1，则你可以与其交换座位，并将此杀的目标改为你。",

    mjs_old_lvzhi: "旧吕雉",
    mjs_old_lvzhi_prefix: "旧",
    mjsoldlinchaochengzhi: "临朝称制",
    mjsoldlinchaochengzhi_info: "回合开始时，你可以选择1个点数或属性，令所有角色在打出此点数或属性的牌后摸1张牌或者随机销毁1张牌，直到你的下个回合开始。",

    mjs_old_xuchu: "旧许褚",
    mjs_old_xuchu_prefix: "旧",
    mjsoldhuchi: "虎痴",
    mjsoldhuchi_info: "受伤，你可以获得1张装备牌，并添加1张阵前对决对你的手牌。",

    mjs_old_fanzeng: "旧范增",
    mjs_old_fanzeng_prefix: "旧",
    mjsoldwangqinbichu: "亡秦必楚",
    mjsoldwangqinbichu_info: "游戏开始时，选择一名其他角色，令其体力上限+2，并回复2点体力，当其造成伤害后，你随机获得1张战法牌，并且可以立即打出此牌。",

    mjs_old_xiaohe: "旧萧何",
    mjs_old_xiaohe_prefix: "旧",
    mjsoldchengye: "成也",
    mjsoldchengye_info: "回合结束时，你可以令一名其他角色立即进行一个出牌阶段；在此阶段内，当其打出牌后，其摸1张牌。",
    mjsoldbaiye: "败也",
    mjsoldbaiye_info: `限定，其他角色的出牌阶段结束时，若其在此阶段内打出的牌＞3张，你可以令另外一名其他角色对其打出手牌中的所有杀，直到目标${get.poptip("rule_mjs_zhongshang")}。`,

    mjs_old_zhangliang: "旧张良",
    mjs_old_zhangliang_prefix: "旧",
    mjsoldbolangzhuiqin: "博浪椎秦",
    mjsoldbolangzhuiqin_info: "你可以将1张武器牌装备给一名其他角色，然后其可以对你选择的其攻击范围内的另一名其他角色打出1张杀。",
    mjsoldyunchouweiwo: "运筹帷幄",
    mjsoldyunchouweiwo_info: "当你获得杀时，将其转化为2张随机战法牌。你在回合外需要打出杀时，其他角色可以替你打出。",
    mjsoldyiqiaoshoushu: "圯桥授书",
    mjsoldyiqiaoshoushu_info: `当你累计打出15张战法牌后，将${get.poptip("mjsyiqiaoshoushu_faq")}添加到你的手牌和你可以转化的战法牌种类中。`,

    mjs_old_longqie: "旧龙且",
    mjs_old_longqie_prefix: "旧",
    mjsoldanyingzhulei: "安营筑垒",
    mjsoldanyingzhulei_info: "回合结束时，你可以弃置所有手牌，每因此弃置1张牌，增加1点体力上限，并回复1点体力。",

    mjs_old_yuanshao: "旧袁绍",
    mjs_old_yuanshao_prefix: "旧",
    mjsoldbaiwanxiongbing: "百万雄兵",
    mjsoldbaiwanxiongbing_info: "当你的手牌数全场最多时，你的战法牌可以当作万箭齐发打出。",

    mjs_old_huangzhong: "旧黄忠",
    mjs_old_huangzhong_prefix: "旧",
    mjsoldbaodaoweilao: "宝刀不老",
    mjsoldbaodaoweilao_info: "回合开始时，若你没有装备武器牌，随机获得1张武器，否则摸1张杀。",
    mjsoldbaibuchuanyang: "百步穿杨",
    mjsoldbaibuchuanyang_info: "出杀，若你与目标距离大于1，则此杀强命。",
    mjsoldjiaobingzhiji: "骄兵之计",
    mjsoldjiaobingzhiji_info: `${get.poptip("rule_mjs_yingzhan")}，你可以摸0张牌，然后可以立即对目标打出1张杀，或者令此技能的摸牌数再次发动时+1，直到你的下个回合开始。`,

    mjs_new_caocao: "旧曹操",
    mjs_new_caocao_prefix: "旧",
    mjsnewluanshijianxiong: "乱世奸雄",
    mjsnewluanshijianxiong_info: "受伤，获得对你造成伤害的牌，并且可以立即打出其中1张牌。",
    mjsnewtianxiaguixin: "天下归心",
    mjsnewtianxiaguixin_info: "击杀，你获得目标角色所有手牌和装备。",

    mjs_new_sunquan: "旧孙权",
    mjs_new_sunquan_prefix: "旧",
    mjsnewquanxuelishi: "劝学励士",
    mjsnewquanxuelishi_info: "出牌阶段限1次，你可以弃置任意张牌然后摸等量牌；其他角色每回合限1次，交给你任意张牌，然后你交还其等量牌，若其交给你所有手牌，其摸1张牌。",

    mjs_new_liubei: "旧刘备",
    mjs_new_liubei_prefix: "旧",
    mjsnewsangumaolu: "三顾茅庐",
    mjsnewsangumaolu_info: "当你每累计主动交给一名其他角色3张牌后，你可以令其每个出牌阶段的出杀次数+1或者手牌上限+1。",
    mjsnewxiemindujiang: "携民渡江",
    mjsnewxiemindujiang_info: "其他角色可以将其在弃牌阶段弃置的牌交给你，这些牌不计入手牌上限，你无法打出或弃置这些牌。",

    mjs_old_caocao: "牢曹操",
    mjs_old_caocao_prefix: "牢",
    mjsoldluanshijianxiong: "乱世奸雄",
    mjsoldluanshijianxiong_info: "受伤，获得对你造成伤害的牌，并且可以立即打出其中1张牌。每个回合限1次，其他角色回合外获得牌后，你可以令其手牌上限+1或-1，直至其下个回合结束。",
    mjsoldtianshi: "天时",
    mjsoldtianshi_info: `所有角色获得${get.poptip("mjsoldguixin")}。`,
    mjsoldguixin: "归心",
    mjsoldguixin_info: "受伤，你可以摸1张牌。",

    mjs_old_sunquan: "牢孙权",
    mjs_old_sunquan_prefix: "牢",
    mjsolddili: "地利",
    mjsolddili_info: `所有角色获得${get.poptip("mjsoldquanheng")}。`,
    mjsoldquanheng: "权衡",
    mjsoldquanheng_info: "每回合限1次，你可以弃置任意张手牌或装备牌，然后摸等量的牌。",

    mjs_old_liubei: "牢刘备",
    mjs_old_liubei_prefix: "牢",
    mjsoldyidefuren: "以德服人",
    mjsoldyidefuren_info: "你可以交给其他角色任意张牌，令其直到你的下个回合开始，出杀后摸1张牌，每因此交出1张牌，自己回复1点体力。",
    mjsoldrenhe: "人和",
    mjsoldrenhe_info: `所有角色获得${get.poptip("mjsoldjijiang")}。`,
    mjsoldjijiang: "激将",
    mjsoldjijiang_info: "每回合出杀次数+1。",
};

const translates2 = {
    mjs_zhaogao: "赵高",
    mjsjianchendangdao: "奸臣当道",
    mjsjianchendangdao_info: "其他角色摸牌时，你摸1张牌。",
    mjszhiluweima: "指鹿为马",
    mjszhiluweima_info: "回合开始时，将随机一名其他角色的手牌随机转化为其他牌。其他角色打出被转化的牌后，你摸2张牌。其他角色的出牌阶段结束时，每张被转化的牌对其造成1点伤害。",
    mjsshaqiuzhibian: "沙丘之变",
    mjsshaqiuzhibian_info: "限定，当其他角色阵亡时，你获得其所有牌，立即开始你的回合，并且此回合内，其他角色无法响应你打出的牌，此回合结束时，你回复7点体力。",

    mjs_shichangshi: "十常侍",
    mjszhuoluanhainei: "浊乱海内",
    mjszhuoluanhainei_info: `回合开始时，登场“张让”，并随机登场2个${get.poptip({
        id: "character_mjs_scs_changshi",
        name: "“常侍”",
        type: "character",
        dialog: "characterDialog",
    })}，直至你的下个回合开始。重伤，随机删除1个“常侍”，并回复1点体力。`,
    mjsscsduoquan: "夺权",
    mjsscsduoquan_info: "其他角色的回合结束时，若其本回合未对你造成过伤害，你获得其2张牌。",
    mjsscsnongquan: "弄权",
    mjsscsnongquan_info: "回合结束时，你每有2张手牌，你的体力上限+2，并回复1点体力。",
    mjsscsgouxian: "构陷",
    mjsscsgouxian_info: "当其他角色弃牌时，随机对1名其他角色造成1点伤害。",
    mjsscsmaiguan: "卖官",
    mjsscsmaiguan_info: "当你打出行动牌时，随机弃置1张牌，然后随机获得一名其他其他角色1张牌。",
    mjsscsshoulu: "受赂",
    mjsscsshoulu_info: "其他角色出牌阶段开始后，你随机获得其1张牌，然后令其出杀次数+1。",
    mjsscshengzheng: "横征",
    mjsscshengzheng_info: "出牌阶段开始时，随机获得其他角色各1张牌。",
    mjsscsnongfa: "弄法",
    mjsscsnongfa_info: "所有其他角色摸牌阶段摸牌数-1，自己摸牌阶段摸牌数+1。",
    mjsscsjiechi: "劫持",
    mjsscsjiechi_info: "回合开始时选择一名其他角色，直到你的下个回合开始，你受到伤害后，其受到等量的伤害，其摸牌后，你摸等量张牌。",
    mjsscslesuo: "勒索",
    mjsscslesuo_info: "其他角色即将回复体力时，你令其交给你1张牌，否则其回复体力的效果无效。",
    mjsscsjianshi: "监视",
    mjsscsjianshi_info: "其他角色回合结束时，其手牌中每少1种类型的牌，你获得1张对应类型的牌。",
    mjsscssougua: "搜刮",
    mjsscssougua_info: "当你打出牌时，若其他角色的手牌中存在相同类型的牌，你随机获得其中1张牌。",
    mjsscsyuanyu: "冤狱",
    mjsscsyuanyu_info: "受伤，你可以添加1张霜冻至一名其他角色的卜卦区。",

    mjs_scs_changshi: "常侍",

    mjs_naochi: "淖齿",
    mjschoujinxuanliang: "抽筋悬梁",
    mjschoujinxuanliang_info: "回合开始时，封禁一名其他角色，然后将其所有手牌移出游戏，直到当前回合结束。",
    mjstiandisanwen: "天地三问",
    mjstiandisanwen_info: "出牌阶段限3次，每次弃置1张不同花色的手牌，然后令一名其他角色弃置所有与此牌相同花色的手牌，并失去1点体力。",
    mjslietufenzang: "裂土分赃",
    mjslietufenzang_info: "其他角色阵亡后，你随机获得其1个武将技能。",

    mjs_jiangchong: "江充",
    mjswuguzhihuo: "巫蛊之祸",
    mjswuguzhihuo_info: `每个回合开始时，随机为一名其他角色添加1张${get.poptip("mjswugurenou")}至其手牌。`,
    mjsxiuyichijie: "绣衣持节",
    mjsxiuyichijie_info: `其他角色即将对你造成伤害时，若其手牌中存在${get.poptip("mjswugurenou")}，则需要弃置1张【巫蛊人偶】，否则此伤害无效。`,
    mjskufaxianyu: "酷法陷狱",
    mjskufaxianyu_info: `当有角色弃置${get.poptip("mjswugurenou")}时，你对其造成1点伤害。`,
};
Object.assign(translates, translates2);

const translates3 = {
    mjs_nianshou: "年兽",
    mjslieyanshixin: "烈焰噬心",
    mjslieyanshixin_info: "受到的火焰伤害+1。",
    mjssenluowanxiang: "森罗万象",
    mjssenluowanxiang_info: "登场，复制所有其他角色的各1个技能。",
    mjskanglongchengsha: "亢龙成煞",
    mjskanglongchengsha_info: "当你回复体力时，改为对所有其他角色依次造成1点伤害。",
    mjsyiqishuangshen: "一气双身",
    mjsyiqishuangshen_info: `登场，卜卦，若结果为8，召唤${get.poptip({
        id: "character_mjs_nianshou",
        name: "年兽",
        type: "character",
        dialog: "characterDialog",
    })}。`,
};
Object.assign(translates, translates3);

const translates4 = {
    mjs_npc_bianxi: "卞喜",
    mjsnpcfengying: "逢迎",
    mjsnpcfengying_info: "登场，将所有手牌交给一名其他角色。拥有你的牌的其他角色无法选择你为手牌或技能的目标。",
    mjsnpcmaifu: "埋伏",
    mjsnpcmaifu_info: "拥有你的牌的其他角色失去最后一张你的牌时，对其打出牌堆顶的第1张杀。",
    mjsnpctaopao: "逃跑",
    mjsnpctaopao_info: "在你的第3个回合开始时，逃离战斗。",

    mjs_npc_caiyang: "蔡阳",
    mjsnpczhuisha: "追杀",
    mjsnpczhuisha_info: "登场，添加装备上限张开山斧至你的手牌并装备，然后将1张手牌当作杀，对一名敌方角色打出。",
    mjsnpcshengjiu: "甥舅",
    mjsnpcshengjiu_info: "每个回合开始时，你失去体力至1点，你每因此失去1点体力，就获得1张牌。",

    mjs_npc_qinqi: "秦琪",
    mjsnpcbiyanchou: "比颜丑",
    mjsnpcbiyanchou_info: "登场，添加一张阵前对决至你的手牌并且立即打出，你因此打出1张杀时，摸1张牌。",
    mjsnpcwuming: "无名",
    mjsnpcwuming_info: "当你受到阵前对决的伤害时，你死亡。",

    mjs_npc_kongxiu: "孔秀",
    mjsnpcpancha: "盘查",
    mjsnpcpancha_info: "回合开始时，查看一名其他角色的手牌，若其中缺少某种类型的牌，则对其造成1点伤害。",
    mjsnpcyiji: "一击",
    mjsnpcyiji_info: "你受到的伤害始终等于你当前体力值。",

    mjs_npc_mengtan: "孟坦",
    mjsnpcyoudi: "诱敌",
    mjsnpcyoudi_info: `登场，令所有敌方角色对你打出一张杀，否则对其造成1点伤害；重伤时，${get.poptip({
        id: "character_mjs_npc_hanfu",
        name: "韩福",
        type: "character",
        dialog: "characterDialog",
    })}登场（韩福一定为玩家的敌方目标）。`,
    mjsnpcmanma: "慢马",
    mjsnpcmanma_info: "每轮开始时，获得并装备1张坐骑牌。每个回合开始时，令所有其他角色获得并装备1张坐骑牌。",

    mjs_npc_hanfu: "韩福",
    mjsnpclengjian: "冷箭",
    mjsnpclengjian_info: "登场，对一名其他角色打出手牌中的所有的杀。",
    mjsnpcjizou: "急走",
    mjsnpcjizou_info: "当你手牌中没有杀时，你失去所有其他技能。",

    mjs_npc_wangzhi: "王植",
    mjsnpczonghuo: "纵火",
    mjsnpczonghuo_info: "登场，令一名其他角色的当前手牌在其下个回合结束时被烧毁。",
    mjsnpcchuni: "触逆",
    mjsnpcchuni_info: "当你获得先拔头筹和休养生息时，将其转化为火杀。当你的杀对目标造成伤害后，目标对你打出手牌中所有的杀。",
};
Object.assign(translates, translates4);

const characters44 = {
    mjs_tap_laobing: "烙饼",
    mjs_tap_guangzhichen: "光之尘",
    mjs_tap_xiaolongbao: "小笼包",
};
Object.assign(translates, characters44);

export default translates;
