// Generated by scripts/import-hlhj-voices.mjs. All takes; choose a variant at playback.
export const clips = {
    "JZ01": {
        "variants": [
            "hlhj_daiyu_jz01_01.mp3"
        ],
        "text": "灵河一株草，承露始知情。"
    },
    "JZ02": {
        "variants": [
            "hlhj_daiyu_jz02_01.mp3",
            "hlhj_daiyu_jz02_02.mp3"
        ],
        "text": "草木虽无言，深恩未敢忘。"
    },
    "JZ03": {
        "variants": [
            "hlhj_daiyu_jz03_01.mp3",
            "hlhj_daiyu_jz03_02.mp3"
        ],
        "text": "一点痴心，随我入红尘。"
    },
    "JZ04": {
        "variants": [
            "hlhj_daiyu_jz04_01.mp3",
            "hlhj_daiyu_jz04_02.mp3"
        ],
        "text": "清露养成身，闲愁结作心。"
    },
    "JZ05": {
        "variants": [
            "hlhj_daiyu_jz05_01.mp3",
            "hlhj_daiyu_jz05_02.mp3"
        ],
        "text": "偷来梨蕊三分白，借得梅花一缕魂。"
    },
    "JZ06": {
        "variants": [
            "hlhj_daiyu_jz06_01.mp3",
            "hlhj_daiyu_jz06_02.mp3"
        ],
        "text": "半帘秋色里，自惜此冰心。"
    },
    "JZ07": {
        "variants": [
            "hlhj_daiyu_jz07_01.mp3",
            "hlhj_daiyu_jz07_02.mp3"
        ],
        "text": "孤标原自许，何必问时人。"
    },
    "JZ08": {
        "variants": [
            "hlhj_daiyu_jz08_01.mp3",
            "hlhj_daiyu_jz08_02.mp3"
        ],
        "text": "纵是无情物，临风也有愁。"
    },
    "JZ09": {
        "variants": [
            "hlhj_daiyu_jz09_01.mp3",
            "hlhj_daiyu_jz09_02.mp3"
        ],
        "text": "孤标傲世偕谁隐，一样花开为底迟？"
    },
    "JZ10": {
        "variants": [
            "hlhj_daiyu_jz10_01.mp3",
            "hlhj_daiyu_jz10_02.mp3"
        ],
        "text": "休言举世无谈者，解语何妨片语时。"
    },
    "JZ11": {
        "variants": [
            "hlhj_daiyu_jz11_01.mp3",
            "hlhj_daiyu_jz11_02.mp3"
        ],
        "text": "灵河草木承清露，一缕幽情入世来。"
    },
    "JZ12": {
        "variants": [
            "hlhj_daiyu_jz12_01.mp3",
            "hlhj_daiyu_jz12_02.mp3"
        ],
        "text": "桃花桃叶乱纷纷，花绽新红叶凝碧。"
    },
    "JZ13": {
        "variants": [
            "hlhj_daiyu_jz13_01.mp3",
            "hlhj_daiyu_jz13_02.mp3"
        ],
        "text": "清露曾滋灵草绿，幽情犹向故人深。"
    },
    "MS01": {
        "variants": [
            "hlhj_daiyu_ms01_01.mp3",
            "hlhj_daiyu_ms01_02.mp3"
        ],
        "text": "隔了尘缘，眉目却依稀。"
    },
    "MS02": {
        "variants": [
            "hlhj_daiyu_ms02_01.mp3",
            "hlhj_daiyu_ms02_02.mp3"
        ],
        "text": "前尘虽未记，此意已相知。"
    },
    "MS03": {
        "variants": [
            "hlhj_daiyu_ms03_01.mp3",
            "hlhj_daiyu_ms03_02.mp3"
        ],
        "text": "泪有千行，只向知心处。"
    },
    "MS04": {
        "variants": [
            "hlhj_daiyu_ms04_01.mp3",
            "hlhj_daiyu_ms04_02.mp3"
        ],
        "text": "旧帕无多字，深情自往还。"
    },
    "MS05": {
        "variants": [
            "hlhj_daiyu_ms05_01.mp3",
            "hlhj_daiyu_ms05_02.mp3"
        ],
        "text": "此泪因谁起，还将此意酬。"
    },
    "MS06": {
        "variants": [
            "hlhj_daiyu_ms06_01.mp3",
            "hlhj_daiyu_ms06_02.mp3"
        ],
        "text": "留得寸心在，何妨付一笺。"
    },
    "MS07": {
        "variants": [
            "hlhj_daiyu_ms07_01.mp3",
            "hlhj_daiyu_ms07_02.mp3"
        ],
        "text": "欲问知音处，花前又独吟。"
    },
    "MS08": {
        "variants": [
            "hlhj_daiyu_ms08_01.mp3",
            "hlhj_daiyu_ms08_02.mp3"
        ],
        "text": "心事未曾改，谁来解此愁。"
    },
    "MS09": {
        "variants": [
            "hlhj_daiyu_ms09_01.mp3",
            "hlhj_daiyu_ms09_02.mp3"
        ],
        "text": "乍见已如曾识面，未言先觉是知音。"
    },
    "MS10": {
        "variants": [
            "hlhj_daiyu_ms10_01.mp3",
            "hlhj_daiyu_ms10_02.mp3"
        ],
        "text": "灵河旧约心犹记，一世清愁泪尽酬。"
    },
    "MS11": {
        "variants": [
            "hlhj_daiyu_ms11_01.mp3",
            "hlhj_daiyu_ms11_02.mp3"
        ],
        "text": "旧帕两方传密意，清泪千行答故人。"
    },
    "MS12": {
        "variants": [
            "hlhj_daiyu_ms12_01.mp3",
            "hlhj_daiyu_ms12_02.mp3"
        ],
        "text": "甘露前恩犹未报，清泪今生不肯悭。"
    },
    "MS13": {
        "variants": [
            "hlhj_daiyu_ms13_01.mp3",
            "hlhj_daiyu_ms13_02.mp3"
        ],
        "text": "欲把幽怀寻解语，何妨片语问知音。"
    },
    "MS14": {
        "variants": [
            "hlhj_daiyu_ms14_01.mp3",
            "hlhj_daiyu_ms14_02.mp3"
        ],
        "text": "此心未改当时意，谁解眉间今日愁。"
    },
    "XD01": {
        "variants": [
            "hlhj_daiyu_xd01_01.mp3",
            "hlhj_daiyu_xd01_02.mp3"
        ],
        "text": "红消香断有谁怜？"
    },
    "XD02": {
        "variants": [
            "hlhj_daiyu_xd02_01.mp3",
            "hlhj_daiyu_xd02_02.mp3"
        ],
        "text": "莫逐流水去，前路有污泥。"
    },
    "XD03": {
        "variants": [
            "hlhj_daiyu_xd03_01.mp3",
            "hlhj_daiyu_xd03_02.mp3",
            "hlhj_daiyu_xd03_03.mp3"
        ],
        "text": "轻将残蕊拾，犹恐损余香。"
    },
    "XD04": {
        "variants": [
            "hlhj_daiyu_xd04_01.mp3",
            "hlhj_daiyu_xd04_02.mp3"
        ],
        "text": "满地无人顾，花囊尚可容。"
    },
    "XD05": {
        "variants": [
            "hlhj_daiyu_xd05_01.mp3",
            "hlhj_daiyu_xd05_02.mp3"
        ],
        "text": "一囊残红，你我同惜。"
    },
    "XD06": {
        "variants": [
            "hlhj_daiyu_xd06_01.mp3",
            "hlhj_daiyu_xd06_02.mp3"
        ],
        "text": "我惜花时你亦知，一襟清泪两心痴。"
    },
    "XD07": {
        "variants": [
            "hlhj_daiyu_xd07_01.mp3",
            "hlhj_daiyu_xd07_02.mp3"
        ],
        "text": "花去无声，袖上添痕。"
    },
    "XD08": {
        "variants": [
            "hlhj_daiyu_xd08_01.mp3",
            "hlhj_daiyu_xd08_02.mp3"
        ],
        "text": "风携香去，谁收这薄命春。"
    },
    "XD09": {
        "variants": [
            "hlhj_daiyu_xd09_01.mp3",
            "hlhj_daiyu_xd09_02.mp3"
        ],
        "text": "花开易见落难寻，阶前闷杀葬花人。"
    },
    "XD10": {
        "variants": [
            "hlhj_daiyu_xd10_01.mp3",
            "hlhj_daiyu_xd10_02.mp3"
        ],
        "text": "抛珠滚玉只偷潸，镇日无心镇日闲。"
    },
    "ZH01": {
        "variants": [
            "hlhj_daiyu_zh01_01.mp3",
            "hlhj_daiyu_zh01_02.mp3"
        ],
        "text": "质本洁来还洁去，强于污淖陷渠沟。"
    },
    "ZH02": {
        "variants": [
            "hlhj_daiyu_zh02_01.mp3",
            "hlhj_daiyu_zh02_02.mp3"
        ],
        "text": "净土为衾，莫教香骨委泥尘。"
    },
    "ZH03": {
        "variants": [
            "hlhj_daiyu_zh03_01.mp3",
            "hlhj_daiyu_zh03_02.mp3"
        ],
        "text": "轻掩旧绢囊，留香归净土。"
    },
    "ZH04": {
        "variants": [
            "hlhj_daiyu_zh04_01.mp3",
            "hlhj_daiyu_zh04_02.mp3"
        ],
        "text": "不付浊流，且归这小小花冢。"
    },
    "ZH05": {
        "variants": [
            "hlhj_daiyu_zh05_01.mp3",
            "hlhj_daiyu_zh05_02.mp3"
        ],
        "text": "土深花自寂，春去我犹怜。"
    },
    "ZH06": {
        "variants": [
            "hlhj_daiyu_zh06_01.mp3",
            "hlhj_daiyu_zh06_02.mp3"
        ],
        "text": "一锄埋落瓣，半袖湿残春。"
    },
    "ZH07": {
        "variants": [
            "hlhj_daiyu_zh07_01.mp3",
            "hlhj_daiyu_zh07_02.mp3"
        ],
        "text": "芳魂且安睡，莫听杜鹃啼。"
    },
    "ZH08": {
        "variants": [
            "hlhj_daiyu_zh08_01.mp3",
            "hlhj_daiyu_zh08_02.mp3"
        ],
        "text": "花归春亦去，独自倚斜阳。"
    },
    "ZH09": {
        "variants": [
            "hlhj_daiyu_zh09_01.mp3",
            "hlhj_daiyu_zh09_02.mp3"
        ],
        "text": "未若锦囊收艳骨，一抔净土掩风流。"
    },
    "ZH10": {
        "variants": [
            "hlhj_daiyu_zh10_01.mp3",
            "hlhj_daiyu_zh10_02.mp3"
        ],
        "text": "独倚花锄泪暗洒，洒上空枝见血痕。"
    },
    "ZH11": {
        "variants": [
            "hlhj_daiyu_zh11_01.mp3",
            "hlhj_daiyu_zh11_02.mp3"
        ],
        "text": "侬今葬花人笑痴，他年葬侬知是谁？"
    },
    "ZH12": {
        "variants": [
            "hlhj_daiyu_zh12_01.mp3",
            "hlhj_daiyu_zh12_02.mp3"
        ],
        "text": "杜鹃无语正黄昏，荷锄归去掩重门。"
    },
    "XX01": {
        "variants": [
            "hlhj_daiyu_xx01_01.mp3",
            "hlhj_daiyu_xx01_02.mp3"
        ],
        "text": "一枚金麟，又添几许闲猜。"
    },
    "XX02": {
        "variants": [
            "hlhj_daiyu_xx02_01.mp3",
            "hlhj_daiyu_xx02_02.mp3",
            "hlhj_daiyu_xx02_03.mp3"
        ],
        "text": "眼空蓄泪泪空垂，暗洒闲抛却为谁？"
    },
    "XX03": {
        "variants": [
            "hlhj_daiyu_xx03_01.mp3",
            "hlhj_daiyu_xx03_02.mp3"
        ],
        "text": "窗前千竿竹，可记此斑斑。"
    },
    "XX04": {
        "variants": [
            "hlhj_daiyu_xx04_01.mp3",
            "hlhj_daiyu_xx04_02.mp3"
        ],
        "text": "帘内一身愁，随花又逐风。"
    },
    "XX05": {
        "variants": [
            "hlhj_daiyu_xx05_01.mp3",
            "hlhj_daiyu_xx05_02.mp3"
        ],
        "text": "你的话我早知道了！"
    },
    "XX06": {
        "variants": [
            "hlhj_daiyu_xx06_01.mp3",
            "hlhj_daiyu_xx06_02.mp3"
        ],
        "text": "既蒙知己意，且拭眼边珠。"
    },
    "XX07": {
        "variants": [
            "hlhj_daiyu_xx07_01.mp3",
            "hlhj_daiyu_xx07_02.mp3"
        ],
        "text": "两方旧帕，已抵万语千言。"
    },
    "XX08": {
        "variants": [
            "hlhj_daiyu_xx08_01.mp3",
            "hlhj_daiyu_xx08_02.mp3"
        ],
        "text": "一灯来相照，才觉雨声轻。"
    },
    "XX09": {
        "variants": [
            "hlhj_daiyu_xx09_01.mp3",
            "hlhj_daiyu_xx09_02.mp3"
        ],
        "text": "彩线难收面上珠，湘江旧迹已模糊。"
    },
    "XX10": {
        "variants": [
            "hlhj_daiyu_xx10_01.mp3",
            "hlhj_daiyu_xx10_02.mp3"
        ],
        "text": "花解怜人花也愁，隔帘消息风吹透。"
    },
    "GM01": {
        "variants": [
            "hlhj_daiyu_gm01_01.mp3",
            "hlhj_daiyu_gm01_02.mp3"
        ],
        "text": "一生清泪，到此偿还。"
    },
    "GM02": {
        "variants": [
            "hlhj_daiyu_gm02_01.mp3",
            "hlhj_daiyu_gm02_02.mp3"
        ],
        "text": "秋冬清泪尽，春夏也无多。"
    },
    "GM03": {
        "variants": [
            "hlhj_daiyu_gm03_01.mp3",
            "hlhj_daiyu_gm03_02.mp3"
        ],
        "text": "镜花兼水月，终究留不住。"
    },
    "GM04": {
        "variants": [
            "hlhj_daiyu_gm04_01.mp3",
            "hlhj_daiyu_gm04_02.mp3"
        ],
        "text": "春尽帘栊寂，倦魂随月去。"
    },
    "GM05": {
        "variants": [
            "hlhj_daiyu_gm05_01.mp3",
            "hlhj_daiyu_gm05_02.mp3"
        ],
        "text": "我身归去，愿你少些风雨。"
    },
    "GM06": {
        "variants": [
            "hlhj_daiyu_gm06_01.mp3",
            "hlhj_daiyu_gm06_02.mp3"
        ],
        "text": "一帕寄相思，留与你珍重。"
    },
    "GM07": {
        "variants": [
            "hlhj_daiyu_gm07_01.mp3",
            "hlhj_daiyu_gm07_02.mp3"
        ],
        "text": "此去难言，余情尚系知心人。"
    },
    "GM08": {
        "variants": [
            "hlhj_daiyu_gm08_01.mp3",
            "hlhj_daiyu_gm08_02.mp3"
        ],
        "text": "花魂若有知，犹念惜花人。"
    },
    "GM09": {
        "variants": [
            "hlhj_daiyu_gm09_01.mp3",
            "hlhj_daiyu_gm09_02.mp3"
        ],
        "text": "泪眼观花泪易干，泪干春尽花憔悴。"
    },
    "GM10": {
        "variants": [
            "hlhj_daiyu_gm10_01.mp3",
            "hlhj_daiyu_gm10_02.mp3"
        ],
        "text": "一声杜宇春归尽，寂寞帘栊空月痕！"
    },
    "GM11": {
        "variants": [
            "hlhj_daiyu_gm11_01.mp3",
            "hlhj_daiyu_gm11_02.mp3"
        ],
        "text": "醒时幽怨同谁诉，衰草寒烟无限情。"
    },
    "GM12": {
        "variants": [
            "hlhj_daiyu_gm12_01.mp3",
            "hlhj_daiyu_gm12_02.mp3"
        ],
        "text": "前尘甘露今偿尽，留取余情护此身。"
    },
    "GM13": {
        "variants": [
            "hlhj_daiyu_gm13_01.mp3",
            "hlhj_daiyu_gm13_02.mp3"
        ],
        "text": "旧帕曾题相忆字，余香犹待惜花人。"
    },
    "YY01": {
        "variants": [
            "hlhj_daiyu_yy01_01.mp3",
            "hlhj_daiyu_yy01_02.mp3"
        ],
        "text": "愿君珍摄，莫负此番牵念。"
    },
    "YY02": {
        "variants": [
            "hlhj_daiyu_yy02_01.mp3",
            "hlhj_daiyu_yy02_02.mp3"
        ],
        "text": "前恩未敢忘，余露尚堪酬。"
    },
    "YY03": {
        "variants": [
            "hlhj_daiyu_yy03_01.mp3",
            "hlhj_daiyu_yy03_02.mp3"
        ],
        "text": "雨深休独行，犹有一灯明。"
    },
    "YY04": {
        "variants": [
            "hlhj_daiyu_yy04_01.mp3",
            "hlhj_daiyu_yy04_02.mp3"
        ],
        "text": "愁病随风远，留得此身安。"
    },
    "YY05": {
        "variants": [
            "hlhj_daiyu_yy05_01.mp3",
            "hlhj_daiyu_yy05_02.mp3"
        ],
        "text": "既识寸心，何忍独承风雨。"
    },
    "YY06": {
        "variants": [
            "hlhj_daiyu_yy06_01.mp3",
            "hlhj_daiyu_yy06_02.mp3"
        ],
        "text": "你身添新伤，原也牵我心。"
    },
    "YY07": {
        "variants": [
            "hlhj_daiyu_yy07_01.mp3",
            "hlhj_daiyu_yy07_02.mp3"
        ],
        "text": "此灯分与你，长夜莫惊寒。"
    },
    "YY08": {
        "variants": [
            "hlhj_daiyu_yy08_01.mp3",
            "hlhj_daiyu_yy08_02.mp3"
        ],
        "text": "飘向天涯去，犹愿伴君行。"
    },
    "YY09": {
        "variants": [
            "hlhj_daiyu_yy09_01.mp3",
            "hlhj_daiyu_yy09_02.mp3"
        ],
        "text": "伤痕未褪心先痛，欲语还休泪已潸。"
    },
    "YY10": {
        "variants": [
            "hlhj_daiyu_yy10_01.mp3",
            "hlhj_daiyu_yy10_02.mp3"
        ],
        "text": "灵河一滴当年露，化作余恩护故人。"
    },
    "YY11": {
        "variants": [
            "hlhj_daiyu_yy11_01.mp3",
            "hlhj_daiyu_yy11_02.mp3"
        ],
        "text": "一盏清光分夜雨，愿君归路少风霜。"
    },
    "YY12": {
        "variants": [
            "hlhj_daiyu_yy12_01.mp3",
            "hlhj_daiyu_yy12_02.mp3"
        ],
        "text": "纸鸢已逐东风远，愿把沉疴一并销。"
    },
    "YY13": {
        "variants": [
            "hlhj_daiyu_yy13_01.mp3",
            "hlhj_daiyu_yy13_02.mp3"
        ],
        "text": "若使知心长抱恨，怎堪独自避风霜。"
    },
    "YY14": {
        "variants": [
            "hlhj_daiyu_yy14_01.mp3",
            "hlhj_daiyu_yy14_02.mp3"
        ],
        "text": "纵随断线归天际，犹伴孤鸢过远汀。"
    },
    "QS01": {
        "variants": [
            "hlhj_daiyu_qs01_01.mp3",
            "hlhj_daiyu_qs01_02.mp3"
        ],
        "text": "此中深意，惟有你知。"
    },
    "QS02": {
        "variants": [
            "hlhj_daiyu_qs02_01.mp3",
            "hlhj_daiyu_qs02_02.mp3"
        ],
        "text": "不须题字，已是相思。"
    },
    "QS03": {
        "variants": [
            "hlhj_daiyu_qs03_01.mp3",
            "hlhj_daiyu_qs03_02.mp3"
        ],
        "text": "难言心事，且付知音。"
    },
    "QS04": {
        "variants": [
            "hlhj_daiyu_qs04_01.mp3",
            "hlhj_daiyu_qs04_02.mp3"
        ],
        "text": "万语到唇边，只剩一回眸。"
    },
    "QS05": {
        "variants": [
            "hlhj_daiyu_qs05_01.mp3",
            "hlhj_daiyu_qs05_02.mp3"
        ],
        "text": "一页相携看，两心各自明。"
    },
    "QS06": {
        "variants": [
            "hlhj_daiyu_qs06_01.mp3",
            "hlhj_daiyu_qs06_02.mp3"
        ],
        "text": "花影落书边，余香犹未散。"
    },
    "QS07": {
        "variants": [
            "hlhj_daiyu_qs07_01.mp3",
            "hlhj_daiyu_qs07_02.mp3"
        ],
        "text": "晴雨都难定，此意付灯前。"
    },
    "QS08": {
        "variants": [
            "hlhj_daiyu_qs08_01.mp3",
            "hlhj_daiyu_qs08_02.mp3"
        ],
        "text": "半句未曾说，你心应自省。"
    },
    "QS09": {
        "variants": [
            "hlhj_daiyu_qs09_01.mp3",
            "hlhj_daiyu_qs09_02.mp3"
        ],
        "text": "满纸自怜题素怨，片言谁解诉秋心。"
    },
    "QS10": {
        "variants": [
            "hlhj_daiyu_qs10_01.mp3",
            "hlhj_daiyu_qs10_02.mp3"
        ],
        "text": "欲讯秋情众莫知，喃喃负手叩东篱。"
    },
    "QS11": {
        "variants": [
            "hlhj_daiyu_qs11_01.mp3",
            "hlhj_daiyu_qs11_02.mp3"
        ],
        "text": "几页奇文同细看，一襟花影各相知。"
    },
    "QS12": {
        "variants": [
            "hlhj_daiyu_qs12_01.mp3",
            "hlhj_daiyu_qs12_02.mp3"
        ],
        "text": "尺素未题情已满，何须重问意中人。"
    },
    "QS13": {
        "variants": [
            "hlhj_daiyu_qs13_01.mp3",
            "hlhj_daiyu_qs13_02.mp3"
        ],
        "text": "万语欲言还未语，寸心相照已相怜。"
    },
    "EN01": {
        "variants": [
            "hlhj_daiyu_en01_01.mp3",
            "hlhj_daiyu_en01_02.mp3"
        ],
        "text": "灵河旧露尚在，绛珠今入尘寰。"
    },
    "EN02": {
        "variants": [
            "hlhj_daiyu_en02_01.mp3",
            "hlhj_daiyu_en02_02.mp3"
        ],
        "text": "但把我一生所有的眼泪还他。"
    },
    "EN03": {
        "variants": [
            "hlhj_daiyu_en03_01.mp3",
            "hlhj_daiyu_en03_02.mp3"
        ],
        "text": "初逢浑似旧识，欲问又自无言。"
    },
    "EN04": {
        "variants": [
            "hlhj_daiyu_en04_01.mp3",
            "hlhj_daiyu_en04_02.mp3"
        ],
        "text": "花前一面，恍若隔世重逢。"
    },
    "D01": {
        "variants": [
            "hlhj_daiyu_d01_01.mp3",
            "hlhj_daiyu_d01_02.mp3"
        ],
        "text": "寒塘渡鹤影，冷月葬花魂……"
    },
    "D02": {
        "variants": [
            "hlhj_daiyu_d02_01.mp3",
            "hlhj_daiyu_d02_02.mp3",
            "hlhj_daiyu_d02_03.mp3",
            "hlhj_daiyu_d02_04.mp3"
        ],
        "text": "春已尽，花与人……俱杳然。"
    },
    "D03": {
        "variants": [
            "hlhj_daiyu_d03_01.mp3",
            "hlhj_daiyu_d03_02.mp3"
        ],
        "text": "宝玉，宝玉，你好……"
    },
    "D04": {
        "variants": [
            "hlhj_daiyu_d04_01.mp3",
            "hlhj_daiyu_d04_02.mp3"
        ],
        "text": "紫鹃……送我回去。"
    },
    "D05": {
        "variants": [
            "hlhj_daiyu_d05_01.mp3",
            "hlhj_daiyu_d05_02.mp3"
        ],
        "text": "一朝春尽红颜老，花落人亡两不知！"
    },
    "P01": {
        "variants": [
            "hlhj_daiyu_p01_01.mp3",
            "hlhj_daiyu_p01_02.mp3"
        ],
        "text": "湘帘轻半卷，清影到衣边。"
    },
    "P02": {
        "variants": [
            "hlhj_daiyu_p02_01.mp3",
            "hlhj_daiyu_p02_02.mp3"
        ],
        "text": "幽篁常相伴，且容我静坐。"
    },
    "P03": {
        "variants": [
            "hlhj_daiyu_p03_01.mp3",
            "hlhj_daiyu_p03_02.mp3"
        ],
        "text": "篱畔秋酣一觉清，和云伴月不分明。"
    },
    "P04": {
        "variants": [
            "hlhj_daiyu_p04_01.mp3",
            "hlhj_daiyu_p04_02.mp3"
        ],
        "text": "草木是前身，依稀入梦来。"
    },
    "P05": {
        "variants": [
            "hlhj_daiyu_p05_01.mp3",
            "hlhj_daiyu_p05_02.mp3"
        ],
        "text": "毫端蕴秀临霜写，口齿噙香对月吟。"
    },
    "P06": {
        "variants": [
            "hlhj_daiyu_p06_01.mp3",
            "hlhj_daiyu_p06_02.mp3"
        ],
        "text": "素笺犹待墨，先已动秋心。"
    },
    "P07": {
        "variants": [
            "hlhj_daiyu_p07_01.mp3",
            "hlhj_daiyu_p07_02.mp3"
        ],
        "text": "半卷湘帘半掩门，碾冰为土玉为盆。"
    },
    "P08": {
        "variants": [
            "hlhj_daiyu_p08_01.mp3",
            "hlhj_daiyu_p08_02.mp3"
        ],
        "text": "月窟仙人缝缟袂，秋闺怨女拭啼痕。"
    },
    "B01": {
        "variants": [
            "hlhj_daiyu_b01_01.mp3",
            "hlhj_daiyu_b01_02.mp3"
        ],
        "text": "寒烟小院转萧条，疏竹虚窗时滴沥。"
    },
    "B02": {
        "variants": [
            "hlhj_daiyu_b02_01.mp3",
            "hlhj_daiyu_b02_02.mp3"
        ],
        "text": "雨到竹梢，秋声又近一层。"
    },
    "B03": {
        "variants": [
            "hlhj_daiyu_b03_01.mp3",
            "hlhj_daiyu_b03_02.mp3"
        ],
        "text": "月色满寒塘，诗心入静夜。"
    },
    "B04": {
        "variants": [
            "hlhj_daiyu_b04_01.mp3",
            "hlhj_daiyu_b04_02.mp3"
        ],
        "text": "一径烟云，梦里还寻旧约。"
    },
    "H01": {
        "variants": [
            "hlhj_daiyu_h01_01.mp3",
            "hlhj_daiyu_h01_02.mp3"
        ],
        "text": "身原多病，怎禁这番摧折。"
    },
    "H02": {
        "variants": [
            "hlhj_daiyu_h02_01.mp3",
            "hlhj_daiyu_h02_02.mp3"
        ],
        "text": "风雨又来，薄衾难护。"
    },
    "DY01": {
        "variants": [
            "hlhj_daiyu_dy01_01.mp3",
            "hlhj_daiyu_dy01_02.mp3"
        ],
        "text": "欲待知心至，奈此身难久。"
    },
    "DY02": {
        "variants": [
            "hlhj_daiyu_dy02_01.mp3",
            "hlhj_daiyu_dy02_02.mp3"
        ],
        "text": "灯影将残尽，心事还未了。"
    },
    "DY03": {
        "variants": [
            "hlhj_daiyu_dy03_01.mp3",
            "hlhj_daiyu_dy03_02.mp3"
        ],
        "text": "罗衾不奈秋风力，残漏声催秋雨急。"
    },
    "DY04": {
        "variants": [
            "hlhj_daiyu_dy04_01.mp3",
            "hlhj_daiyu_dy04_02.mp3"
        ],
        "text": "花飞人倦天将暮，一缕余情未肯休。"
    },
    "W01": {
        "variants": [
            "hlhj_daiyu_w01_01.mp3",
            "hlhj_daiyu_w01_02.mp3"
        ],
        "text": "花前有知己，此意便堪珍。"
    },
    "W02": {
        "variants": [
            "hlhj_daiyu_w02_01.mp3",
            "hlhj_daiyu_w02_02.mp3"
        ],
        "text": "一卷新诗成，暂把闲愁搁。"
    },
    "W03": {
        "variants": [
            "hlhj_daiyu_w03_01.mp3",
            "hlhj_daiyu_w03_02.mp3"
        ],
        "text": "一从陶令平章后，千古高风说到今。"
    },
    "W04": {
        "variants": [
            "hlhj_daiyu_w04_01.mp3",
            "hlhj_daiyu_w04_02.mp3"
        ],
        "text": "诗成已许知音赏，愁到相知亦暂休。"
    },
    "L01": {
        "variants": [
            "hlhj_daiyu_l01_01.mp3",
            "hlhj_daiyu_l01_02.mp3"
        ],
        "text": "眼底奇缘，终成虚话。"
    },
    "L02": {
        "variants": [
            "hlhj_daiyu_l02_01.mp3",
            "hlhj_daiyu_l02_02.mp3"
        ],
        "text": "草木也知愁，韶华竟白头！"
    },
    "L03": {
        "variants": [
            "hlhj_daiyu_l03_01.mp3",
            "hlhj_daiyu_l03_02.mp3"
        ],
        "text": "桃李明年能再发，明年闺中知有谁？"
    },
    "TS01": {
        "variants": [
            "hlhj_daiyu_ts01_01.mp3",
            "hlhj_daiyu_ts01_02.mp3",
            "hlhj_daiyu_ts01_03.mp3"
        ],
        "text": "你从此可都改了罢！"
    },
    "TS02": {
        "variants": [
            "hlhj_daiyu_ts02_01.mp3",
            "hlhj_daiyu_ts02_02.mp3"
        ],
        "text": "疼成这样，还只管哄我。"
    },
    "TS03": {
        "variants": [
            "hlhj_daiyu_ts03_01.mp3",
            "hlhj_daiyu_ts03_02.mp3"
        ],
        "text": "欲语先凝噎，临君泪不收。"
    },
    "TS04": {
        "variants": [
            "hlhj_daiyu_ts04_01.mp3",
            "hlhj_daiyu_ts04_02.mp3"
        ],
        "text": "一见君扶枕，双眸又泪盈。"
    },
    "TS05": {
        "variants": [
            "hlhj_daiyu_ts05_01.mp3",
            "hlhj_daiyu_ts05_02.mp3"
        ],
        "text": "强说无疼宽我意，怎知我已泪难收。"
    },
    "TS06": {
        "variants": [
            "hlhj_daiyu_ts06_01.mp3",
            "hlhj_daiyu_ts06_02.mp3"
        ],
        "text": "枕上袖边难拂拭，任他点点与斑斑。"
    }
};
