(function() {
	return {
		"name": "手杀锦囊特效",
		"label": "手杀锦囊特效",
		"enable": true,
		"data": [{
			"label": "酒",
			"name": "手杀锦囊特效/effect_jiu",
			"action": "animation",
			"filter": function(trigger) {
				if (!trigger.player.isDying()) return true;
				else return false;
			},
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["jiu"],
			"parent": "player",
			"skills": [],
			"forbid": false
		}, {
			"label": "免伤",
			"name": "手杀锦囊特效/qy_tx_wushang",
			"action": "play",
			"trigger": {
				"player": ["damageZero", "damageCancelled"]
			},
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"audio_enable": true,
			"skills": [],
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.8",
			"skeScaleY": "0.8",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "乐不思蜀生效",
			"name": "手杀锦囊特效/qy_tx_lebusishushengxiao",
			"action": "play",
			"trigger": {
				"player": "lebuBegin"
			},
			"filter": function(trigger) {
				return trigger.parent.name !== 'useCard' && trigger._result.bool === false
			},
			"position": "player",
			"skeX": "0",
			"skeY": "10",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"audio_enable": true,
			"skills": [],
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.4",
			"skeScaleY": "0.4",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"configId": ""
		}, {
			"label": "兵粮寸断生效",
			"name": "手杀锦囊特效/qy_tx_bingliangcunduan",
			"action": "play",
			"trigger": {
				"player": "bingliangBegin"
			},
			"filter": function(trigger) {
				return trigger.parent.name !== 'useCard' && trigger._result.bool === false
			},
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"audio_enable": true,
			"skills": [],
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.4",
			"skeScaleY": "0.4",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"configId": ""
		}, {
			"label": "技能",
			"name": "手杀锦囊特效/jineng",
			"position": "player",
			"skeScale": "0.8",
			"skeX": "0",
			"skeY": "-9",
			"filter": function(trigger) {
				if (trigger.skill?.indexOf('_chongzhu') !== -1) return false; /*if(lib.skill[trigger.skill]?.equipSkill) return false; */
				if (lib.skill[trigger.skill]?.juexingji) return false;
				if (lib.skill[trigger.skill]?.limted) return false;
				if (lib.skill[trigger.skill]?.dutySkill) return false;
				else return true;
			},
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"trigger": {
				"player": "useSkillBegin"
			},
			"skills": [],
			"isJson": true,
			"action": "play"
		}, {
			"label": "五谷丰登BIG",
			"name": "手杀锦囊特效/qy_tx_wugu",
			"action": "play",
			"position": "target",
			"skeX": "1",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "0.8",
			"cards": [],
			"skills": [],
			"audio_enable": true,
			"trigger": {
				"player": "wuguBegin"
			},
			"isJson": true,
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.7",
			"skeScaleY": "0.7",
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "闪电受击",
			"name": "手杀锦囊特效/qy_tx_shandianshouji",
			"trigger": {
				"player": "changeHp"
			},
			"filter": function(trigger) {
				var evt = trigger.getParent();
				if (!evt || evt.name != 'damage') return false;
				return get.qyname(evt.card) === 'shandian'
			},
			"action": "play",
			"position": "player",
			"skeScale": "0.5",
			"skeX": "0",
			"skeY": "-5",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "0.8",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"skills": [],
			"audio_enable": true,
			"forbid": false
		}, {
			"label": "南蛮入侵BIG",
			"name": "手杀锦囊特效/qy_aar_nanmanruqin",
			"action": "play",
			"position": "screen",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["nanman"],
			"skills": [],
			"audio_enable": true,
			"parent": "screen",
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.8",
			"skeScaleY": "0.8",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "南蛮入侵受击",
			"name": "手杀锦囊特效/qy_tx_nanmanruqinshouji",
			"trigger": {
				"player": "changeHp"
			},
			"filter": function(trigger) {
				var evt = trigger.getParent();
				if (!evt || evt.name != 'damage') return false;
				return get.qyname(evt.card) === 'nanman'
			},
			"action": "play",
			"position": "player",
			"skeScale": "0.5",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "0.8",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"skills": [],
			"audio_enable": true,
			"forbid": false
		}, {
			"label": "万箭齐发BIG",
			"name": "手杀锦囊特效/qy_tx_wanjianqifa",
			"action": "play",
			"position": "screen",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["wanjian"],
			"skills": [],
			"audio_enable": true,
			"parent": "screen",
			"forbid": false,
			"position_custom": "",
			"trigger": {},
			"skeScaleX": "0.7",
			"skeScaleY": "0.7",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "万箭齐发受击",
			"name": "手杀锦囊特效/qy_tx_wanjianshouji",
			"trigger": {
				"player": "changeHp"
			},
			"filter": function(trigger) {
				var evt = trigger.getParent();
				if (!evt || evt.name != 'damage') return false;
				return get.qyname(evt.card) === 'wanjian'
			},
			"action": "play",
			"position": "player",
			"skeX": "0",
			"skeY": "10",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "0.8",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"skills": [],
			"audio_enable": true,
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.4",
			"skeScaleY": "0.4",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"configId": ""
		}, {
			"label": "火攻BIG",
			"name": "手杀锦囊特效/qy_tx_huogong",
			"action": "play",
			"position": "screen",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "3",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["huogong"],
			"skills": [],
			"audio_enable": true,
			"forbid": false,
			"parent": "screen",
			"position_custom": "",
			"trigger": {},
			"skeScaleX": "0.8",
			"skeScaleY": "0.8",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"trigger": {
				"player": "changeHp"
			},
			"filter": function(trigger) {
				var evt = trigger.getParent();
				if (!evt || evt.name != 'damage') return false;
				return get.qyname(evt.card) === 'huogong'
			},
			"label": "火攻受击",
			"name": "手杀锦囊特效/qy_tx_huogongshouji",
			"action": "play",
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "0.8",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": [],
			"skills": [],
			"audio_enable": true,
			"forbid": false,
			"position_custom": "",
			"skeScaleX": "0.8",
			"skeScaleY": "0.8",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"configId": ""
		}, {
			"label": "决斗BIG",
			"name": "手杀锦囊特效/qy_tx_juedou",
			"action": "play",
			"position": "screen",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "-1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["juedou"],
			"skills": [],
			"audio_enable": true,
			"parent": "screen",
			"forbid": false,
			"position_custom": "",
			"trigger": {},
			"skeScaleX": "1",
			"skeScaleY": "1",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "杀",
			"name": "手杀锦囊特效/sha",
			"action": "play",
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1.3",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"skills": [],
			"cards": ["sha"],
			"parent": "player",
			"forbid": false,
			"position_custom": "",
			"trigger": {},
			"skeScaleX": "1.2",
			"skeScaleY": "1.2",
			"audio_enable": false,
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "闪",
			"name": "手杀锦囊特效/shan",
			"position": "player",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1.2",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["shan"],
			"skills": [],
			"parent": "player",
			"action": "animation",
			"audio_enable": true,
			"forbid": false,
			"position_custom": "",
			"trigger": {},
			"skeScaleX": "1.2",
			"skeScaleY": "1.2",
			"isJson": false,
			"follow": false,
			"loop": false,
			"appendAnimation": [],
			"zIndex": "0",
			"filter": "",
			"configId": ""
		}, {
			"label": "桃",
			"name": "手杀锦囊特效/effect_tao",
			"action": "animation",
			"filter": function(trigger) {
				if (trigger.player.hp >= 0) return true;
				else return false;
			},
			"position": "player",
			"skeScale": "0.8",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"cards": ["tao"],
			"parent": "player",
			"skills": [],
			"forbid": false
		}, {
			"label": "技能框",
			"name": "手杀锦囊特效/baikuang",
			"action": "animation",
			"position": "player",
			"trigger": {
				"player": ["useSkillBegin", "logSkill"]
			},
			"filter": function(trigger) {
				if (trigger.skill?.indexOf('_chongzhu') !== -1) return false; /*if(lib.skill[trigger.skill]?.equipSkill) return false;*/
				if (lib.skill[trigger.skill]?.juexingji) return false;
				if (lib.skill[trigger.skill]?.limted) return false;
				if (lib.skill[trigger.skill]?.dutySkill) return false;
				if (trigger.skill?.indexOf('_') === 0) return false;
				else return true;
			},
			"skeScale": "0.5",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"skills": [],
			"cards": [],
			"forbid": false
		}, {
			"label": "主内单挑",
			"name": "手杀锦囊特效/neijian",
			"position": "screen",
			"trigger": {
				"player": "die"
			},
			"filter": function(trigger) {
				if (game.zhu && game.zhu.isAlive() && game.players.length == 2 && get.population('nei') == 1) return true;
			},
			"skeScale": "0.7",
			"skeX": "0",
			"skeY": "0",
			"audio_url": "extension/清瑶葭绮/members/假装无敌/audio/$#name#$.mp3",
			"audio_delay": "0",
			"audio_num": "0",
			"spine_delay": "0",
			"speed": "1",
			"loopCount": "1",
			"rotation": "0",
			"is_lazy": true,
			"alpha": "1",
			"skills": [],
			"cards": [],
			"follow": true,
			"action": "play",
			"audio_enable": true
		}]
	}
})()