import { lib } from "noname";
const Character = lib.element.Character;

export default {
	gz_jiubian_caocao: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_jianxiong"],
		img: "image/character/gz_jiubian_caocao.jpg",
		dieAudios: ["caocao"],
	}),
	gz_jiubian_caoren: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_jushou"],
		img: "image/character/gz_jiubian_caoren.jpg",
		dieAudios: ["caoren"],
	}),
	gz_jiubian_yuejin: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_xiaoguo"],
		hasSkinInGuozhan: true,
		img: "image/character/gz_jiubian_yuejin.jpg",
		dieAudios: ["yuejin"],
	}),
	gz_jiubian_bianfuren: new Character({
		sex: "female",
		group: "wei",
		hp: 3,
		maxHp: 3,
		skills: ["gz_jiubian_wanwei", "gz_jiubian_yuejian"],
		img: "image/character/gz_jiubian_bianfuren.jpg",
		dieAudios: ["ol_bianfuren"],
	}),
	gz_jiubian_menghuo: new Character({
		doubleGroup: ["shu"],
		sex: "male",
		group: "shu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_huoshou", "gz_jiubian_zaiqi"],
		img: "image/character/gz_jiubian_menghuo.jpg",
		dieAudios: ["menghuo"],
	}),
	gz_jiubian_ganning: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_qixi", "gz_jiubian_fenwei"],
		img: "image/character/gz_jiubian_ganning.jpg",
		dieAudios: ["re_ganning"],
	}),
	gz_jiubian_yanwen: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_shuangxiong"],
		img: "image/character/gz_jiubian_yanwen.jpg",
		names: "颜|良-文|丑",
	}),
	gz_jiubian_zhangren: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_xunu", "gz_jiubian_fengshi"],
		img: "image/character/gz_jiubian_zhangren.jpg",
		dieAudios: ["gz_zhangren"],
	}),
	gz_jiubian_jiling: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_shuangren"],
		img: "image/character/gz_jiubian_jiling.jpg",
	}),
	gz_jiubian_simashi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_yimie", "gz_jiubian_ruilve"],
		img: "image/character/gz_jiubian_simashi.jpg",
		dieAudios: ["jin_simashi"],
	}),
	gz_jiubian_yanghuiyu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		skills: ["gz_jiubian_ciwei", "gz_jiubian_caiyuan"],
		img: "image/character/gz_jiubian_yanghuiyu.jpg",
		dieAudios: ["jin_yanghuiyu"],
	}),
	gz_jiubian_xusheng: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_yicheng"],
		hasSkinInGuozhan: true,
		img: "image/character/gz_jiubian_xusheng.jpg",
		dieAudios: ["gz_xusheng"],
	}),
	gz_jiubian_chendong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_duanxie", "gz_jiubian_fenming"],
		hasSkinInGuozhan: true,
		img: "image/character/gz_jiubian_chendong.jpg",
		dieAudios: ["gz_chendong"],
	}),
	gz_jiubian_lingtong: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_xuanlve", "gz_jiubian_yongjin"],
		hasSkinInGuozhan: true,
		img: "image/character/gz_jiubian_lingtong.jpg",
		dieAudios: ["gz_lingtong"],
	}),
	gz_jiubian_lukang: new Character({
		sex: "male",
		group: "wu",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_cegu", "gz_jiubian_keshou"],
		img: "image/character/gz_jiubian_lukang.jpg",
		dieAudios: ["gz_lukang"],
	}),
	gz_jiubian_caohong: new Character({
		sex: "male",
		group: "wei",
		hp: 4,
		maxHp: 4,
		skills: ["gz_jiubian_huyuan", "gz_jiubian_heyi"],
		img: "image/character/gz_jiubian_caohong.jpg",
		dieAudios: ["caohong"],
	}),
	gz_jiubian_ganfuren: new Character({
		sex: "female",
		group: "shu",
		hp: 3,
		maxHp: 3,
		skills: ["gz_jiubian_shenzhi", "gz_jiubian_shushen"],
		img: "image/character/gz_jiubian_ganfuren.jpg",
		names: "甘|null",
		dieAudios: ["ganfuren"],
	}),
};

export const sort = "guozhan_jiubian";
