import { lib } from "noname";

const characters = {
    mjs_zhongjun: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsqiru", "mjsqingying"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_hananguo: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsqiangnuzhimo", "mjssihuifuran"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_weijie: {
        sex: "male",
        hp: 3,
        group: "xijin",
        skills: ["mjsfengshenxiuyi", "mjszhuyuzaice", "mjssimengchengji"],
        trashBin: ["junk"],
        maxHandcardBase: 6,
        dieAudios: [],
    },
    mjs_yueguang: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsyueyanxili", "mjsmingjiaoyuedi", "mjsbeigongsheying"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_wangyuanji: {
        sex: "female",
        hp: 4,
        group: "xijin",
        skills: ["mjszhujianyishi", "mjsqianchongjiexia", "mjsgongzhifangji"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_duyu: {
        sex: "male",
        hp: 6,
        group: "xijin",
        skills: ["mjsduwuku", "mjsshirupozhu", "mjslinggucunxun"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_zhanghua: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsshuangjianhualong", "mjsbowuzhi", "mjslanaitongfen"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_xunxu: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsshierdilv", "mjssibufenlei", "mjsxingguanqingxin"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhufuyan: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsxiancetuien", "mjstuhaomaoling", "mjszhuchengshuofang"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_guojie: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsjianghudaochi", "mjsquanxingzhouli", "mjsweixiazhezhong"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_fuxuan: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsyuanqishangqing", "mjsjinzhuzhechi", "mjszhengzaiqusi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_luji: {
        sex: "male",
        hp: 4,
        group: "xijin",
        skills: ["mjsyuanqingqimi", "mjslucairuhai", "mjshuatingheli"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_liushan: {
        sex: "male",
        hp: 5,
        group: "shu",
        skills: ["mjssusishoucheng", "mjslebusishu"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_weiyan: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjsziwuqimou", "mjsfangunizhan", "mjsshuiganshawo"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_simayan: {
        sex: "male",
        hp: 5,
        group: "xijin",
        skills: ["mjstaishixinlv", "mjsrongnadangzheng", "mjsshanshinanzhong"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_yanghu: {
        sex: "male",
        hp: 6,
        group: "xijin",
        skills: ["mjsqingqiuhuandai", "mjsdeguansihai", "mjsqianmouyuanji"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_liuju: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsbowangnaxian", "mjsjufenchengli", "mjsguilaiwangsi"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_guosheren: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsqiaoyanjiehuo", "mjstouhu"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_lvmeng: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsshujunkeji", "mjsduzhifenxue", "mjsbaiyidujiang"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_xusheng: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsruxupojun", "mjsbailiyicheng"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_hane: {
        sex: "female",
        hp: 4,
        group: "han",
        skills: ["mjsqianguliuyin", "mjsyuyinraoliang"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_zhengguo: {
        sex: "male",
        hp: 4,
        group: "han",
        skills: ["mjszuozhuguanju", "mjspiqinzhiji", "mjsguanzhongwoye"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_jiaxu: {
        sex: "male",
        hp: 4,
        group: "donghan",
        skills: ["mjssuanwuyice", "mjswenheluanwu", "mjsdushi"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_chengong: {
        sex: "male",
        hp: 4,
        group: "donghan",
        skills: ["mjsqiguantouyi", "mjscezhimingyi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhaoshe: {
        sex: "male",
        hp: 6,
        group: "zhao",
        skills: ["mjsxialuxiangfeng", "mjsfenggongrufa"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_limu: {
        sex: "male",
        hp: 6,
        group: "zhao",
        skills: ["mjsyanmenzongmu", "mjsjiniuxiangshi"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_weijiu: {
        sex: "male",
        hp: 4,
        group: "wèi",
        skills: ["mjsliuwangchujun", "mjsshouliweiwang"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
        doubleGroup: ["wèi", "zhāngchǔ"],
    },
    mjs_pangnuan: {
        sex: "male",
        hp: 9,
        group: "zhao",
        skills: ["mjsqinianrenjia", "mjswuguozongshi"],
        trashBin: ["rare"],
        maxHandcardBase: 2,
        dieAudios: [],
    },
    mjs_zhuowenjun: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsyebenxiangru", "mjsdanglumaijiu", "mjsbaitouyin"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_simaxiangru: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsfengqiuhuang", "mjszizhedubi", "mjsquanbaifengyi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhaojieyu: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjswoquancanggou", "mjsyaomumen"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_liufuling: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjslinzhichengtong", "mjsyantiezhiyi"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_lifuren: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsqingguoqingcheng", "mjsshanshanlaichi"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_huangyueying: {
        sex: "female",
        hp: 4,
        group: "shu",
        skills: ["mjsqiaoshoujiangxin", "mjsqizhizuomou"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_wangyi: {
        sex: "female",
        hp: 4,
        group: "wei",
        skills: ["mjszhongzhenganglie", "mjssheziquanyi"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_pingyanggongzhu: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsjianshuruye", "mjsfenglisanchun"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_huoguang: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsxingjuyouchang", "mjsmangcizaibei", "mjsshanzhuanfeili"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_houying: {
        sex: "male",
        hp: 4,
        group: "wèi",
        skills: ["mjsxiushenjiexing", "mjsshijingyinzhe", "mjsyishenmingzhi"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_zhuhai: {
        sex: "male",
        hp: 6,
        group: "wèi",
        skills: ["mjsbujuxiaoli", "mjsshijingguoshi", "mjsyishenbohu"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_gongsunzan: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjsbaimayicong", "mjszhujingzigu"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "公孙|瓒",
    },
    mjs_lingtong: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjszongmatidao", "mjsyuxuefenwei"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_xiangyan: {
        sex: "male",
        hp: 6,
        group: "chu",
        skills: ["mjspoqinfengrui", "mjschusuisaihu"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_lumochou: {
        sex: "female",
        hp: 4,
        group: "chu",
        skills: ["mjsyangchunbaixue", "mjsqingyinwangyou"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_sanghongyang: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsyantieguanying", "mjsjunshupingzhun", "mjssuanmingaomin"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhangbao: {
        sex: "male",
        hp: 4,
        group: "huangjin",
        skills: ["mjssanshiliufang", "mjshuangtianyaofa"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhanglianghuang: {
        sex: "male",
        hp: 6,
        group: "huangjin",
        skills: ["mjsshenliyiji", "mjshuangtianjingyong"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_huangjinbing: {
        sex: "male",
        hp: 1,
        group: "huangjin",
        skills: ["mjshuangtiandangli"],
        trashBin: ["rare"],
        maxHandcardBase: 0,
        dieAudios: [],
        isUnseen: true,
    },
    mjs_weiliao: {
        sex: "male",
        hp: 5,
        group: "daqin",
        skills: ["mjsxieyierzhan", "mjstianguanbingtan", "mjszhanweigongquan"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_baiqi: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsliaodihebian", "mjschuqiwuqiong", "mjsjianmie"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_lixin: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsguoshizhuangyong", "mjsyanshuizhuifeng"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhurongfuren: {
        sex: "female",
        hp: 6,
        group: "shu",
        skills: ["mjschilifeiren", "mjshuoshenzuyi"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        names: "祝|融",
    },
    mjs_taizidan: {
        sex: "male",
        hp: 4,
        group: "yan",
        skills: ["mjsziqingsuoyu", "mjsyishuicuxing"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "燕|丹",
    },
    mjs_menghuo: {
        sex: "male",
        hp: 7,
        group: "shu",
        skills: ["mjsxiongyubaishou", "mjsnanzhongzhizhu"],
        trashBin: ["junk"],
        maxHandcardBase: 2,
        dieAudios: [],
    },
    mjs_yingzheng: {
        sex: "male",
        hp: 5,
        group: "daqin",
        skills: ["mjsyitongliuhe", "mjsqinnuqishe", "mjswanlichangcheng"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_wangjian: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjshengsaosanjin", "mjsqingtian", "mjschiduancunchang"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
        chibi: true,
    },
    mjs_liuxie: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjsfudingjianxie", "mjsyidaizhao"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_liubiao: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjszishoudaishi", "mjspiananjingxiang"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_gaojianli: {
        sex: "male",
        hp: 4,
        group: "yan",
        skills: ["mjsjizhuerge", "mjsbianzhizhisheng", "mjszhuangshiquxi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_baqing: {
        sex: "female",
        hp: 4,
        group: "daqin",
        skills: ["mjslikangwancheng", "mjsdanshanvwang", "mjshuaiqingtai"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_pangtong: {
        sex: "male",
        hp: 3,
        group: "shu",
        skills: ["mjstiesuolianzhou", "mjsrushusance", "mjsyuzhanjizu"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_yuanshu: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjstugaodaihan", "mjssishisangong", "mjswangzizunda"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_luzhonglian: {
        sex: "male",
        hp: 4,
        group: "qi",
        skills: ["mjsyibudiqin", "mjsyijiandingliao", "mjszhumingshuojin"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_junwanghou: {
        sex: "female",
        hp: 4,
        group: "qi",
        skills: ["mjshuiyanshilang", "mjsshiqinjinshen", "mjsqiaojieyuhuan"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_bulianshi: {
        sex: "female",
        hp: 4,
        group: "wu",
        skills: ["mjsrenhuifuxia", "mjsguanchonghouting", "mjszhuicezhonggong"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_taishici: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsyuanbishanshe", "mjsshentinghanzzhan"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhaoji: {
        sex: "female",
        hp: 4,
        group: "daqin",
        skills: ["mjsjuehaoshanwu", "mjsyinguiganquan"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        chibi: true,
    },
    mjs_lvbuwei: {
        sex: "male",
        hp: 5,
        group: "daqin",
        skills: ["mjsqihuokeju", "mjsyiziqianjin"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_jiangwei: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjstianshuiqiliner", "mjsjiufazhongyuan", "mjsshizhikuanghan"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_fazheng: {
        sex: "male",
        hp: 4,
        group: "shu",
        skills: ["mjsqihuacesuan", "mjsyazibibao"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_jingke: {
        sex: "male",
        hp: 6,
        group: "yan",
        skills: ["mjstuqiongbijian", "mjsbaxiuerzhen", "mjschibizhizhu"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_qinwuyang: {
        sex: "male",
        hp: 6,
        group: "yan",
        skills: ["mjsfengxiaxiantu", "mjsyanyouyongshi", "mjssebianzhenkong"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_xuhuang: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsjieliangfenzi", "mjsfupochongwei"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhangchunhua: {
        sex: "female",
        hp: 4,
        group: "wei",
        skills: ["mjshualuojueqing", "mjstongshuishangshi"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_sunjian: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsmenghuxiaolin", "mjskuajiangjibiao", "mjshundingjiangdong"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_huanggai: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjskurouji", "mjszhaxiangfenzhou"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_wuguotai: {
        sex: "female",
        hp: 4,
        group: "wu",
        skills: ["mjsganluzhaoqin", "mjsdaofucangen"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_caoren: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsshimengjushou", "mjsfengfaxingling", "mjstianrenjiangjun"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
        chibi: true,
    },
    mjs_xiahoudun: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsbashidanjing", "mjsqingjianzunshi"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
        names: "夏侯|惇",
    },
    mjs_zhanghe: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsqiaobianshanzhan", "mjsyingshibuzhen", "mjshuhuhanjiang"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_caopi: {
        sex: "male",
        hp: 5,
        group: "wei",
        skills: ["mjssichengweiwu", "mjsyangexingyin", "mjsshanrangshoufeng"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_caozhi: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjscaigaobadou", "mjsqibuqiai"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_weiqing: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjszhidaohuanglong", "mjscheqihezhan"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_huoqubing: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjsheyijiawei", "mjsfenglangjuxu", "mjsyinmahanhai"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_liuche: {
        sex: "male",
        hp: 5,
        group: "xihan",
        skills: ["mjsgongshoushiyi", "mjstuienling", "mjsluntaizuiji"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
        chibi: true,
    },
    mjs_weizifu: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjspingyanouzhe", "mjsjiafuderuosi"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_zhangqian: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjssichouzhilu", "mjszaokongxiyu"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_dongzhongshu: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsbachubaijia", "mjstianrenganying", "mjschunqiufanlu"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_liguang: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjsfeijiangshelu", "mjssheshibohu"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_mibazi: {
        sex: "female",
        hp: 4,
        group: "daqin",
        skills: ["mjschushuruqin"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
        doubleGroup: ["daqin", "chu"],
    },
    mjs_chenajiao: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjsjinwucangjiao", "mjsqianjinmaifu"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_hanfei: {
        sex: "male",
        hp: 4,
        group: "han",
        skills: ["mjsfabuagui", "mjsshiyibeibian", "mjsbuqixiugu"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhongwuyan: {
        sex: "female",
        hp: 6,
        group: "qi",
        skills: ["mjszijianzhenxi", "mjszhiyongdingqi"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
        names: "钟离|春",
    },
    mjs_guowei: {
        sex: "male",
        hp: 4,
        group: "yan",
        skills: ["mjsqianjinshigu", "mjsqingziweishi"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_baoyuan: {
        sex: "male",
        hp: 9,
        group: "han",
        skills: ["mjsbaizhanwujie", "mjsluzhanfenghui", "mjsxuruizhuizhan"],
        trashBin: ["junk"],
        dieAudios: [],
        maxHandcardBase: 2,
    },
    mjs_shenbuhai: {
        sex: "male",
        hp: 4,
        group: "han",
        skills: ["mjsyishuyuguo", "mjschangyuwushi", "mjsjuncaoqibing"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 5,
    },
    mjs_yanzhaowang: {
        sex: "male",
        hp: 5,
        group: "yan",
        skills: ["mjsxiuzhujintai", "mjsqiangbingfaqi"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 4,
        names: "姬|职",
    },
    mjs_yueyi: {
        sex: "male",
        hp: 6,
        group: "yan",
        skills: ["mjsgujunlianke", "mjsfeikeshunmin", "mjsbaohuiwangshu"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 3,
    },
    mjs_zhaoweihou: {
        sex: "female",
        hp: 4,
        group: "zhao",
        skills: ["mjszhiziweibing", "mjswuminheyoujun"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 4,
        //maxHandcardBase: 5,
    },
    mjs_linxiangru: {
        sex: "male",
        hp: 4,
        group: "zhao",
        skills: ["mjswanbiguizhao", "mjsmianchizhihui", "mjsjiangxianghe"],
        trashBin: ["epic"],
        dieAudios: [],
        maxHandcardBase: 5,
    },
    mjs_lianpo: {
        sex: "male",
        hp: 6,
        group: "zhao",
        skills: ["mjsfujingqingzui", "mjsshangnengfanfou"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 3,
    },
    mjs_mengyao: {
        sex: "female",
        hp: 4,
        group: "zhao",
        skills: ["mjsyanruoshaorong", "mjsguseerge"],
        trashBin: ["junk"],
        dieAudios: [],
        maxHandcardBase: 4,
    },
    mjs_pingyuanjun: {
        sex: "male",
        hp: 4,
        group: "zhao",
        skills: ["mjszhanxiaolixin", "mjslilingzhihun"],
        trashBin: ["legend"],
        dieAudios: [],
        maxHandcardBase: 5,
        names: "赵|胜",
    },
    mjs_suqin: {
        sex: "male",
        hp: 4,
        group: "zhao",
        skills: ["mjshezong", "mjsliuguoxiangyin", "mjscigu"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_ximenbao: {
        sex: "male",
        hp: 5,
        group: "wèi",
        skills: ["mjsyinzhangshierqu", "mjshouminboku", "mjsrubaohebo"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "西门|豹",
    },
    mjs_xinlingjun: {
        sex: "male",
        hp: 4,
        group: "wèi",
        skills: ["mjsshikesanqian", "mjsdaofucijiang", "mjsweisishi"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "魏|无忌",
    },
    mjs_ruji: {
        sex: "female",
        hp: 4,
        group: "wèi",
        skills: ["mjsqiefujiuzhao", "mjsxianhuanshibao"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_zhengxiu: {
        sex: "female",
        hp: 4,
        group: "chu",
        skills: ["mjsyanxiugongchan", "mjsyinduquanshi"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        //maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_songyu: {
        sex: "male",
        hp: 4,
        group: "chu",
        skills: ["mjsqugaohegua", "mjsjiubian"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_chunshenjun: {
        sex: "male",
        hp: 4,
        group: "chu",
        skills: ["mjsyihuajiemu", "mjswuwangzhizai"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "黄|歇",
    },
    mjs_tiandan: {
        sex: "male",
        hp: 5,
        group: "qi",
        skills: ["mjshuoniuzhen", "mjsjieqiujiuren"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_mengchangjun: {
        sex: "male",
        hp: 4,
        group: "qi",
        skills: ["mjsfenquanshiyi", "mjsjiaotusanku", "mjsjiminggoudao"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "田|文",
    },
    mjs_zhangyi: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjslianheng", "mjszhongkoushuojin", "mjszhezhu"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_fanju: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjswuguibaixiang", "mjsyuanjiaojingong", "mjsqingyunzhishang"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_fusu: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjsshanyoufusu", "mjsxianwenyumin"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "嬴|扶苏",
    },
    mjs_lisi: {
        sex: "male",
        hp: 4,
        group: "daqin",
        skills: ["mjsfanshumingfa", "mjsjianzhizhuke"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_ziying: {
        sex: "male",
        hp: 5,
        group: "daqin",
        skills: ["mjsmodaiqinwang", "mjstuimiaozhujian"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "嬴|子婴",
    },
    mjs_zhanghan: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsshetushoubing", "mjsxianmei"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_mengyi: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjsneimoufazhi", "mjszhongxin"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_mengtian: {
        sex: "male",
        hp: 6,
        group: "daqin",
        skills: ["mjszhuchenshoufan", "mjszhongxin"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_dongzhuo: {
        sex: "male",
        hp: 6,
        group: "donghan",
        skills: ["mjsqitianfeizhu", "mjscangbaoumeiwu"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_caiwenji: {
        sex: "female",
        hp: 4,
        group: "donghan",
        skills: ["mjshujiashibapai", "mjsbeifenlichou"],
        trashBin: ["epic"],
        maxHandcardBase: 4,
        dieAudios: [],
        names: "蔡|琰",
    },
    mjs_huatuo: {
        sex: "male",
        hp: 4,
        group: "donghan",
        skills: ["mjsguaguliaodu", "mjsqingnangmiaoshou"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_zuoci: {
        sex: "male",
        hp: 1,
        group: "donghan",
        skills: ["mjszhibeixicao", "mjsdunjiatianshu", "mjsfeishengtaixu"],
        trashBin: ["legend"],
        maxHandcardBase: 1,
        dieAudios: [],
    },
    mjs_diaochan: {
        sex: "female",
        hp: 4,
        group: "donghan",
        skills: ["mjsgeliansongmu", "mjsbiyuezhizi"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_yuanshao: {
        sex: "male",
        hp: 5,
        group: "donghan",
        skills: ["mjssishisangong", "mjsbaiwanxiongbing", "mjsfujinfengliu"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_lvbu: {
        sex: "male",
        hp: 7,
        group: "donghan",
        skills: ["mjswushuangfeijiang", "mjslangziyexin", "mjsyuanmensheji"],
        trashBin: ["epic"],
        maxHandcardBase: 2,
        dieAudios: [],
    },
    mjs_chensheng: {
        sex: "male",
        hp: 5,
        group: "zhāngchǔ",
        skills: ["mjsgouhuohuming", "mjsningyouzhonghu", "mjsjieganerqi"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhoubo: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjsxiaozouwange", "mjsxuepingzhulv"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_fankuai: {
        sex: "male",
        hp: 6,
        group: "xihan",
        skills: ["mjsxiandeng", "mjspaitazhiru"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_chenping: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsliuchuqiji", "mjsguaxiweimen"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_hanxin: {
        sex: "male",
        hp: 5,
        group: "xihan",
        skills: ["mjsshimianmaifu", "mjsbeishuiyizhan", "mjsdengtanbaijiang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_liubang: {
        sex: "male",
        hp: 5,
        group: "xihan",
        skills: ["mjszhansheqiyi", "mjsdafengge", "mjsyuefasanzhang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
        chibi: true,
    },
    mjs_lvzhi: {
        sex: "female",
        hp: 4,
        group: "xihan",
        skills: ["mjslinchaochengzhi", "mjszhulvweiwang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_xiaohe: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsjuxianweijiang", "mjsjizhaoyouzhu"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhangliang: {
        sex: "male",
        hp: 4,
        group: "xihan",
        skills: ["mjsbolangzhuiqin", "mjsyunchouweiwo", "mjsyiqiaoshoushu"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_xiangliang: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjsjiangmenlichu", "mjsxianfazhiren"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_jibu: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjsyinuoqianjin", "mjsweiqirenxia"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_fanzeng: {
        sex: "male",
        hp: 4,
        group: "xichu",
        skills: ["mjswangqinbichu", "mjshongmenyan"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_longqie: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjszhongyongshiwu", "mjsanyingzhulei"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_xiangyu: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjspofuchenzhou", "mjsbawang"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
        chibi: true,
    },
    mjs_yingbu: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjsgongguanzhuhou", "mjsdaxiguowang"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_yuji: {
        sex: "female",
        hp: 4,
        group: "xichu",
        skills: ["mjsmeiren", "mjsbawangbieji"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_zhonglimo: {
        sex: "male",
        hp: 6,
        group: "xichu",
        skills: ["mjsfeilianshi", "mjsgugengzhichen"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
        names: "钟离|眜",
    },
    mjs_xunyu: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjserhujingshi", "mjsquhutunlang", "mjsxunlingliuxiang"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_caocao: {
        sex: "male",
        hp: 5,
        group: "wei",
        skills: ["mjstianbufuwo", "mjsxietianyiling", "mjstianxiaguixin"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_dianwei: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsguzhielai", "mjszhuhuguojian"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_guojia: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjsshishengshibai", "mjstianduyingcai", "mjsyicepingliao"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        chibi: true,
    },
    mjs_simayi: {
        sex: "male",
        hp: 4,
        group: "wei",
        skills: ["mjslangguyingshi", "mjsren"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "司马|懿",
    },
    mjs_xuchu: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjshuchi", "mjsxiejiahanzhan"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhangliao: {
        sex: "male",
        hp: 6,
        group: "wei",
        skills: ["mjsxiaoyaozhiti", "mjsbailangchihui"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhenfu: {
        sex: "female",
        hp: 4,
        group: "wei",
        skills: ["mjspianruojinghong", "mjsluoshenfu"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_huangzhong: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjsbaodaoweilao", "mjsbaibuchuanyang", "mjsjiaobingzhiji"],
        trashBin: ["junk"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_liubei: {
        sex: "male",
        hp: 5,
        group: "shu",
        skills: ["mjsweixianweide", "mjssangumaolu", "mjsxiemindujiang"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_machao: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjsliangzhoutieji", "mjsjinshizi"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
        chibi: true,
    },
    mjs_sunshangxiang: {
        sex: "female",
        hp: 4,
        group: "shu",
        skills: ["mjsxiaojiniangniang", "mjsdaojianqingyuan"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
        chibi: true,
    },
    mjs_zhangfei: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjswanrendi", "mjsheduandangyang", "mjsshijiuruming"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhaoyun: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjsqiangchurulong", "mjshunshenshidan", "mjsqijinqichu"],
        trashBin: ["rare"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_zhugeliang: {
        sex: "male",
        hp: 4,
        group: "shu",
        skills: ["mjsqimendunjia", "mjsjinnangmiaoji"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
        names: "诸葛|亮",
    },
    mjs_guanyu: {
        sex: "male",
        hp: 6,
        group: "shu",
        skills: ["mjswanjunqushou", "mjswushengyijue", "mjsshuiyanqijun"],
        trashBin: ["legend"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_daqiao: {
        sex: "female",
        hp: 4,
        group: "wu",
        skills: ["mjsqiushuiyiren", "mjsjunshengbieli"],
        trashBin: ["junk"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_ganning: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjsbairenyexi", "mjsjinfanyouxia"],
        trashBin: ["rare"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
    mjs_lusu: {
        sex: "male",
        hp: 4,
        group: "wu",
        skills: ["mjszhiqunxiangzeng", "mjsjiezhoudimeng"],
        trashBin: ["rare"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_luxun: {
        sex: "male",
        hp: 4,
        group: "wu",
        skills: ["mjshuopolianying", "mjsjieyigongwu"],
        trashBin: ["legend"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_sunce: {
        sex: "male",
        hp: 6,
        group: "wu",
        skills: ["mjshujuyingyang", "mjsxiaobawang"],
        trashBin: ["epic"],
        maxHandcardBase: 3,
        dieAudios: [],
    },
    mjs_sunquan: {
        sex: "male",
        hp: 5,
        group: "wu",
        skills: ["mjschengmashehu", "mjsquanxuelishi"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
        isZhugong: true,
    },
    mjs_xiaoqiao: {
        sex: "female",
        hp: 4,
        group: "wu",
        skills: ["mjsbingdifurong", "mjstaozhiyaoyao"],
        trashBin: ["junk"],
        maxHandcardBase: 5,
        dieAudios: [],
        chibi: true,
    },
    mjs_zhouyu: {
        sex: "male",
        hp: 4,
        group: "wu",
        skills: ["mjsxiongziyingfa", "mjsfanjianchuhuan", "mjshuoshaochibi"],
        trashBin: ["epic"],
        maxHandcardBase: 5,
        dieAudios: [],
    },
    mjs_zhangjiao: {
        sex: "male",
        hp: 5,
        group: "huangjin",
        skills: ["mjstaipingyaoshu", "mjstaipingdao"],
        trashBin: ["legend"],
        maxHandcardBase: 4,
        dieAudios: [],
    },
};

const isChildrensDay = (() => {
    const date = new Date();
    if (date.getMonth() !== 5) {
        return false;
    }
    const day = date.getDate();
    return day === 1;
})();

for (let i in characters) {
    //characters[i].trashBin.push(`ext:名将杀/image/character/${lib.config.extension_名将杀_outcrop}/${i}.jpg`);
    characters[i].img = `extension/名将杀/image/character/${lib.config.extension_名将杀_outcrop}/${i}.jpg`;
    /*if (isChildrensDay && characters[i].chibi) {
        characters[i].img = `extension/名将杀/skin/image/${i}/mengjiang.jpg`;
    }*/
    characters[i].dieAudios.addArray([`ext:名将杀/audio/die/${i}.mp3`, `ext:名将杀/audio/die/${i}2.mp3`]);
    characters[i].enterAudios ??= [];
    characters[i].killAudios ??= [];
    characters[i].victoryAudios ??= [];
    characters[i].enterAudios.addArray([`ext:名将杀/audio/enter/${i}.mp3`, `ext:名将杀/audio/enter/${i}2.mp3`]);
    characters[i].killAudios.addArray([`ext:名将杀/audio/kill/${i}.mp3`, `ext:名将杀/audio/kill/${i}2.mp3`]);
    characters[i].victoryAudios.addArray([`ext:名将杀/audio/victory/${i}.mp3`, `ext:名将杀/audio/victory/${i}2.mp3`]);
}

export default characters;
