import { get } from "noname";

const translates = {
    mjs_yanshi: "偃师",
    mjszaohuatonggong: "造化同功",
    mjszaohuatonggong_info: "在选将阶段被选择时，额外选择1个武将，制作1个与其相同的傀儡，然后傀儡代替你登场，并且由你控制傀儡。当你的傀儡在场时，其他角色只能查看傀儡的技能。",
    mjschaijiejishu: "拆解机枢",
    mjschaijiejishu_info: "当傀儡重伤或累计受到3次伤害时，你代替傀儡登场，并拆解傀儡，此时傀儡每剩余1点体力，你摸2张牌，并立即进行1个出牌阶段。",
    mjsmugesuxing: "木革塑形",
    mjsmugesuxing_info: "限定，你可以弃置2张♣牌，选择并制作1个新的傀儡，然后傀儡代替你登场。",

    mjs_majun: "马钧",
    mjsshuizhuanbaixi: "水转百戏",
    mjsshuizhuanbaixi_info: "出牌阶段限1次，将至少1张♠牌洗回牌堆，然后选择一名角色，依次翻开牌堆顶等量张牌并自动对其打出，然后你获得其中无法被打出的牌。",
    mjslonggujiliu: "龙骨汲流",
    mjslonggujiliu_info: "出牌阶段限1次，你可以将1张♣牌选择并转化为1张装备牌。当你打出装备牌后，将弃牌堆中的♠牌洗回牌堆，并且你的装备区每存在1张牌，就获得1张♠牌。",
    mjsqiaosijueshi: "巧思绝世",
    mjsqiaosijueshi_info: "出牌阶段限1次，你可以将一名角色的1张牌的花色改为你选择的任意1种花色。",

    mjs_zhongjun: "终军",
    mjsqiru: "弃繻",
    mjsqiru_info: "出牌阶段限1次，你可以令一名其他角色选择展示其1张手牌，然后你可以弃置任意张点数和与展示牌相同的牌，对其造成1点伤害，若此过程中你只弃置了1张牌，重置此技能。",
    mjsqingying: "请缨",
    mjsqingying_info: "出牌阶段开始时，你可以令一名其他角色交给你至少1张牌，然后直到回合结束，当你造成伤害时，其摸1张牌。",

    mjs_hananguo: "韩安国",
    mjsqiangnuzhimo: "强弩之末",
    mjsqiangnuzhimo_info: "当一名其他角色失去最后的手牌时，你可以令其受到的下1次伤害+1，并且下回合手牌上限-1；或交给其至少1张手牌。",
    mjssihuifuran: "死灰复燃",
    mjssihuifuran_info: "每个回合限1次，当你失去最后的手牌时，你可以摸牌至手牌上限，然后卜卦，若结果为♠，手牌上限-1；若结果为♥，手牌上限+1。",

    mjs_weijie: "卫玠",
    mjsfengshenxiuyi: "风神秀异",
    mjsfengshenxiuyi_info: "当你即将受到伤害时，若你的手牌上限＞体力值，则改为减少等量的手牌上限。当你打出牌时，若所有其他角色手牌中都不存在与此牌相同牌名的牌，则你的手牌上限+1，并可以选择一名有手牌的角色，获得1张与其手牌中相同牌名的牌。",
    mjszhuyuzaice: "珠玉在侧",
    mjszhuyuzaice_info: "当你打出牌后，你可以削弱一名与你距离最近的其他角色手牌中所有相同牌名的牌。",
    mjssimengchengji: "思梦成疾",
    mjssimengchengji_info: "出牌阶段，你可以获得1张与所有其他角色手牌中牌名都不相同的牌，然后失去1点体力，若没有因此获得牌，此技能失效直到当前回合结束。",

    mjs_yueguang: "乐广",
    mjsyueyanxili: "约言析理",
    mjsyueyanxili_info: "回合结束时，若你在本回合的每个出牌阶段打出的牌数都≤2，直到你的下个回合开始，当其他角色主动打出战法牌后，你可以立即将1张牌当作同名战法牌打出。",
    mjsmingjiaoyuedi: "名教乐地",
    mjsmingjiaoyuedi_info: "其他角色的回合结束时，若其在本回合没有发动过技能，且未拥有此技能，则你可以令其获得此技能。你的出牌阶段结束时，若你上个出牌阶段内没有发动过技能，则你可以摸0张牌，并进行1个额外的出牌阶段，场上每额外存在1个名教乐地，此技能的摸牌数+1。",
    mjsbeigongsheying: "杯弓蛇影",
    mjsbeigongsheying_info: "当一名其他角色获得牌后，若其中包含与本轮对其造成过伤害的牌相同牌名的牌，则其选择是否将其中相同牌名的牌交给你，并令此技能对其无效，直到本轮结束；否则其每个回合结束时失去1点体力，直到其再次触发此技能。",

    mjs_wangyuanji: "王元姬",
    mjszhujianyishi: "烛奸抑势",
    mjszhujianyishi_info: "出牌阶段结束时，你可以获得一名其他角色的1张牌，并且当其发动“出牌阶段限1次”的技能后，你可以获得其2张牌，直到你的下个回合开始。",
    mjsqianchongjiexia: "谦冲接下",
    mjsqianchongjiexia_info: "每个回合限1次，当你获得其他角色的牌时，你可以令你与其描述中有“出牌阶段限1次”的技能下个出牌阶段的发动次数+1。",
    mjsgongzhifangji: "躬执纺绩",
    mjsgongzhifangji_info: "出牌阶段限1次，获得1张行动牌，然后你可以将此牌交给一名其他角色，或者令一名未拥有此技能的其他角色获得此技能。",

    mjs_duyu: "杜预",
    mjsduwuku: "杜武库",
    mjsduwuku_info: "登场，复制牌堆中每种牌名的牌各1张放入武库。应战/出牌阶段限1次，你可以立即打出武库中的一张牌。",
    mjsshirupozhu: "势如破竹",
    mjsshirupozhu_info: "当你打出的战法牌造成伤害后，可以削弱目标角色2张牌，且你本回合选择其为目标的下1张杀对其伤害+1。",
    mjslinggucunxun: "陵谷存勋",
    mjslinggucunxun_info: "击杀，永久标记此时牌堆顶和牌堆底的各1张牌。之后每当有此标记的牌被打出时，你摸3张牌。",

    mjs_zhanghua: "张华",
    mjsshuangjianhualong: "双剑化龙",
    mjsshuangjianhualong_info: `登场，添加随机花色和点数的${get.poptip("mjslongquanjian")}/${get.poptip("mjstaiejian")}至牌堆底。当你打出牌时，若此牌花色或点数与【龙泉剑】/【太阿剑】相同，则你获得【龙泉剑】/【太阿剑】。当你同时装备【龙泉剑】和【太阿剑】时，增强你的所有其他牌。 `,
    mjsbowuzhi: "博物志",
    mjsbowuzhi_info: "出牌阶段限1次，你可以弃置1张牌，查看牌堆中前10张与此牌花色相同的牌与这些牌在牌堆中的位置，你可以交换这些牌的位置，并且可以选择获得其中2张牌。",
    mjslanaitongfen: "兰艾同焚",
    mjslanaitongfen_info: `阵亡，销毁所有${get.poptip("mjslongquanjian")}和${get.poptip("mjslongquanjian")}，然后可以削弱任意名其他角色的所有牌。`,

    mjs_xunxu: "荀勖",
    mjsshierdilv: "十二笛律",
    mjsshierdilv_info: "当你打出牌后，若本回合你打出过的牌的总点数等于12，你可以选择1个点数，查看牌堆中前12张与此牌点数相同的牌在牌堆中的位置，你可以交换这些牌的位置，并且可以选择获得其中1张牌。",
    mjssibufenlei: "四部分类",
    mjssibufenlei_info: "登场，你将1~8的点数分为甲乙丙丁4组；每轮结束时，若你本轮打出过每组点数的至少1张牌，随机获得每组点数的各1张牌。",
    mjsxingguanqingxin: "省官清心",
    mjsxingguanqingxin_info: "当你打出牌时，若此牌的点数<上一张你打出牌的点数，你可以削弱一名角色的1张牌。",

    mjs_zhufuyan: "主父偃",
    mjsxiancetuien: "献策推恩",
    mjsxiancetuien_info: "每个回合限1次，当有角色回合外获得大于1张牌时，你可以令其将其中至少1张牌，交给你指定的另外一名其他角色。所有角色每累计获得其他角色4张牌时，你摸1张牌。",
    mjstuhaomaoling: "徙豪茂陵",
    mjstuhaomaoling_info: "出牌阶段限1次，令任意名有牌的角色依次将至少1张牌放回牌堆顶，这些角色若因此放回大于1张牌，则在本轮结束时，摸等量张牌。",
    mjszhuchengshuofang: "筑城朔方",
    mjszhuchengshuofang_info: "当有牌被放入牌堆时，你随机将其中1张牌的复制放入“朔方”。每个回合限1次，当你即将受到伤害时，你可以随机销毁“朔方”中的1张牌，令此伤害-1，或者选择获得朔方中的1张牌。",

    mjs_guojie: "郭解",
    mjsjianghudaochi: "江湖道敕",
    mjsjianghudaochi_info: "当有角色即将受到伤害时，你可以交给伤害来源1张牌并令此伤害-1，接下来本局游戏伤害来源再次对同一角色造成伤害时，你令其随机弃置1张牌。",
    mjsquanxingzhouli: "权行州里",
    mjsquanxingzhouli_info: "每轮限1次，当有角色失去最后一张手牌时，你可以选择另外任意名有牌的其他角色，令这些角色可以将1张牌当作杀对其打出，若拒绝，则下个摸牌阶段摸牌数-1。在此过程中当有一名角色阵亡时，你与伤害来源各失去1点体力。",
    mjsweixiazhezhong: "为侠者众",
    mjsweixiazhezhong_info: "阵亡，接下来本局游戏每轮结束时，所有本轮对其他角色造成过伤害的角色失去1点体力。",

    mjs_fuxuan: "傅玄",
    mjsyuanqishangqing: "元气上清",
    mjsyuanqishangqing_info: "回合开始时，获得1点元气，并且之后每回合获得的元气+1。出牌阶段，你可以消耗2点元气，令一名角色添加1张你选择的类型的牌至其手牌。",
    mjsjinzhuzhechi: "近朱者赤",
    mjsjinzhuzhechi_info: "当一名其他角色在其回合内累计打出3张战法牌时，你可以令一名与其距离为1的角色获得1张战法牌，若目标角色是你，你获得2点元气。",
    mjszhengzaiqusi: "政在去私",
    mjszhengzaiqusi_info: "限定，选择一种类型的牌，将场上所有此类型的牌放回牌堆顶。",

    mjs_luji: "陆机",
    mjsyuanqingqimi: "缘情绮靡",
    mjsyuanqingqimi_info: "当有角色成为本轮首次被打出的战法牌的目标时，若你或打出此牌的角色不是此牌的目标，你可以令你或打出此牌的角色也成为此牌的目标。",
    mjslucairuhai: "陆才如海",
    mjslucairuhai_info: "回合开始时，你可以将所有手牌当作本轮未被打出过的任意1张战法牌打出，然后直到你的下个回合开始，当一名其他角色打出本轮首次被打出的战法牌后，你可以将所有手牌当作本轮未被打出过的任意1张战法牌打出。",
    mjshuatingheli: "华亭鹤唳",
    mjshuatingheli_info: "每轮结束时，若你在本轮受到过伤害，你可以选择并添加1张你本局游戏打出过的战法牌到手牌，每种牌限1次，之后每当有其他角色打出与此牌相同名称的战法牌时，你可以随机削弱其1张牌。",

    mjs_liushan: "刘禅",
    mjssusishoucheng: "素丝守成",
    mjssusishoucheng_info: "出牌阶段限4次，可以令一名其他角色查看并打出你的1张手牌，其打出此牌时无法选择你为目标，并且当其打出此牌后，将此过程中获得的牌交给你，若其无法打出，则其随机弃置1张牌。",
    mjslebusishu: "乐不思蜀",
    mjslebusishu_info: "你打出的牌无法选择其他角色为目标，并且生效2次。",

    mjs_weiyan: "魏延",
    mjsziwuqimou: "子午奇谋",
    mjsziwuqimou_info: "每轮开始时，你可以将任意牌当作杀对一名其他角色打出，若此杀造成伤害，你摸2张牌。",
    mjsfangunizhan: "反骨逆战",
    mjsfangunizhan_info: "当你选择杀的目标时，目标本轮每对你打出过1张杀，此杀对其伤害+1。",
    mjsshuiganshawo: "谁敢杀我",
    mjsshuiganshawo_info: "限定，令所有其他角色依次对你打出1张杀，若无法打出，则你获得其1张牌，并且出杀次数+1。",

    mjs_simayan: "司马炎",
    mjstaishixinlv: "泰始新律",
    mjstaishixinlv_info: "限定，你选择1张手牌，削弱游戏中所有同名牌，接下来本局游戏当你打出削弱牌后，可以削弱一名角色的2张牌。",
    mjsrongnadangzheng: "容纳谠正",
    mjsrongnadangzheng_info: "你的怒只能当作上1张被打出的战法牌打出。你打出的或你装备区的削弱牌以普通牌效果生效。",
    mjsshanshinanzhong: "善始难终",
    mjsshanshinanzhong_info: `当你打出削弱牌时，摸1张牌，当所有角色累计打出15张削弱牌后，失去技能容纳说正${get.poptip("mjsrongnadangzheng")}，此技能增加效果“每个回合限1次，当你获得牌时，削弱这些牌”。`,

    mjs_yanghu: "羊祜",
    mjsqingqiuhuandai: "轻裘缓带",
    mjsqingqiuhuandai_info: "你的每个阶段结束时：若你的装备区没有牌，则你的下一轮的同名阶段改为出牌阶段；若你的装备区有牌，则你的下一轮的同名阶段改为摸牌阶段。",
    mjsdeguansihai: "德冠四海",
    mjsdeguansihai_info: "出牌阶段限1次，当你选择其他角色为牌的目标时，你可以将你的装备牌收回手牌，并且令你与所有此牌的目标分别展示2张手牌(不足则全展示)，然后你选择其中一名其他角色，交换你与其展示的牌，若交换后你的手牌总点数全场最大，添加1张装备牌至手牌并且装备上限+1。",
    mjsqianmouyuanji: "潜谋远计",
    mjsqianmouyuanji_info: "回合结束时，你选择一名其他角色，你本回合每打出过1张装备牌，就随机削弱其1张牌。",

    mjs_liuju: "刘据",
    mjsbowangnaxian: "博望纳贤",
    mjsbowangnaxian_info: "每个回合限1次，当你失去最后的手牌时，其他角色可以交给你任意张牌；当你获得其他角色的牌时，随机获得其中1张牌的复制，每名其他角色每个回合限1次。",
    mjsjufenchengli: "惧忿成戾",
    mjsjufenchengli_info: "限定，回合结束时，若你的体力值全场最低，你可以销毁所有手牌，摸2倍数量张牌，并获得1个额外的出牌阶段，直到此阶段结束时，若没有角色阵亡，你失去全部体力。",
    mjsguilaiwangsi: "归来望思",
    mjsguilaiwangsi_info: "阵亡，你可以令一名其他角色的手牌上限-1，并且之后每个摸牌阶段的摸牌数-1。",

    mjs_guosheren: "郭舍人",
    mjsqiaoyanjiehuo: "巧言解祸",
    mjsqiaoyanjiehuo_info: "每个回合限1次，当其他角色选择你为牌的目标时，你可以立即打出1张相同花色或点数的牌，然后抵消此牌。",
    mjstouhu: "投壶",
    mjstouhu_info: "出牌阶段限1次，卜卦，并翻开牌堆顶的3张牌，然后你可以弃置1张牌，若点数与卜卦牌相同，则你获得这3张牌，否则你选择获得其中1张，并将另外2张牌按原顺序放回牌堆顶。",
    
    mjs_lvmeng: "吕蒙",
    mjsshujunkeji: "束军克己",
    mjsshujunkeji_info: "每个回合结束时，若你此回合没有打出过牌，你获得1张杀；回合开始时，你每拥有2张杀，随机添加1张战法牌到你的手牌。",
    mjsduzhifenxue: "笃志奋学",
    mjsduzhifenxue_info: "你每获得3张战法牌，手牌上限+2。",
    mjsbaiyidujiang: "白衣渡江",
    mjsbaiyidujiang_info: "当你的手牌上限大于体力值时，隐藏你的手牌数和体力值，并且回合开始时，你可以选择获得一名其他角色的所有手牌，并对其打出其中的所有杀，然后你失去此技能。",

    mjs_xusheng: "徐盛",
    mjsruxupojun: "濡须破军",
    mjsruxupojun_info: "当你的装备区获得或失去装备牌时，你可以将一名其他角色的1张牌移出游戏，直到你的下个回合结束。",
    mjsbailiyicheng: "百里疑城",
    mjsbailiyicheng_info: "当你成为其他角色打出牌的目标时，你可以立即打出1张装备牌，或者将一名角色装备区的1张牌收回其手牌，然后每个回合限1次，随机添加1张装备牌到你的手牌。",

    mjs_hane: "韩娥",
    mjsqianguliuyin: "千古留音",
    mjsqianguliuyin_info: `登场/当你的体力值变化后，令一名未获得${get.poptip("mjsqianguliuyin_faq")}的角色获得一种${get.poptip("mjsqianguliuyin_faq")}，或者令一名已经获得${get.poptip("mjsqianguliuyin_faq")}的角色切换一种${get.poptip("mjsqianguliuyin_faq")}。`,
    mjsqianguliuyin_faq: "余音",
    mjsqianguliuyin_faq_info: "余音效果：<br>宫：获得时/每个回合首次打出战法牌时，随机添加1张战法牌至手牌。<br>商：获得时/每个回合首次造成伤害后，随机弃置1张牌。<br>角：获得时/每个回合非摸牌阶段首次获得牌后，随机添加1张装备牌至手牌。<br>徵：获得时/出牌阶段开始时，可以立即打出1张杀，此杀不消耗出杀次数。<br>羽：获得时/每个回合首次弃置牌后，失去1点体力。",
    mjsyuyinraoliang: "余音绕梁",
    mjsyuyinraoliang_info: `阵亡，令一名其他角色获得你的${get.poptip("mjsqianguliuyin_faq")}，并且保留当前的所有${get.poptip("mjsqianguliuyin_faq")}效果，持续到游戏结束。`,

    mjs_zhengguo: "郑国",
    mjszuozhuguanju: "作注溉渠",
    mjszuozhuguanju_info: `每轮开始时，你可以将至多等同于存活角色张牌转化为${get.poptip("mjsqu")}并交给等量角色，然后你摸对应数量张牌。你的${get.poptip("mjsqu")}不计入手牌上限。`,
    mjspiqinzhiji: "疲秦之计",
    mjspiqinzhiji_info: "每名角色每个回合限2次，当其他角色获得你的牌时，若其手牌中有【渠】，你可以令其顺时针或者逆时针随机将1张牌交给相邻的手牌中有【渠】的角色，然后该角色重复此动作直到你。",
    mjsguanzhongwoye: "关中沃野",
    mjsguanzhongwoye_info: "出牌阶段限1次，你可以将1张牌交给有【渠】的角色，然后你可以销毁其1张【渠】并摸1张牌。",

    mjs_jiaxu: "贾诩",
    mjssuanwuyice: "算无遗策",
    mjssuanwuyice_info: "你打出的战法牌无法被识破抵消；你可以将任意战法牌当作识破打出。",
    mjswenheluanwu: "文和乱武",
    mjswenheluanwu_info: "限定，直到你的下个回合开始，所有其他角色无法从牌堆获得牌，并且出杀次数+1。",
    mjsdushi: "毒士",
    mjsdushi_info: "所有角色每累计受到3点杀的伤害时，你获得1张战法牌。",

    mjs_chengong: "陈宫",
    mjsqiguantouyi: "弃官投义",
    mjsqiguantouyi_info: "当你在非摸牌阶段获得牌时，每回合每种牌限1次，可以将其中1张牌交给一名其他角色，令其可以对你选择的另外一名其他角色打出此牌，然后你下个摸牌阶段摸牌数+1，若其没有打出，你受到1点伤害。",
    mjscezhimingyi: "策直明义",
    mjscezhimingyi_info: "受伤，你可以令一名其他角色受到的下1次伤害+1，当你选择的目标下1次受伤后，你获得1张战法牌。",

    mjs_zhaoshe: "赵奢",
    mjsxialuxiangfeng: "狭路相逢",
    mjsxialuxiangfeng_info: "出牌阶段限1次，你可以选择一名其他角色，翻开牌堆顶的5张牌，你获得其中除杀之外的牌，令其对你依次打出剩余杀，然后：其对你再次执行此效果。",
    mjsfenggongrufa: "奉公如法",
    mjsfenggongrufa_info: "出牌阶段限1次，你可以令一名其他角色进行1个弃牌阶段，你获得其在此阶段内弃置的牌。",

    mjs_limu: "李牧",
    mjsyanmenzongmu: "雁门纵牧",
    mjsyanmenzongmu_info: "当你成为其他角色打出杀的目标时，其不消耗出杀次数并且你下个出牌阶段的出杀次数+1。当你每累计受伤或应战3次时，你可以手牌上限+1，然后摸牌至手牌上限，并可以立即打出1张牌。",
    mjsjiniuxiangshi: "击牛飨士",
    mjsjiniuxiangshi_info: "应战/出牌阶段限1次，你可以弃置1张牌，增强手牌中的杀。",

    mjs_weijiu: "魏咎",
    mjsliuwangchujun: "流亡储君",
    mjsliuwangchujun_info: `登场，你可以选择一名其他角色，当其弃置牌时，你获得其中1张牌，并转化为${get.poptip("mjsyibing")}。当你打出${get.poptip("mjsyibing")}时，你令一名其他角色进入连环状态。`,
    mjsshouliweiwang: "受立魏王",
    mjsshouliweiwang_info: `限定，回合开始时，你每有1张${get.poptip("mjsyibing")}，你可以增加1点体力上限，然后回复1点体力，并获得技能${get.poptip("mjsfenshenjiumin")}。`,
    mjsfenshenjiumin: "焚身救民",
    mjsfenshenjiumin_info: "回合结束时，你进入连环状态，摸2张牌，然后受到1点火焰伤害，并失去1点体力上限。",

    mjs_pangnuan: "庞煖",
    mjsqinianrenjia: "耆年韧甲",
    mjsqinianrenjia_info: "回合开始/结束时，失去1点体力，手牌上限+1。当你的体力值首次变为1时，摸牌至手牌上限。",
    mjswuguozongshi: "五国纵师",
    mjswuguozongshi_info: "摸牌阶段开始时，若你的手牌上限≥5，则你摸牌阶段摸牌数+3，出杀次数+4。",
    
    mjs_zhuowenjun: "卓文君",
    mjsyebenxiangru: "夜奔相如",
    mjsyebenxiangru_info: "出牌阶段开始时，你可以翻开牌堆底的5张牌，将其中的♠牌交给一名其他角色，然后可以将剩余牌按原顺序放回牌堆顶。",
    mjsdanglumaijiu: "当垆卖酒",
    mjsdanglumaijiu_info: "每个回合限1次，当你获得♥牌时，添加1张酒到你手牌，你可以将此牌交给一名其他角色，然后选择获得其1张牌。",
    mjsbaitouyin: "白头吟",
    mjsbaitouyin_info: "受伤，你可以令任意名其他角色随机弃置1张牌。",

    mjs_simaxiangru: "司马相如",
    mjsfengqiuhuang: "凤求凰",
    mjsfengqiuhuang_info: "出牌阶段开始时，你可以翻开牌堆顶的5张牌，将其中的♥牌交给一名其他角色，然后可以将剩余牌按原顺序放回牌堆底。",
    mjszizhedubi: "自着犊鼻",
    mjszizhedubi_info: "你可以弃置1张♠牌，令你打出的下1张行动牌或战法牌生效2次。",
    mjsquanbaifengyi: "劝百讽一",
    mjsquanbaifengyi_info: "每个回合限2次，当你造成伤害时，你可以令任意名未受到此伤害的角色摸1张牌。",

    mjs_zhaojieyu: "赵婕妤",
    mjswoquancanggou: "握拳藏钩",
    mjswoquancanggou_info: `登场，添加1张随机花色和点数的${get.poptip("mjsyugou")}，当一名其他角色打出与其相同花色或点数的牌后，你可以将【玉钩】置入该角色的装备区，之后每个回合限1次，当该角色获得牌时，你添加这些牌的复制到你的手牌。`,
    mjsyaomumen: "尧母门",
    mjsyaomumen_info: `当你失去${get.poptip("mjsyugou")}后的第14个回合结束时，用${get.poptip({
        id: "character_mjs_liufuling",
        name: "刘弗陵",
        type: "character",
        dialog: "characterDialog",
    })}替换你的角色。每个回合限1次，当你成为其他角色打出牌的目标时，可以将目标改为装备区有【玉钩】的一名其他角色。`,

    mjs_liufuling: "刘弗陵",
    mjslinzhichengtong: "麟趾承统",
    mjslinzhichengtong_info: "登场，获得场上手牌数最多的一名其他角色的所有手牌的复制。",
    mjsyantiezhiyi: "盐铁之议",
    mjsyantiezhiyi_info: "出牌阶段限1次，你可以选择令所有角色摸牌阶段的摸牌数+1，或者令所有其他角色的手牌上限-1，你的手牌上限+1。",

    mjs_lifuren: "李夫人",
    mjsqingguoqingcheng: "倾国倾城",
    mjsqingguoqingcheng_info: "出牌阶段限2次，你可以令一名其他角色查看并选择添加1张你的手牌的复制，当其打出此牌首次造成伤害时，你摸2张牌。",
    mjsshanshanlaichi: "姗姗来迟",
    mjsshanshanlaichi_info: "你在游戏的第2轮开始时登场。登场/阵亡，令一名其他角色摸牌至手牌上限，并且回复所有体力值。",

    mjs_huangyueying: "黄月英",
    mjsqiaoshoujiangxin: "巧手匠心",
    mjsqiaoshoujiangxin_info: "出牌阶段限1次，你可以选择1张手牌或场上任意1张装备牌，获得1张此牌的复制。",
    mjsqizhizuomou: "奇智佐谋",
    mjsqizhizuomou_info: "你主动打出的战法牌生效2次，每种战法牌每回合限1次。",

    mjs_wangyi: "王异",
    mjszhongzhenganglie: "忠贞刚烈",
    mjszhongzhenganglie_info: "回合结束时，你可以令一名其他角色的手牌数变为与你相同，若其手牌数因此改变>=2，你受到1点伤害。",
    mjssheziquanyi: "舍子全义",
    mjssheziquanyi_info: "受伤，你可以令一名角色弃置所有手牌并摸牌至手牌上限。",

    mjs_pingyanggongzhu: "平阳公主",
    mjsjianshuruye: "荐姝入掖",
    mjsjianshuruye_info: "每局游戏限2次，出牌阶段限1次，选择一名其他角色，然后抽取3张武将牌，选择其中一名武将的1个技能，令其获得此技能，直到你再次发动此技能或你阵亡；当其首次发动此技能时，你的手牌上限+1，并摸牌至手牌上限。",
    mjsfenglisanchun: "凤历三春",
    mjsfenglisanchun_info: "每局游戏限3次，出牌阶段限1次，选择一名其他男性角色，每名角色限1次，选择其1个技能并添加1个与其同名的技能，直到你再次发动此技能或目标角色阵亡。",

    mjs_huoguang: "霍光",
    mjsxingjuyouchang: "行举有常",
    mjsxingjuyouchang_info: "当你打出牌时，若此牌的点数等于当前轮数，你摸1张牌，并增加1点体力上限。",
    mjsmangcizaibei: "芒刺在背",
    mjsmangcizaibei_info: "你的回合内，当其他角色打出牌时，若此牌点数＞你打出的上1张牌的点数，则你可以令其失去1点体力。",
    mjsshanzhuanfeili: "擅专废立",
    mjsshanzhuanfeili_info: "限定，令两名其他角色交换体力上限与体力值、手牌和装备区的牌，然后你减少两者体力值差值的体力上限，并弃置等量张牌。",

    mjs_houying: "侯嬴",
    mjsxiushenjiexing: "修身洁行",
    mjsxiushenjiexing_info: "你受到的>1的伤害-1。",
    mjsshijingyinzhe: "市井隐者",
    mjsshijingyinzhe_info: "你打出目标唯一的战法牌在生效前暗置。回合结束时，本回合你每打出1张战法牌，就可以获得1张装备牌，并交给一名其他角色。",
    mjsyishenmingzhi: "以身明志",
    mjsyishenmingzhi_info: "出牌阶段，你可以失去1点体力，然后获得1张战法牌。",

    mjs_zhuhai: "朱亥",
    mjsbujuxiaoli: "不拘小礼",
    mjsbujuxiaoli_info: "你造成的>1的伤害+1。",
    mjsshijingguoshi: "市井国士",
    mjsshijingguoshi_info: "装备上限+1；你的装备牌仅你可见。",
    mjsyishenbohu: "以身搏虎",
    mjsyishenbohu_info: "杀伤，令目标角色流血+1。你对流血效果的角色伤害+1。",

    mjs_gongsunzan: "公孙瓒",
    mjsbaimayicong: "白马义从",
    mjsbaimayicong_info: "登场，复制牌堆中所有的坐骑牌，并洗入牌堆；你的坐骑牌的效果会触发2次。",
    mjszhujingzigu: "筑京自固",
    mjszhujingzigu_info: "受伤，你获得1张坐骑牌。",

    mjs_lingtong: "凌统",
    mjszongmatidao: "纵马提刀",
    mjszongmatidao_info: "每回合限1次，出杀，获得并装备1张装备牌。",
    mjsyuxuefenwei: "浴血奋威",
    mjsyuxuefenwei_info: "出牌阶段限1次，你可以失去1点体力，获得2张杀，并且出杀次数+1。",

    mjs_xiangyan: "项燕",
    mjspoqinfengrui: "破秦锋锐",
    mjspoqinfengrui_info: "每个回合首次成为其他角色打出牌的目标时，获得2张杀，若此牌对你造成伤害，你进行1个出牌阶段。",
    mjschusuisaihu: "楚虽三户",
    mjschusuisaihu_info: `阵亡，你可以令一名其他角色获得技能${get.poptip("mjspoqinfengrui")}，并且之后每回合的摸牌数+2。`,

    mjs_lumochou: "卢莫愁",
    mjsyangchunbaixue: "阳春白雪",
    mjsyangchunbaixue_info: "每回合每种牌限1次，当你以其他角色为目标打出牌后，若此牌没有被其他角色抵消或响应，则你可以将此牌交给一名其他角色，此牌再次被打出时无法被抵消和响应。",
    mjsqingyinwangyou: "清音忘忧",
    mjsqingyinwangyou_info: "当你交给其他角色手牌后，随机弃置其卜卦区中的1张牌，若其卜卦区中没有牌，每个回合限2次，你可以选择并添加任意1张牌到其手牌。",

    mjs_sanghongyang: "桑弘羊",
    mjsyantieguanying: "盐铁官营",
    mjsyantieguanying_info: "出牌阶段限1次，你可以查看一名其他角色的手牌，展示其中所有的♦/♣牌，令另外一名其他角色选择获得其中1张牌，然后交给你1张牌。",
    mjsjunshupingzhun: "均输平准",
    mjsjunshupingzhun_info: "当你获得其他角色的牌时，你可以令这些牌的点数+1或-1（最小为1，最大为8），然后若这些牌的总点数等于你手牌中其他牌的总点数，你可以令一名角色获得1张你选择的花色或点数的牌。",
    mjssuanmingaomin: "算缗告缗",
    mjssuanmingaomin_info: "每个回合限1次，当有其他角色获得另外一名角色的牌后，你可以查看这些牌并获得其中1张。",

    mjs_zhangbao: "张宝",
    mjssanshiliufang: "三十六方",
    mjssanshiliufang_info: "出牌阶段限1次，你可以弃置至少1张牌，然后令一名其他角色弃置等量的牌，因此弃置的牌的总点数每累计36点，你可以对一名角色造成2点雷电伤害。",
    mjshuangtianyaofa: "黄天妖法",
    mjshuangtianyaofa_info: "当你获得杀时，你将其转化为雷杀（♦4）。当有角色受到雷电伤害时，你摸1张牌。",

    mjs_zhanglianghuang: "张梁",
    mjsshenliyiji: "神力一击",
    mjsshenliyiji_info: "当有角色弃置♦牌后，你可以将1张牌转化为雷杀（♦4），并且你对目标角色打出的下1张雷杀的伤害+1。",
    mjshuangtianjingyong: "黄天精勇",
    mjshuangtianjingyong_info: `出牌阶段限1次，你可以弃置1张♦牌，若场上存活角色少于8名，且不存在因此召唤的${get.poptip({
        id: "character_mjs_huangjinbing",
        name: "黄巾兵",
        type: "character",
        dialog: "characterDialog",
    })}，则召唤一名黄巾兵，否则令所有黄巾势力的角色增加1点体力上限。`,

    mjs_huangjinbing: "黄巾兵",
    mjshuangtiandangli: "黄天当立",
    mjshuangtiandangli_info: "登场，卜卦，你的体力上限与手牌上限之和等于卜卦牌点数，并随机分配。若卜卦点数为0，则你的体力上限与手牌上限均为8。",

    mjs_weiliao: "尉缭",
    mjsxieyierzhan: "挟义而战",
    mjsxieyierzhan_info: "当有角色受伤时，你可以选择查看并增强其1张手牌。",
    mjstianguanbingtan: "天官兵谈",
    mjstianguanbingtan_info: "你无法卜卦；其他角色卜卦后，你获得1张♣牌。",
    mjszhanweigongquan: "战威攻权",
    mjszhanweigongquan_info: "当你打出增强牌时，可以弃置一名其他角色任意区域的1张牌。",

    mjs_baiqi: "白起",
    mjsliaodihebian: "料敌合变",
    mjsliaodihebian_info: "当其他角色失去最后的手牌后，你可以立即对其打出1张杀。",
    mjschuqiwuqiong: "出奇无穷",
    mjschuqiwuqiong_info: "每个回合限1次，当你在回合外需要打出行动牌时，可以将任意1张手牌当作要打出的牌打出，然后获得1张杀。 ",
    mjsjianmie: "歼灭",
    mjsjianmie_info: "出杀/杀伤，可以销毁一名其他角色任意区域的1张牌。",

    mjs_lixin: "李信",
    mjsguoshizhuangyong: "果势壮勇",
    mjsguoshizhuangyong_info: "当你造成伤害后，若你的体力值不满，则你回复1点体力；当你即将造成伤害时，若你的体力值满，你可以令此伤害+1。",
    mjsyanshuizhuifeng: "衍水追锋",
    mjsyanshuizhuifeng_info: "你可以弃置1张牌，出杀次数+1，然后令此技能需要弃置的牌数改为2直到当前回合结束。击杀，你本回合每打出过1张杀，就可以摸2张牌，然后此技能本回合无效。",

    mjs_zhurongfuren: "祝融夫人",
    mjschilifeiren: "赤黎飞刃",
    mjschilifeiren_info: `当你打出的牌被响应时，你可以将1张牌转化为杀对其打出，此杀获得对应${get.poptip("mjschilifeiren_faq")}。`,
    mjschilifeiren_faq: "花色的效果",
    mjschilifeiren_faq_info: `花色的效果：<br>金（♦）：贯穿。<br>木（♣）：杀伤，${get.poptip("mjs_debuff_zhongdu_faq")}+1。<br>水（♠）：杀伤，随机获得目标1张牌。<br>火（♥）：杀伤，随机烧毁目标1张牌。<br>土（☯）：此杀伤害+1。`,
    mjshuoshenzuyi: "火神族裔",
    mjshuoshenzuyi_info: "你每个回合首次受到的火焰伤害-1，对其他角色首次造成的火焰伤害+1。",

    mjs_taizidan: "太子丹",
    mjsziqingsuoyu: "恣卿所欲",
    mjsziqingsuoyu_info: "当有角色失去最后1张手牌时，你可以失去1点体力，令其摸2张牌。",
    mjsyishuicuxing: "易水促行",
    mjsyishuicuxing_info: "每个角色出牌阶段结束时，若你在当前回合内失去过体力，你可以将当前回合角色的弃牌阶段改为出牌阶段，当其在此阶段造成伤害时，你回复1点体力。",

    mjs_menghuo: "孟获",
    mjsxiongyubaishou: "雄驭百兽",
    mjsxiongyubaishou_info: `出牌阶段限1次，你可以将1张牌转化为对应花色的${get.poptip("mjsxiongyubaishou_faq")}。当有角色失去猛兽牌时，你可以销毁此牌，然后获得1张与此牌花色相同的牌。`,
    mjsxiongyubaishou_faq: "猛兽牌",
    mjsxiongyubaishou_faq_info: `猛兽牌包括：<br>虎（♦）：回合结束时，你可以令一名其他角色${get.poptip("mjs_debuff_liuxue_faq")}+1<br>蛇（♣）：杀伤，令目标${get.poptip("mjs_debuff_zhongdu_faq")}+1<br>鳄（♠）：手牌上限+1。出牌阶段开始时，出杀次数+1<br>鹰（♥）：摸牌+1，手牌上限+1<br>象（☯）：装备上限+1。回合结束时回复1点体力。除此牌外的猛兽效果+1`,
    mjsnanzhongzhizhu: "南中之主",
    mjsnanzhongzhizhu_info: "出牌阶段限1次，获得1张你手牌中没有的花色的牌。",

    mjs_yingzheng: "嬴政",
    mjsyitongliuhe: "一统六合",
    mjsyitongliuhe_info: "与你势力相同的角色造成伤害后，你可以将受伤角色的势力改为与你相同或移除受伤角色的势力。当全场首次仅存在一种势力时，你回复全部体力，之后你的回合开始时，随机获得每个无势力角色的1张牌。",
    mjsqinnuqishe: "秦弩齐射",
    mjsqinnuqishe_info: "出牌阶段限1次，翻开牌堆顶的8张牌，你可以为其中的每张杀选择一名不同的其他角色作为目标，依次对目标打出，然后你可以将剩余牌按原顺序放回牌堆顶或弃置。",
    mjswanlichangcheng: "万里长城",
    mjswanlichangcheng_info: "每轮开始时，对你翻开牌堆顶的8张牌，将其中的闪放入万里长城，然后你可以将剩余牌按原顺序放回牌堆顶或弃置。每个回合限1次，与你势力相同的角色需要打出闪时，你可以代替其从万里长城中打出。",

    mjs_wangjian: "王翦",
    mjshengsaosanjin: "横扫三晋",
    mjshengsaosanjin_info: "当你的杀选择目标时，随机将目标3张手牌移出游戏，直到其下回合开始。",
    mjsqingtian: "请田",
    mjsqingtian_info: "出牌阶段开始时，你可以选择一名其他角色，其可以交给你任意张牌，然后你此阶段增加1次出杀次数。",
    mjschiduancunchang: "尺短寸长",
    mjschiduancunchang_info: "其他角色回合开始时，若其本轮交给过你牌，则可以令你对另一名其他角色打出1张杀，若你拒绝则获得你的1张牌。",

    mjs_liuxie: "刘协",
    mjsfudingjianxie: "负鼎见胁",
    mjsfudingjianxie_info: "其他角色出牌阶段限1次，若其与你的距离为1，其可以交给你1张牌，然后其可以打出你的1张手牌，若此牌造成伤害，你与其摸1张牌。",
    mjsyidaizhao: "衣带诏",
    mjsyidaizhao_info: "限定，你可以选择一名其他角色，令所有其他角色与其的距离始终为1。当其受到伤害时，伤害来源角色摸1张牌。当其阵亡时，你获得其所有牌，并且重置此技能。",

    mjs_liubiao: "刘表",
    mjszishoudaishi: "自守待时",
    mjszishoudaishi_info: "每回合每种花色限1次，你可以弃置2张同花色的牌，摸2张牌。",
    mjspiananjingxiang: "偏安荆襄",
    mjspiananjingxiang_info: "回合结束时，若你本回合没有造成过伤害，直到你的下回合开始，当其他角色弃牌时，你随机获得其中1张牌。",

    mjs_gaojianli: "高渐离",
    mjsjizhuerge: "击筑而歌",
    mjsjizhuerge_info: "当你打出牌时，若此牌与你当前回合打出的前1张牌的点数不同，可以弃置一名其他角色的1张牌；若点数相同，则你摸1张牌，并且此技能失效直到当前回合结束。",
    mjsbianzhizhisheng: "变徴之声",
    mjsbianzhizhisheng_info: "当你打出牌时，若此牌与你当前回合打出的前1张牌的花色不同，则你可以弃置所有手牌，并摸等量牌；若花色相同，则你摸1张牌，并且此技能失效直到当前回合结束。",
    mjszhuangshiquxi: "壮士去兮",
    mjszhuangshiquxi_info: "阵亡，你可以对一名其他角色打出弃牌堆中你本轮弃置的杀，直到目标重伤。",

    mjs_baqing: "巴清",
    mjslikangwancheng: "礼抗万乘",
    mjslikangwancheng_info: `每轮开始时，场上所有角色的手牌中，每有1张杀，就添加1张${get.poptip("mjsdansha")}到你的手牌。`,
    mjsdanshanvwang: "丹砂女王",
    mjsdanshanvwang_info: `你的${get.poptip("mjsdansha")}不计入手牌上限；打出【丹砂】不消耗次数，直到你在当前阶段获得【丹砂】；当其他角色打出【丹砂】时，你获得1张♦牌。`,
    mjshuaiqingtai: "怀清台",
    mjshuaiqingtai_info: `你阵亡后，你的座位变为${get.poptip("mjshuaiqingtai_faq")}。`,
    mjshuaiqingtai_faq: "怀清台",
    mjshuaiqingtai_faq_info: "怀清台：没有体力和手牌，无法成为任何手牌或技能的目标，回合开始时，令所有未对巴清造成过伤害的角色各摸1张牌，然后回合结束。",

    mjs_pangtong: "庞统",
    mjstiesuolianzhou: "铁索连舟",
    mjstiesuolianzhou_info: "你可以将♦牌当作连环打出。当处于连环状态的角色受到属性伤害时，你摸1张牌。",
    mjsrushusance: "入蜀三策",
    mjsrushusance_info: "每轮限1次，其他角色的回合开始时，你可以随机添加3张战法牌至其手牌，令其可以立即打出其中1张，然后弃置另外2张牌，否则销毁这些牌。",
    mjsyuzhanjizu: "欲展骥足",
    mjsyuzhanjizu_info: "出牌阶段限1次，你可以将所有牌转化为等量随机战法牌。",

    mjs_yuanshu: "袁术",
    mjstugaodaihan: "涂高代汉",
    mjstugaodaihan_info: `登场，添加${get.poptip("mjschuanguoyuxi")}至你的手牌。出牌阶段限1次，若你没有【传国玉玺】，你可以弃置至少1张牌并获得【传国玉玺】，若你是从其他角色处获得【传国玉玺】，令其获得这些牌。`,
    mjswangzizunda: "妄自尊大",
    mjswangzizunda_info: "与你距离为1的其他角色，手牌上限-1。回合结束时，你的手牌上限-1。",

    mjs_luzhonglian: "鲁仲连",
    mjsyibudiqin: "义不帝秦",
    mjsyibudiqin_info: "其他角色无法改变你的势力。当你打出牌后，若此牌的花色是你在当前回合首次打出，你可以将此牌放入牌堆底，然后摸1张牌。",
    mjsyijiandingliao: "一箭定聊",
    mjsyijiandingliao_info: "出牌阶段限1次，你可以弃置至多3张花色各不相同的手牌，并令一名其他角色弃置与你弃置的牌数量、花色均相同的牌，然后将这些牌放入牌堆底。若其弃置的牌数量不足，则其失去等量体力。",
    mjszhumingshuojin: "珠明烁今",
    mjszhumingshuojin_info: "回合结束时，你可以将本回合你放入牌堆底的其中1张牌交给一名角色。",

    mjs_junwanghou: "君王后",
    mjshuiyanshilang: "慧眼识郎",
    mjshuiyanshilang_info: "登场，你可以选择一名其他男性角色。每个回合你们的体力值或手牌数变化后首次相同，你们各摸1张牌。",
    mjsshiqinjinshen: "事秦谨慎",
    mjsshiqinjinshen_info: "每个回合限1次，体力值>你的角色对你造成伤害后，你可以令一名角色摸1张牌；手牌数>你的角色对你造成伤害后，你可以令一名角色回复1点体力值。",
    mjsqiaojieyuhuan: "巧解玉环",
    mjsqiaojieyuhuan_info: "每个回合限1次，当你成为其他角色打出的战法牌目标时，你可以将其转化为杀并对你打出。",

    mjs_bulianshi: "步练师",
    mjsrenhuifuxia: "仁惠抚下",
    mjsrenhuifuxia_info: "当一名其他角色受到伤害时，你可以交给其1张牌，然后令其获得并装备1张装备牌。",
    mjsguanchonghouting: "宠冠后庭",
    mjsguanchonghouting_info: "每个角色的回合结束时，若你的手牌数不是全场最多，你摸1张牌。",
    mjszhuicezhonggong: "追册中宫",
    mjszhuicezhonggong_info: "阵亡，你可以将所有手牌交给一名其他角色，然后令其获得并装备装备牌直到达到装备上限或获得了装备上限张装备牌。",

    mjs_taishici: "太史慈",
    mjsyuanbishanshe: "猿臂善射",
    mjsyuanbishanshe_info: "当你选择杀的目标时，若目标手牌中没有闪，则此杀伤害+1；闪避，获得1张杀。",
    mjsshentinghanzzhan: "神亭酣战",
    mjsshentinghanzzhan_info: "出牌阶段限1次，选择一名其他角色，从你开始依次对对方打出手牌中的所有杀，直至其中一方因此重伤。若有角色因此阵亡，你失去此技能。",

    mjs_zhaoji: "赵姬",
    mjsjuehaoshanwu: "绝好善舞",
    mjsjuehaoshanwu_info: "当你打出牌时，你可以弃置1张牌，然后摸1张牌。当你打出最后1张手牌时，摸1张牌。",
    mjsyinguiganquan: "迎归甘泉",
    mjsyinguiganquan_info: "限定，失去你的所有其他技能，然后获得弃牌堆中所有你弃置的牌。",

    mjs_lvbuwei: "吕不韦",
    mjsqihuokeju: "奇货可居",
    mjsqihuokeju_info: "每个回合限1次，当你获得牌时，你可以将其中任意张牌交给一名其他角色，然后你摸1张牌。其他角色每累计打出4张获得过的你的牌后，你与其各摸2张牌。",
    mjsyiziqianjin: "一字千金",
    mjsyiziqianjin_info: `当你累计打出或弃置7张牌后，添加1张${get.poptip("mjslvshichunqiu")}到你的手牌。`,

    mjs_jiangwei: "姜维",
    mjstianshuiqiliner: "天水麒麟儿",
    mjstianshuiqiliner_info: "出牌阶段限1次，你可以将任意1张牌当作调兵遣将打出。",
    mjsjiufazhongyuan: "九伐中原",
    mjsjiufazhongyuan_info: "出牌阶段限1次，摸2张牌，出杀次数+1，并且出牌阶段结束时选择手牌上限-1或体力上限-1。",
    mjsshizhikuanghan: "矢志匡汉",
    mjsshizhikuanghan_info: "当你的体力值首次变为1时，你可以将所有牌交给一名其他角色，令其对另外一名其他角色打出所有杀，然后弃置所有牌。",

    mjs_fazheng: "法正",
    mjsqihuacesuan: "奇画策算",
    mjsqihuacesuan_info: "出牌阶段，当你打出牌时，若此牌点数等于你本回合累计打出的牌数，则获得2张与此牌点数相同的牌。",
    mjsyazibibao: "睚眦必报",
    mjsyazibibao_info: "每回合限1次，受伤，你可以查看并打出伤害来源的1张手牌，若其手牌均无法打出，你对其造成1点伤害。",

    mjs_jingke: "荆轲",
    mjstuqiongbijian: "图穷匕见",
    mjstuqiongbijian_info: `出牌阶段限1次，当你失去最后1张手牌时，添加1张${get.poptip("mjsxufurenbishou")}和1张杀至你的手牌。`,
    mjsbaxiuerzhen: "把袖而揕",
    mjsbaxiuerzhen_info: "出牌阶段限1次，你可以交出1张手牌给一名其他角色，令其与你的距离变为1，并且你对其造成的下一次伤害+1，直到回合结束。",
    mjschibizhizhu: "持匕掷柱",
    mjschibizhizhu_info: "当你的杀被抵消后，你可以弃置1张武器牌，对目标角色造成1点伤害。",

    mjs_qinwuyang: "秦舞阳",
    mjsfengxiaxiantu: "奉匣献图",
    mjsfengxiaxiantu_info: "其他角色出牌阶段限1次，其可以令你摸1张牌，然后你可以对其指定的另外一名角色打出杀。",
    mjsyanyouyongshi: "燕有勇士",
    mjsyanyouyongshi_info: `当你失去体力时，你可以令一名角色摸1张牌，并且令其造成下1次杀的伤害时，令目标角色${get.poptip("mjs_debuff_zhongdu_faq")}+1。`,
    mjssebianzhenkong: "色变振恐",
    mjssebianzhenkong_info: "出杀，你失去1点体力。",

    mjs_xuhuang: "徐晃",
    mjsjieliangfenzi: "截粮焚辎",
    mjsjieliangfenzi_info: "每个回合限1次，杀伤，你可以选择1种花色并烧毁目标所有此花色的牌，然后令一名角色摸等量的牌。",
    mjsfupochongwei: "斧破重围",
    mjsfupochongwei_info: "若你对目标打出的杀被抵消，你可以弃置1张牌，令此杀仍然造成伤害。",

    mjs_zhangchunhua: "张春华",
    mjshualuojueqing: "花落绝情",
    mjshualuojueqing_info: "每个回合限1次，当你选择其他角色为打出牌的目标时，你可以失去1点体力，令其封禁。",
    mjstongshuishangshi: "痛随伤逝",
    mjstongshuishangshi_info: `当一名角色失去体力时，你可以令一名其他角色${get.poptip("mjs_debuff_liuxue_faq")}+1，然后你摸1张牌。`,

    mjs_sunjian: "孙坚",
    mjsmenghuxiaolin: "猛虎啸林",
    mjsmenghuxiaolin_info: "装备上限+1；当你的装备区获得或失去装备牌时，你打出的下1张杀的伤害+1。",
    mjskuajiangjibiao: "跨江击表",
    mjskuajiangjibiao_info: "出牌阶段限1次，你可以弃置1张装备牌，对一名其他角色造成1点伤害，然后若你与此目标距离>1，随机添加1张装备牌至你的手牌。",
    mjshundingjiangdong: "魂定江东",
    mjshundingjiangdong_info: "阵亡，你可以令一名其他角色的装备上限+2。",

    mjs_huanggai: "黄盖",
    mjskurouji: "苦肉计",
    mjskurouji_info: "出牌阶段限1次，受到1点伤害，摸2张牌，本回合你造成的火焰伤害+1。",
    mjszhaxiangfenzhou: "诈降焚舟",
    mjszhaxiangfenzhou_info: "限定，将所有牌交给一名其他角色，对其造成1点火焰伤害，然后在其下回合开始时，烧毁这些牌。",

    mjs_wuguotai: "吴国太",
    mjsganluzhaoqin: "甘露招亲",
    mjsganluzhaoqin_info: "每个回合限1次，当一名角色成为杀的目标时，你可以展示其所有手牌，其中每存在1种类型的牌，就令其获得并装备1张装备牌。",
    mjsdaofucangen: "刀斧藏恩",
    mjsdaofucangen_info: "出牌阶段限1次，令一名角色将装备区的所有牌收回手牌。",

    mjs_caoren: "曹仁",
    mjsshimengjushou: "誓盟据守",
    mjsshimengjushou_info: "当你的体力值等于1时，你可以将任意牌当作闪打出。你在回合外每累计打出3张牌时，你回复1点体力。",
    mjsfengfaxingling: "奉法行令",
    mjsfengfaxingling_info: `其他角色在其回合内的非摸牌阶段获得战法牌时，你可以将其中随机1张转化为${get.poptip("mjschi")}；其他角色在非弃牌阶段弃牌时，若其手牌中存在【笞】，你可以对其造成1点伤害。`,
    mjstianrenjiangjun: "天人将军",
    mjstianrenjiangjun_info: "其他角色体力值首次变为1时，你可以失去体力至1点，你每因此失去1点体力，就令其回复1点体力。",

    mjs_xiahoudun: "夏侯惇",
    mjsbashidanjing: "拔矢啖睛",
    mjsbashidanjing_info: `受伤，你可以弃置1张牌，对伤害来源造成1点伤害，然后每局游戏限1次，你可以减1点体力上限，回复1点体力，并可以对目标打出1张具有${get.poptip("rule_mjs_qiangming")}的杀。`,
    mjsqingjianzunshi: "清俭尊师",
    mjsqingjianzunshi_info: "每个回合限1次，当你在回合外获得牌后，你可以将至少1张牌交给1名其他角色，然后添加等量杀至你的手牌，并且你下个出牌阶段的出杀次数+1。",

    mjs_zhanghe: "张郃",
    mjsqiaobianshanzhan: "巧变善战",
    mjsqiaobianshanzhan_info: "出牌阶段各限1次，你可以将1张行动牌或战法牌当作本局游戏未选择过的任意同类型牌打出。",
    mjsyingshibuzhen: "应势布阵",
    mjsyingshibuzhen_info: "受伤/回合结束，你可以摸1张牌，然后将至少1张牌放入“军阵”。出牌阶段限1次，你可以用至少1张牌替换“军阵”中等量的牌。你从“军阵”中获得的牌无法被其他角色响应。",
    mjshuhuhanjiang: "虓虎悍将",
    mjshuhuhanjiang_info: "限定，“军阵”中每有1张牌，你摸1张牌。",

    mjs_caopi: "曹丕",
    mjssichengweiwu: "嗣承魏武",
    mjssichengweiwu_info: "受伤，随机获得伤害来源1张牌，并且获得对你造成伤害的牌。",
    mjsyangexingyin: "燕歌行吟",
    mjsyangexingyin_info: "每个回合限1次，当你选择杀的目标时，你可以弃置目标2张牌，若此杀造成伤害，令其摸2张牌。",
    mjsshanrangshoufeng: "禅让受封",
    mjsshanrangshoufeng_info: "限定，当一名其他角色阵亡时，你可以选择其1个技能，转移给自己。",

    mjs_caozhi: "曹植",
    mjscaigaobadou: "才高八斗",
    mjscaigaobadou_info: "当你打出酒后，翻开堆顶的1张牌，并且你可以立即打出此牌，或者令一名角色获得此牌，然后随机弃置1张牌。",
    mjsqibuqiai: "七步七哀",
    mjsqibuqiai_info: "你可以将♣牌当酒打出。当你在出牌阶段弃牌时，摸1张牌。",

    mjs_weiqing: "卫青",
    mjszhidaohuanglong: "直捣龙城",
    mjszhidaohuanglong_info: `登场，令你对其他角色打出的下1张杀的攻击范围无限，并且具有${get.poptip("rule_mjs_qiangming")}，${get.poptip("rule_mjs_fengjin")}，${get.poptip("rule_mjs_guanchuan")}，伤害+1。`,
    mjscheqihezhan: "车骑合战",
    mjscheqihezhan_info: `游戏开始和回合开始时，若你的装备区没有${get.poptip("mjswugangche")}，添加并装备【武刚车】；其他角色装备坐骑牌时，你可以令你装备区的【武刚车】复制其效果，每个【武刚车】每个坐骑牌限复制1次。当你失去【武刚车】时，重置你的其他技能。`,

    mjs_huoqubing: "霍去病",
    mjsheyijiawei: "何以家为",
    mjsheyijiawei_info: "回合结束时，若你本回合没有造成过伤害，你可以摸3张牌，立即进行一个额外出牌阶段，此阶段结束时，你失去1点体力上限。",
    mjsfenglangjuxu: "封狼居胥",
    mjsfenglangjuxu_info: "当你造成其他角色重伤时，你可以选择其1个技能，转移给你。",
    mjsyinmahanhai: "饮马翰海",
    mjsyinmahanhai_info: "造成伤害后，摸1张牌。",

    mjs_liuche: "刘彻",
    mjstuienling: "推恩令",
    mjstuienling_info: "所有其他角色摸牌阶段改为摸1张牌，然后左右两侧的角色各摸1张牌。",
    mjsgongshoushiyi: "攻守势易",
    mjsgongshoushiyi_info: "每个回合限1次，当你成为其他角色打出牌的目标时，若你的手牌数小于对方，你可以令一名角色添加其随机1张手牌的复制，若你的手牌数大于对方，你可以销毁一名角色2张牌。",
    mjsluntaizuiji: "轮台罪己",
    mjsluntaizuiji_info: "当你第1次失去最后的手牌时，你可以体力上限-1，回复所有体力值，并摸牌至手牌上限。",

    mjs_weizifu: "卫子夫",
    mjspingyanouzhe: "平阳讴者",
    mjspingyanouzhe_info: "当你打出牌后，弃置1张牌；当你失去最后的手牌后，添加你当前回合弃置牌的复制，并且将此技能改为“每回合每种牌限1次，当你打出牌后，令一名其他角色添加1张此牌的复制”。",
    mjsjiafuderuosi: "嘉夫德若斯",
    mjsjiafuderuosi_info: "你每累计令一名其他角色获得4张牌，添加1张休养生息到你的手牌，你的休养生息只对你选择的任意名角色生效。",
    
    mjs_zhangqian: "张骞",
    mjssichouzhilu: "丝绸之路",
    mjssichouzhilu_info: "出牌阶段限1次，令所有角色可以展示任意张手牌，你可以选择与一名展示了手牌的角色交换各自展示的手牌，然后令获得牌少的一方摸2张牌。",
    mjszaokongxiyu: "凿空西域",
    mjszaokongxiyu_info: "当你累计获得其他角色8张牌后，丝绸之路的发动次数+1，然后此技能改为“你每累计获得其他角色8张牌后，装备上限+1，并随机获得1张装备牌”。",

    mjs_dongzhongshu: "董仲舒",
    mjstianrenganying: "天人感应",
    mjstianrenganying_info: "当有角色卜卦后，你添加卜卦牌的1张复制至手牌，然后你可以弃置1张花色不同的手牌，若与卜卦牌相生，则被生者下回合摸牌数+1，若与卜卦牌相克，则被克者下回合摸牌数-1。",
    mjschunqiufanlu: "春秋繁露",
    mjschunqiufanlu_info: "出牌阶段限1次，令一名有手牌的角色卜卦，若结果为阳（♥♣），你令其选择复制1张手牌，若结果为阴（♠♦），你选择销毁其1张手牌。",
    mjsbachubaijia: "罢黜百家",
    mjsbachubaijia_info: "限定，你可以令所有角色手牌中的战法牌转化为任意一张你选择的战法牌。",

    mjs_liguang: "李广",
    mjsfeijiangshelu: "飞将慑虏",
    mjsfeijiangshelu_info: "其他角色出牌阶段造成第2次伤害时，你可以翻开牌堆顶的3张牌，然后对其打出其中所有杀。",
    mjssheshibohu: "射石搏虎",
    mjssheshibohu_info: "你打出的伤害值＞1的杀被闪抵消时，仍然造成伤害，但是伤害-1；受伤，你对目标角色打出的下1张杀的伤害+1。",

    mjs_mibazi: "芈八子",
    mjschushuruqin: "楚姝入秦",
    mjschushuruqin_info: `登场，将势力改为楚。受伤/回合开始时，你可以令自己的体力上限+1，并回复所有体力，然后失去此技能，将势力改为秦，并获得技能${get.poptip("mjsyidingmingfeng")}和${get.poptip("mjsquanyusigui")}。`,
    mjsyidingmingfeng: "易鼎鸣凤",
    mjsyidingmingfeng_info: "出牌阶段限1次，你可以令一名其他角色选择是否将势力改为与你相同，若其拒绝，则其弃置2张手牌。势力与你相同的其他角色以你为目标打出牌时，你可以为此牌增加另一名其他角色为目标。",
    mjsquanyusigui: "权御四贵",
    mjsquanyusigui_info: "出牌阶段，你可以交给一名与你势力相同的其他角色1张牌，当其拥有此牌时，其每回合打出的前2张牌生效2次。",

    mjs_chenajiao: "陈阿娇",
    mjsjinwucangjiao: "金屋藏娇",
    mjsjinwucangjiao_info: "其他角色出牌阶段限1次，其可以交给你至少1张牌，然后你回复等量的体力值，并且可以令其当前阶段出杀次数+1。",
    mjsqianjinmaifu: "千金买赋",
    mjsqianjinmaifu_info: "限定，其他角色回合结束时，你可以将所有手牌交给该角色，然后添加其本回合打出过的所有牌的复制至你的手牌。",
    
    mjs_hanfei: "韩非",
    mjsfabuagui: "法不阿贵",
    mjsfabuagui_info: "出牌阶段限1次，你可以令所有角色上一轮每发动过1次技能，就随机弃置1张牌，若有角色因此失去所有手牌和装备，则失去1点体力。",
    mjsshiyibeibian: "事异备变",
    mjsshiyibeibian_info: `回合结束时，你可以将${get.poptip("mjsfabuagui")}中“随机弃置1张牌”的效果改为“摸1张牌”，或者恢复为“随机弃置1张牌”。`,
    mjsbuqixiugu: "不期修古",
    mjsbuqixiugu_info: "每回合限1次，当你发动其他技能后，可以失去该技能，然后抽取3张武将牌，选择获得其中1名武将的1个技能。",

    mjs_zhongwuyan: "钟无艳",
    mjszijianzhenxi: "自荐枕席",
    mjszijianzhenxi_info: "限定，令一名与你势力相同的其他角色进行一个出牌阶段，此阶段其只能打出你的手牌，之后你与其回合开始时，按其打出这些牌的顺序，分别添加其中1张牌的1个复制至手牌。",
    mjszhiyongdingqi: "智勇定齐",
    mjszhiyongdingqi_info: "出杀，随机添加1张战法牌到手牌，当你打出此战法牌时，你可以令一名其他角色的势力改为与你相同，所有与你势力相同的其他角色获得1张杀。",
    
    mjs_guowei: "郭隗",
    mjsqianjinshigu: "千金市骨",
    mjsqianjinshigu_info: "出牌阶段限1次，你可以将所有手牌增强后洗入牌堆，然后从弃牌堆获得3种不同类型的牌各1张，并增强其中的坐骑牌。",
    mjsqingziweishi: "请自隗始",
    mjsqingziweishi_info: "当其他角色在其回合内打出第1张牌时，你可以将此牌的目标改为你。当有角色打出牌的目标不唯一并且包含你时，从你开始结算。",
    
    mjs_baoyuan: "暴鸢",
    mjsbaizhanwujie: "百战无竭",
    mjsbaizhanwujie_info: "当你受到杀的伤害时，摸2张牌。",
    mjsluzhanfenghui: "路转锋回",
    mjsluzhanfenghui_info: "你无法选择杀的目标。当你打出的杀需要选择目标时，卜卦，根据卜卦牌的点数确定此杀目标。你的杀不计入出杀次数。",
    mjsxuruizhuizhan: "蓄锐追斩",
    mjsxuruizhuizhan_info: "当你对一名角色打出杀后，若此杀未造成伤害，则你打出的下1张杀的伤害+1。",

    mjs_shenbuhai: "申不害",
    mjsyishuyuguo: "以术驭国",
    mjsyishuyuguo_info: "牌堆顶的第1张牌向你明示，当你打出的牌与此牌的花色或点数相同时，摸1张牌。",
    mjschangyuwushi: "藏于无事",
    mjschangyuwushi_info: "每个回合限1次，当你成为其他角色杀或战法牌的目标时，其手牌向你明示直到当前回合结束，你弃置的牌对其他角色暗置。",
    mjsjuncaoqibing: "君操其柄",
    mjsjuncaoqibing_info: `登场，你可以令一名其他角色获得${get.poptip("mjsyishuzhiguo")}。当你或者其阵亡时，未阵亡的角色也失去${get.poptip("mjsyishuyuguo")}、${get.poptip("mjsyishuzhiguo")}。`,
    mjsyishuzhiguo: "依术治国",
    mjsyishuzhiguo_info: "牌堆顶的第1张牌向你明示，当你打出与其相同花色的牌时，摸1张牌。",

    mjs_yanzhaowang: "燕昭王",
    mjsxiuzhujintai: "修筑金台",
    mjsxiuzhujintai_info: "每轮开始时，将场上人数张牌置入黄金台并增强。每名角色出牌阶段限1次，可以将1张手牌或装备置入黄金台并增强，然后卜卦，并获得黄金台中所有与卜卦牌点数相同的牌。你的回合开始时，你可以选择获得黄金台中的1张牌。",
    mjsqiangbingfaqi: "强兵伐齐",
    mjsqiangbingfaqi_info: "你每累计获得3次增强牌时，之后每回合的摸牌数+1，出杀次数+1。",

    mjs_yueyi: "乐毅",
    mjsgujunlianke: "孤军连克",
    mjsgujunlianke_info: "出牌阶段开始时，你可以对自己翻出牌堆顶的5张牌，并可以打出其中任意2种花色各1张牌，然后将剩余的牌放入牌堆底。",
    mjsfeikeshunmin: "废苛顺民",
    mjsfeikeshunmin_info: "每个回合限1次，当你回合外需要打出行动牌时，可以查看牌堆底的2张牌，并可以打出其中1张，然后弃置剩余牌。",
    mjsbaohuiwangshu: "报惠王书",
    mjsbaohuiwangshu_info: "限定，每轮开始时，你可以弃置你的所有手牌，然后选择一名其他角色，将势力改为与其相同，并获得其手牌的复制。",

    mjs_zhaoweihou: "赵威后",
    mjszhiziweibing: "质子为兵",
    mjszhiziweibing_info: "出牌阶段限1次，你可以令一名其他角色获得你任意区域的1张牌，并交给你另外至少1张牌，然后令你受到的下1次伤害-1。当你打出因此获得的牌时，可以弃置另外一名其他角色的1张手牌。",
    mjswuminheyoujun: "无民何有君",
    mjswuminheyoujun_info: "当一名角色跳过摸牌阶段、失去最后的手牌或者有牌被烧毁/销毁/移出时，你可以令其卜卦，若结果不为♣，则其失去1点体力。",
    
    mjs_linxiangru: "蔺相如",
    mjswanbiguizhao: "完璧归赵",
    mjswanbiguizhao_info: "每个回合限1次，当有角色获得其他角色的牌时，你可以令其选择是否将这些牌增强并交给你，若其拒绝，你可以失去1点体力并销毁这些牌。",
    mjsmianchizhihui: "渑池之会",
    mjsmianchizhihui_info: "出牌阶段限1次，选择两名其他角色，令其依次交给对方1张牌，否则你与其各失去1点体力。",
    mjsjiangxianghe: "将相和",
    mjsjiangxianghe_info: "每个回合限1次，当你失去体力后，你可以令一名其他角色交给你任意张牌，然后你回复等量体力，其下回合开始时摸等量张牌。",

    mjs_lianpo: "廉颇",
    mjsfujingqingzui: "负荆请罪",
    mjsfujingqingzui_info: "出牌阶段限1次，你可以获得攻击范围内一名其他角色任意区域内的2张牌，其下个回合开始时，你失去1点体力，然后将因此获得的牌交回。",
    mjsshangnengfanfou: "尚能饭否",
    mjsshangnengfanfou_info: "回合结束时，若你的出杀次数：为0，你可以摸牌至手牌上限，并且之后每回合出杀次数+1；不为0，你摸剩余出杀次数张牌。",

    mjs_mengyao: "孟姚",
    mjsyanruoshaorong: "颜若苕荣",
    mjsyanruoshaorong_info: "每个回合限1次，当其他角色打出的行动牌或战法牌选择除你以外的目标时，你可以令自己也成为此牌的目标。",
    mjsguseerge: "鼓瑟而歌",
    mjsguseerge_info: "每个回合首次打出装备牌时，随机获得1张战法牌；首次打出战法牌时，随机获得1张装备牌。",

    mjs_pingyuanjun: "平原君",
    mjszhanxiaolixin: "斩笑立信",
    mjszhanxiaolixin_info: "出牌阶段限1次，你可以销毁一名其他角色的1张牌，然后令所有与你势力相同的角色依次摸1张牌，并交给你1张牌。",
    mjslilingzhihun: "利令智昏",
    mjslilingzhihun_info: "其他角色受到伤害时，你可以将其势力改为与你相同；其他角色回合开始时，若你在其攻击范围内，你可以令其本回合打出的杀无法选择与你势力相同的其他角色为目标。",

    mjs_suqin: "苏秦",
    mjshezong: "合纵",
    mjshezong_info: "出牌阶段限1次，你可以查看并增强一名角色的1张牌。回合开始时，场上每存在1种势力，本回合此技能的发动次数+1。",
    mjsliuguoxiangyin: "六国相印",
    mjsliuguoxiangyin_info: "你同时拥有2个势力。每回合开始时，你可以将自己的1个势力变为六国的任意1个势力。",
    mjscigu: "刺股",
    mjscigu_info: "出牌阶段，若你没有可以打出的手牌，你可以失去1点体力，摸2张牌。然后令此技能失去的体力数和摸牌数+1，直到当前回合结束。",

    mjs_ximenbao: "西门豹",
    mjsyinzhangshierqu: "引漳十二渠",
    mjsyinzhangshierqu_info: "你可以将1张♠牌给一名此阶段未选择过的其他角色，并获得其任意区域的1张牌，然后若你手牌中没有与此花色相同花色的牌，你获得1张♠牌。",
    mjshouminboku: "厚民薄库",
    mjshouminboku_info: "你可以弃置2张相同花色的牌，令任意名角色各获得1张♠牌。",
    mjsrubaohebo: "入报河伯",
    mjsrubaohebo_info: "限定，你将场上和弃牌堆中所有的♠牌洗回牌堆。",

    mjs_xinlingjun: "信陵君",
    mjsshikesanqian: "食客三千",
    mjsshikesanqian_info: "每轮开始时，你查看其他所有角色各1张手牌。当你查看过的牌被打出后，你获得此牌。",
    mjsdaofucijiang: "盗符刺将",
    mjsdaofucijiang_info: `出杀，你对有${get.poptip("mjs_debuff_liuxue_faq")}状态的角色伤害+1。当你获得其他角色的装备牌时，可以令一名其他角色增加1层${get.poptip("mjs_debuff_liuxue_faq")}。`,
    mjsweisishi: "魏死士",
    mjsweisishi_info: `回合结束时，你可以查看牌堆顶的3张牌并标记其中1张牌，然后将所有牌按顺序放回牌堆顶。当此牌被其他角色打出时，你可以令其增加1层${get.poptip("mjs_debuff_liuxue_faq")}并销毁此牌；当此牌被弃置后，你获得此牌。`,

    mjs_ruji: "如姬",
    mjsqiefujiuzhao: "窃符救赵",
    mjsqiefujiuzhao_info: `出牌阶段开始时，你可以查看一名其他角色的随机3张手牌(不足则全看)，并可以用你的手牌交换这些牌或将这些牌补至最多3张，然后根据这些牌的${get.poptip("mjsqiefujiuzhao_faq")}触发对应效果。`,
    mjsqiefujiuzhao_faq: "组合",
    mjsqiefujiuzhao_faq_info: `组合规则：<br>花色相同、点数连续：添加${get.poptip("mjsweihufu")}，并交给一名角色<br>花色相同：添加1张同花色的牌至手牌<br>点数连续：添加1张${get.poptip("mjsduoliangjieying")}至手牌<br>3张点数相同：摸3张牌<br>2张点数相同：摸2张牌`,
    mjsxianhuanshibao: "衔环誓报",
    mjsxianhuanshibao_info: `当有角色${get.poptip("rule_mjs_zhongshang")}时，若其曾对你造成过伤害，你可以令伤害来源增加1点体力上限，然后回复1点体力。`,

    mjs_zhengxiu: "郑袖",
    mjsyanxiugongchan: "掩袖工谗",
    mjsyanxiugongchan_info: "当其他角色打出或每弃置1张获得过的你的牌时，你可以立即对其打出牌堆中的第1张杀，若此杀造成伤害，你摸2张牌。",
    mjsyinduquanshi: "因妒劝释",
    mjsyinduquanshi_info: "出牌阶段限1次，你可以交给一名其他角色至少1张牌，然后令一名角色回复等量体力，并且其下回合出杀次数+1。",

    mjs_songyu: "宋玉",
    mjsqugaohegua: "曲高和寡",
    mjsqugaohegua_info: "当你以其他角色为目标打出牌后，若此牌没有被其他角色抵消或响应，则你可以选择任意名其他角色，令其依次随机弃置1张牌。",
    mjsjiubian: "九辩",
    mjsjiubian_info: "所有角色每累计弃置9张牌，你可以令一名角色随机增强2张牌。",

    mjs_chunshenjun: "春申君",
    mjsyihuajiemu: "移花接木",
    mjsyihuajiemu_info: "每个回合限1次，其他角色主动打出战法牌时，你可以将其转化为任意战法牌（每种战法牌每轮限1次），并由该角色继续执行转化后牌的效果，然后你获得1张转化后牌的复制。",
    mjswuwangzhizai: "无妄之灾",
    mjswuwangzhizai_info: "目标包含你的战法牌生效2次。",

    mjs_tiandan: "田单",
    mjshuoniuzhen: "火牛阵",
    mjshuoniuzhen_info: "你可以消耗1次出杀次数，随机添加1张装备牌至手牌。回合结束时，你可以将所有装备牌当作火杀对一名其他角色打出并消耗所有装备上限，每因此造成1点伤害，你的装备上限+1。",
    mjsjieqiujiuren: "解裘救人",
    mjsjieqiujiuren_info: `其他角色${get.poptip("rule_mjs_zhongshang")}时，你可以交给其1张装备牌，并令其装备，然后其回复1点体力，若其因此脱离重伤状态，你的装备上限+1，并摸牌至装备上限。`,

    mjs_mengchangjun: "孟尝君",
    mjsfenquanshiyi: "焚券市义",
    mjsfenquanshiyi_info: "回合开始时，你可以收回其他角色获得过的你的牌，或者令这些角色在你受到伤害后交给你1张牌，直到你的下个回合开始。",
    mjsjiaotusanku: "狡兔三窟",
    mjsjiaotusanku_info: "出牌阶段限3次，你可以交给一名其他角色1张牌，当其手牌中有因此获得的牌时，你可以令其代替你成为杀或战法牌的目标，然后随机增强其中1张牌。",
    mjsjiminggoudao: "鸡鸣狗盗",
    mjsjiminggoudao_info: "出牌阶段限1次，你可以选择一名其他角色，其可以将任意1张手牌：当作先拔头筹打出，并且你可以选择其中1张牌获得；或当作顺手牵羊打出，并且将获得的牌交给你。",
    
    mjs_zhangyi: "张仪",
    mjslianheng: "连横",
    mjslianheng_info: "出牌阶段限1次，将你的势力变为一名其他角色的势力，或者令一名其他角色的势力变为你的势力，然后若你的势力角色数量全场最多，所有同势力的角色手牌上限+1，体力上限+1。",
    mjszhongkoushuojin: "众口铄金",
    mjszhongkoushuojin_info: "与你势力相同的所有角色，每累计打出3张相同名称的牌时，你可以选择销毁一名其他角色任意区域的1张牌。",
    mjszhezhu: "折竹",
    mjszhezhu_info: "出牌阶段限1次，你可以用1张手牌刻写其他角色本轮发动过的1个技能。之后你可以弃置此牌，获得此技能，直到你的下个回合开始。",

    mjs_fanju: "范雎",
    mjswuguibaixiang: "五跪拜相",
    mjswuguibaixiang_info: "其他角色出牌阶段限1次，其可以交给你1张牌，然后你可以随机添加1张战法牌到其手牌；其他角色每累计令你获得牌或回复体力5次后，你的手牌上限+1，并且将势力改为与其相同。",
    mjsyuanjiaojingong: "远交近攻",
    mjsyuanjiaojingong_info: "出牌阶段限1次，交给一名不同势力的其他角色2张牌，然后对与你距离为1以内的另一名其他势力的角色造成1点伤害。",
    mjsqingyunzhishang: "青云直上",
    mjsqingyunzhishang_info: "回合结束时，若你的手牌数不是全场最多，你之后每个回合的摸牌数+1。",

    mjs_fusu: "扶苏",
    mjsshanyoufusu: "山有扶苏",
    mjsshanyoufusu_info: "你可以消耗1个出杀次数或1点体力，令任意名角色摸1张牌，且因此获得牌的其他角色打出下一张♣牌时，回复1点体力。",
    mjsxianwenyumin: "贤闻于民",
    mjsxianwenyumin_info: "阵亡，令击杀你的角色受到的所有伤害+1，直到游戏结束。",

    mjs_lisi: "李斯",
    mjsfanshumingfa: "燔书明法",
    mjsfanshumingfa_info: "出牌阶段限1次，你可以弃置1张牌，令一名其他角色手牌上限-1。当你弃牌后，直到你的下回合开始，其他角色打出与你弃牌同名的牌时，你可以令其随机弃置1张牌。你每因此弃置其他角色3张牌，此技能下个出牌阶段的发动次数+1。",
    mjsjianzhizhuke: "谏止逐客",
    mjsjianzhizhuke_info: "当你打出牌后，直到你的下回合开始，你可以获得其他角色弃置的与你打出过的牌同名的牌。",

    mjs_ziying: "子婴",
    mjsmodaiqinwang: "末代秦王",
    mjsmodaiqinwang_info: "你的初始手牌×2。在你的回合开始时，你弃置手牌至手牌上限。当你的手牌被弃置时，你可以将其交给任意一名其他角色。",
    mjstuimiaozhujian: "推庙诛奸",
    mjstuimiaozhujian_info: "出牌阶段限1次，你可以减少1点装备上限，摸2张牌，手牌上限+1；当你的装备上限首次为0时，你可以弃置所有杀，并选择一名其他角色，对其造成等量伤害。",

    mjs_zhanghan: "章邯",
    mjsshetushoubing: "赦徒授兵",
    mjsshetushoubing_info: "你可以消耗1次出杀次数，将弃牌堆中的所有杀洗回牌堆，然后摸牌直到摸到的牌不是杀。",
    mjsxianmei: "衔枚",
    mjsxianmei_info: "若你在出牌阶段没有打出杀，你跳过弃牌阶段，并且你之后每个出牌阶段的出杀次数+1。",

    mjs_mengyi: "蒙毅",
    mjsneimoufazhi: "内谋法治",
    mjsneimoufazhi_info: `${get.poptip("rule_mjs_yingzhan")}，你随机弃置目标1张牌，令此技能可以弃牌的数量+1，直到你的下个回合开始。`,

    mjs_mengtian: "蒙恬",
    mjszhuchenshoufan: "筑城守藩",
    mjszhuchenshoufan_info: `${get.poptip("rule_mjs_yingzhan")}，你摸1张牌，若你未受到此杀伤害，令此技能可以摸牌的数量+1，直到你的下个回合开始。`,
    mjszhongxin: "忠信",
    mjszhongxin_info: "每个回合限1次，当一名其他角色成为其他角色杀的目标时，你可以将此杀的目标改为你。",

    mjs_dongzhuo: "董卓",
    mjsqitianfeizhu: "欺天废主",
    mjsqitianfeizhu_info: "出牌阶段限1次，你可以令两名其他角色交换位置，然后选择其中一名角色手牌上限-1。",
    mjscangbaoumeiwu: "藏宝郿坞",
    mjscangbaoumeiwu_info: "回合结束时，将牌堆顶的3张牌放入郿坞；郿坞中的牌在你的回合内视为你的手牌。",

    mjs_caiwenji: "蔡文姬",
    mjshujiashibapai: "胡笳十八拍",
    mjshujiashibapai_info: "每个回合限1次，当有角色受伤或者阵亡后，你可以摸1张牌，然后弃置伤害来源任意区域的1张牌。",
    mjsbeifenlichou: "悲愤离愁",
    mjsbeifenlichou_info: "受伤，封禁伤害来源直到当前回合结束。",

    mjs_huatuo: "华佗",
    mjsguaguliaodu: "刮骨疗毒",
    mjsguaguliaodu_info: "每个回合限1次，当一名有手牌的角色受伤后，你可以将其所有手牌移出游戏，直到其下个回合开始，然后令其回复1点体力。",
    mjsqingnangmiaoshou: "青囊妙手",
    mjsqingnangmiaoshou_info: "当你打出♣的牌后，可以令一名角色回复1点体力，若其体力值已满，则改为体力上限+1并回复1点体力。",

    mjs_zuoci: "左慈",
    mjszhibeixicao: "掷杯戏曹",
    mjszhibeixicao_info: "你打出的以其他角色为唯一目标的牌可以额外选择另一名其他角色为目标，然后你指定其中一个目标为虚假目标。",
    mjsdunjiatianshu: "遁甲天书",
    mjsdunjiatianshu_info: "回合开始前，从随机三名武将中选择一名，直到你的下回合开始，获得其技能。",
    mjsfeishengtaixu: "飞升太虚",
    mjsfeishengtaixu_info: "游戏开始和回合开始时，卜卦2次，根据点数依次确定你当前的体力值和手牌上限。",

    mjs_diaochan: "貂蝉",
    mjsgeliansongmu: "隔帘送目",
    mjsgeliansongmu_info: `出牌阶段限1次，你可以令一名男性角色对你选择的另一名男性角色打出1张具有${get.poptip("rule_mjs_qiangming")}的杀，否则令其随机弃置1张牌并失去1点体力。`,
    mjsbiyuezhizi: "闭月之姿",
    mjsbiyuezhizi_info: "回合结束时，摸2张牌，然后可以打出其中1张牌。",

    mjs_yuanshao: "袁绍",
    mjssishisangong: "四世三公",
    mjssishisangong_info: "初始手牌+4，手牌上限+3。",
    mjsbaiwanxiongbing: "百万雄兵",
    mjsbaiwanxiongbing_info: "出牌阶段开始时，若你的手牌数全场最多，将手牌中的战法牌转化为万箭齐发。",
    mjsfujinfengliu: "幅巾风流",
    mjsfujinfengliu_info: "每打出3张装备牌，手牌上限+1。",

    mjs_lvbu: "吕布",
    mjswushuangfeijiang: "无双飞将",
    mjswushuangfeijiang_info: `你将获得的战法牌转化为2张杀。你的杀具有${get.poptip("rule_mjs_qiangming")}。`,
    mjslangziyexin: "狼子野心",
    mjslangziyexin_info: "杀伤，你可以令攻击范围内的另外一名其他角色交给你2张牌，否则你可以对其打出1张杀。",
    mjsyuanmensheji: "辕门射戟",
    mjsyuanmensheji_info: "限定，其他角色成为杀的目标时，你可以打出1张杀，令其无效。",

    mjs_chensheng: "陈胜",
    mjsgouhuohuming: "篝火狐鸣",
    mjsgouhuohuming_info: `向牌堆中洗入7张${get.poptip("mjshuming")}。`,
    mjsningyouzhonghu: "宁有种乎",
    mjsningyouzhonghu_info: "限定，令所有角色摸牌至与全场手牌最多的角色相同。",
    mjsjieganerqi: "揭竿而起",
    mjsjieganerqi_info: `限定，当你的体力值变为1时，你可以摸3张牌，获得技能${get.poptip("mjsfawudao")}，然后立即进行回合。`,
    mjsfawudao: "伐无道",
    mjsfawudao_info: "你对本局游戏累计造成伤害最多的角色造成的所有伤害+1。",

    mjs_zhoubo: "周勃",
    mjsxiaozouwange: "箫奏挽歌",
    mjsxiaozouwange_info: "当其他角色阵亡后，你可以摸2张牌，然后立即进行1个出牌阶段。",
    mjsxuepingzhulv: "削平诸吕",
    mjsxuepingzhulv_info: "你的回合限1次，摸牌至与全场手牌最多的角色相同，本回合下一次造成的伤害+1，出牌阶段结束时，弃置因此技能获得的牌。",

    mjs_fankuai: "樊哙",
    mjsxiandeng: "先登",
    mjsxiandeng_info: "当有角色的体力值变为1时，你可以对其打出1张杀，若目标因此阵亡，你摸3张牌。",
    mjspaitazhiru: "排闼直入",
    mjspaitazhiru_info: "回合开始时，你可以查看攻击范围内一名有手牌的其他角色的手牌，并打出其中一张，若其手牌均无法打出，你可以对其造成1点伤害。",

    mjs_chenping: "陈平",
    mjsliuchuqiji: "六出奇计",
    mjsliuchuqiji_info: `出牌阶段开始时/${get.poptip("rule_mjs_yingzhan")}，你可以将1张未选择过的${get.poptip("mjsliuchuqiji_faq")}添加到手牌，直到每张专属战法牌都选择后重置此技能。`,
    mjsliuchuqiji_faq: "专属战法牌",
    mjsliuchuqiji_faq_info: "专属战法牌包括：<br><li>捐金反间：将此牌交给一名其他角色，令其受到你选择的另外一名其他角色造成的1点伤害<br><li>恶草近使：令一名其他角色随机弃置2张闪<br><li>夜解荥阳：令一名其他角色随机弃置2张杀<br><li>蹑足稳心：令一名其他角色交给你选择的另一名其他角色1张手牌或装备牌，然后回复1点体力<br><li>游云梦泽：选择一名其他角色，使另一名其他角色随机从其手牌或装备牌中获得2张牌<br><li>白登解围：令一名其他角色直到其下个回合开始，无法被选择为杀的目标",
    mjsguaxiweimen: "挂席为门",
    mjsguaxiweimen_info: "当你的手牌数全场最低时，你无法成为其他角色战法牌的目标，并且其他角色打出战法牌后，你可以获得一张此牌的复制。",

    mjs_hanxin: "韩信",
    mjsshimianmaifu: "十面埋伏",
    mjsshimianmaifu_info: "你可以将任意张牌设为埋伏，当其他角色打出牌时，你可以弃置1张同名的埋伏牌，然后摸1张牌并可以立即对其打出1张杀。",
    mjsbeishuiyizhan: "背水一战",
    mjsbeishuiyizhan_info: "你可以将所有手牌当作杀打出，此杀的伤害+1，且造成伤害后，你收回这些手牌。若此杀没有造成伤害，则你受到的下一次伤害+1。",
    mjsdengtanbaijiang: "登坛拜将",
    mjsdengtanbaijiang_info: "出牌阶段限1次，你可以将1张牌当作多多益善打出。",

    mjs_liubang: "刘邦",
    mjszhansheqiyi: "斩蛇起义",
    mjszhansheqiyi_info: "限定，你选择1张除杀之外的手牌，销毁游戏中所有同名牌，接下来本局游戏你每次弃牌后，可以令一名其他角色摸2张牌。",
    mjsdafengge: "大风歌",
    mjsdafengge_info: "每个回合限1次，当你获得点数为5的牌后，你可以将其弃置，立即重新洗牌，随机弃置其他角色各1张牌，然后可以令一名其他角色摸牌至手牌上限。",
    mjsyuefasanzhang: "约法三章",
    mjsyuefasanzhang_info: "出牌阶段限1次，你可以弃置1张手牌，选择一名其他角色，若其在上一轮，击杀过其他角色，则体力上限-1，造成过伤害，则受到1点伤害，获得过其他角色的牌，随机销毁其1张牌。",

    mjs_lvzhi: "吕雉",
    mjslinchaochengzhi: "临朝称制",
    mjslinchaochengzhi_info: "每个回合开始前，你可以选择1个花色，令所有角色在打出此花色的牌后摸1张牌或者随机销毁1张牌。",
    mjszhulvweiwang: "诸吕为王",
    mjszhulvweiwang_info: "限定，你选择至少三名角色（不足则全部），令其随机平分所有本局游戏被销毁的牌。",

    mjs_xiaohe: "萧何",
    mjsjuxianweijiang: "举贤为将",
    mjsjuxianweijiang_info: "回合结束时，你可以交给一名其他角色至少1张牌，然后令其立即进行一个只有出牌阶段的回合；在此阶段内，当其打出行动牌后，其摸1张牌。",
    mjsjizhaoyouzhu: "计召诱诛",
    mjsjizhaoyouzhu_info: `限定，其他角色的出牌阶段结束时，若其在此阶段内打出的牌＞3张，你可以令另外一名其他角色对其打出手牌中的所有杀，直到目标${get.poptip("rule_mjs_zhongshang")}。`,

    mjs_zhangliang: "张良",
    mjsbolangzhuiqin: "博浪椎秦",
    mjsbolangzhuiqin_info: "你可以将手牌中的1张武器牌装备给一名其他角色，然后其可以对你选择的其攻击范围内的另一名其他角色打出1张杀。",
    mjsyunchouweiwo: "运筹帷幄",
    mjsyunchouweiwo_info: "你的杀只能当做任意战法牌打出，并且每个战法牌每个回合限1次。你在回合外需要打出杀时，其他角色可以替你打出。",
    mjsyiqiaoshoushu: "圯桥授书",
    mjsyiqiaoshoushu_info: `所有角色累计打出15张战法牌后，将${get.poptip("mjsyiqiaoshoushu_faq")}添加到你的手牌和你可以打出的战法牌种类中。`,
    mjsyiqiaoshoushu_faq: "太公六韬",
    mjsyiqiaoshoushu_faq_info: "太公六韬包括：<br><li>文韬：令一名角色摸牌至手牌上限<br><li>武韬：查看一名有牌的其他角色的手牌，若其中缺少某种类型的牌，你可以令一名角色随机获得对应类型的各1张牌<br><li>龙韬：令一名其他角色随机获得并装备1张装备牌，并且下回合的出杀次数+1<br><li>虎韬：本回合你打出的下一张战法牌生效2次<br><li>豹韬：令两名角色交换座位<br><li>犬韬：本回合你打出的下一张行动牌生效2次",

    mjs_xiangliang: "项梁",
    mjsjiangmenlichu: "将门立楚",
    mjsjiangmenlichu_info: `限定，令一名其他角色获得技能${get.poptip("mjschuwang")}。`,
    mjschuwang: "楚王",
    mjschuwang_info: "当你对目标打出杀后，满足攻击范围条件的其他角色也可以相同目标打出1张杀",
    mjsxianfazhiren: "先发制人",
    mjsxianfazhiren_info: "杀伤，你可以获得目标角色的任意区域的1张牌，并增加1点手牌上限。其他角色回合开始时，你可以对其打出1张杀。",

    mjs_jibu: "季布",
    mjsyinuoqianjin: "一诺千金",
    mjsyinuoqianjin_info: "每名其他角色限1次，其可以将所有手牌交给你，你可以拒绝，若你接受，本局游戏无法对其造成伤害，并且代替其成为杀的目标。",
    mjsweiqirenxia: "为气任侠",
    mjsweiqirenxia_info: "每个回合限1次，当有角色受到伤害后，若其体力值或手牌数全场最低，你可以摸1张牌，然后可以对伤害来源打出1张杀。",

    mjs_fanzeng: "范增",
    mjswangqinbichu: "亡秦必楚",
    mjswangqinbichu_info: "每轮开始时，你可以选择一名其他角色，令其体力上限+1，手牌上限+1，当其每个回合首次打出行动牌后，你获得1张战法牌，然后可以立即打出此牌。",
    mjshongmenyan: "鸿门宴",
    mjshongmenyan_info: "限定，你可以摸存活人数张牌并选择一名其他角色，然后你依次交给所有其他角色1张牌，并令其对你选择的角色立即打出此牌，否则其随机弃置1张牌。",

    mjs_longqie: "龙且",
    mjszhongyongshiwu: "忠勇恃武",
    mjszhongyongshiwu_info: "其他角色打出杀后，若目标也在你的攻击范围内，你可以失去1点体力，摸2张牌，然后可以对相同目标打出1张杀。",
    mjsanyingzhulei: "安营筑垒",
    mjsanyingzhulei_info: "回合结束时，你可以弃置所有手牌，并增加等量体力上限，然后回复1点体力；回合开始时，你的体力上限减少至体力值，每减少1点，摸2张牌。",

    mjs_xiangyu: "项羽",
    mjspofuchenzhou: "破釜沉舟",
    mjspofuchenzhou_info: "限定，销毁你所有的手牌和防具牌，然后摸牌至手牌上限，接下来本局游戏你造成的所有伤害+1，出牌阶段开始时，每损失1点体力，出杀次数+1。",
    mjsbawang: "霸王",
    mjsbawang_info: "当你进行阵前对决时，将阵前对决的效果改为对目标造成1点伤害；你每造成3次伤害，添加1张阵前对决到你的手牌。",

    mjs_yingbu: "英布",
    mjsgongguanzhuhou: "功冠诸侯",
    mjsgongguanzhuhou_info: "每轮结束时，若你在本轮造成的伤害最高，你的体力上限+1，之后每个出牌阶段的出杀次数+1。",
    mjsdaxiguowang: "大喜过望",
    mjsdaxiguowang_info: "每轮开始时，你将手牌摸至全场最多。",

    mjs_yuji: "虞姬",
    mjsmeiren: "美人",
    mjsmeiren_info: "登场，你选择一名男性角色，其替你承担所有伤害；当其受到致命伤害时，改为你失去等量的体力值，然后令其回复1点体力，并添加1张阵前对决到其手牌。",
    mjsbawangbieji: "霸王别姬",
    mjsbawangbieji_info: "阵亡，你令一名男性角色立即进行回合。",

    mjs_zhonglimo: "钟离眜",
    mjsfeilianshi: "飞连矢",
    mjsfeilianshi_info: "你的杀可以额外选择1个目标。然后若此杀造成的总伤害＞1，你摸2张牌，若目标未受到此杀伤害，你随机弃置其1张装备牌或手牌。",
    mjsgugengzhichen: "骨鲠之臣",
    mjsgugengzhichen_info: "阵亡，你可以选择废除或重置一名其他角色的1个技能。",

    mjs_xunyu: "荀彧",
    mjserhujingshi: "二虎竞食",
    mjserhujingshi_info: "限定，你令一名其他角色可以对另一名其他角色打出1张杀，若造成伤害，随机获得对方1张牌，然后对方重复此过程，直到其中一方不打出杀。",
    mjsquhutunlang: "驱虎吞狼",
    mjsquhutunlang_info: `限定，你令两名其他角色进行阵前对决；然后选择另外一名其他角色，其可以对阵前对决中受伤的角色打出所有杀，直到目标${get.poptip("rule_mjs_zhongshang")}。`,
    mjsxunlingliuxiang: "荀令留香",
    mjsxunlingliuxiang_info: "受伤，你可以令一名角色摸2张牌，然后手牌上限+1。",

    mjs_caocao: "曹操",
    mjstianbufuwo: "天不负我",
    mjstianbufuwo_info: "受伤，获得对你造成伤害的牌，并且可以立即打出其中1张牌。",
    mjsxietianyiling: "挟天以令",
    mjsxietianyiling_info: "出牌阶段限1次，翻开牌堆顶1张牌，然后令一名角色打出此牌，若其无法打出，你获得此牌并对其造成1点伤害。",
    mjstianxiaguixin: "天下归心",
    mjstianxiaguixin_info: "当其他角色阵亡时，你获得其所有牌。",

    mjs_dianwei: "典韦",
    mjsguzhielai: "古之恶来",
    mjsguzhielai_info: "受伤，你造成的下一次伤害+1。",
    mjszhuhuguojian: "逐虎过涧",
    mjszhuhuguojian_info: "你可以弃置1张武器牌，与一名其他角色交换位置，然后对距离1以内的一名其他角色造成1点伤害。",

    mjs_guojia: "郭嘉",
    mjsshishengshibai: "十胜十败",
    mjsshishengshibai_info: "受伤，你可以摸2张牌，然后你可以交给一名其他角色至少1张手牌，并令其下个出牌阶段的出杀次数+1。",
    mjstianduyingcai: "天妒奇才",
    mjstianduyingcai_info: "回合开始时，卜卦，若结果不为♣，则受到1点伤害；若结果为♣，你获得卜卦牌。",
    mjsyicepingliao: "遗策平辽",
    mjsyicepingliao_info: "阵亡，你可以选择一名其他角色，令其对距离1以内的所有其他角色各造成1点伤害。",

    mjs_simayi: "司马懿",
    mjslangguyingshi: "狼顾鹰视",
    mjslangguyingshi_info: "回合开始时，每有一个没有杀的其他角色，你的手牌上限+1，体力上限+1；每有1个没有闪的其他角色，你本回合出牌阶段的出杀次数+1。",
    mjsren: "忍",
    mjsren_info: "限定，本局游戏所有角色每受到过2点伤害，你就可以摸1张牌。",
    
    mjs_xuchu: "许褚",
    mjshuchi: "虎痴",
    mjshuchi_info: "受伤，摸1张牌，并将其转化为阵前对决，并且你可以立即对伤害来源打出此牌。",
    mjsxiejiahanzhan: "卸甲酣战",
    mjsxiejiahanzhan_info: "限定，你弃置所有装备牌，每弃置1张装备牌，摸2张牌，出杀次数+1。",

    mjs_zhangliao: "张辽",
    mjsxiaoyaozhiti: "逍遥止啼",
    mjsxiaoyaozhiti_info: "回合开始时，你可以获得一名其他角色的1张手牌，然后令其本回合无法打出识破。",
    mjsbailangchihui: "白狼持麾",
    mjsbailangchihui_info: "回合开始时，你可以标记一名角色，直到你的下回合开始，对其打出杀的角色摸1张牌。",

    mjs_zhenfu: "甄宓",
    mjspianruojinghong: "翩若惊鸿",
    mjspianruojinghong_info: "每个回合限1次，你的♠牌可以当作识破打出。你每累计打出3张♠牌，可以令最多两名角色各回复1点体力。",
    mjsluoshenfu: "洛神赋",
    mjsluoshenfu_info: "当你获得♠牌后，额外再摸等量牌；你的♠牌不计入手牌上限。",

    mjs_huangzhong: "黄忠",
    mjsbaodaoweilao: "宝刀不老",
    mjsbaodaoweilao_info: "回合开始时，随机获得1张武器牌，若牌堆中没有武器牌，改为获得1张杀。",
    mjsbaibuchuanyang: "百步穿杨",
    mjsbaibuchuanyang_info: `每个回合限1次，出杀，若你与目标距离大于1，则此杀你将获得的战法牌转化为2张杀。你的杀具有${get.poptip("rule_mjs_qiangming")}。，否则此杀伤害+1。`,
    mjsjiaobingzhiji: "骄兵之计",
    mjsjiaobingzhiji_info: "其他角色回合结束时，若其手牌数小于你，你可以立即对其打出1张杀或者下回合的出杀次数+1。",

    mjs_liubei: "刘备",
    mjsweixianweide: "惟贤惟德",
    mjsweixianweide_info: "你可以交给其他角色任意张牌，令其下个回合首次出杀后摸1张牌，每因此交出1张牌，你回复1点体力。",
    mjssangumaolu: "三顾茅庐",
    mjssangumaolu_info: "当你每累计主动交给一名其他角色3张牌后，你可以令其手牌上限+1或者下回合出杀次数+1。",
    mjsxiemindujiang: "携民渡江",
    mjsxiemindujiang_info: "其他角色可以将其在弃牌阶段弃置的牌交给你，这些牌无法被打出或主动弃置，直到下一轮结束。",

    mjs_machao: "马超",
    mjsliangzhoutieji: "凉州铁骑",
    mjsliangzhoutieji_info: "你的杀具有封禁；回合开始时，随机获得1张坐骑牌，若牌堆中没有坐骑牌，改为获得1张杀。",
    mjsjinshizi: "锦狮子",
    mjsjinshizi_info: "当你打出装备牌时，你可以与一名其他角色交换位置；然后距离1以内每存在一名被封禁的角色，你的出杀次数+1。",

    mjs_sunshangxiang: "孙尚香",
    mjsxiaojiniangniang: "枭姬娘娘",
    mjsxiaojiniangniang_info: "装备上限+1；当你的装备区获得或失去装备牌时，摸1张牌。",
    mjsdaojianqingyuan: "刀剑情缘",
    mjsdaojianqingyuan_info: "出牌阶段限1次，你可以弃置1张牌，令你和一名男性角色回复1点体力，若体力已满，随机获得1张装备牌。",

    mjs_zhangfei: "张飞",
    mjswanrendi: "万人敌",
    mjswanrendi_info: "回合开始时，添加随机花色的杀到手牌上限。杀伤，本回合出杀次数+1。",
    mjsheduandangyang: "喝断当阳",
    mjsheduandangyang_info: "应战，随机弃置目标1张牌，若此杀没有对你造成伤害，令目标本回合无法再打出牌。",
    mjsshijiuruming: "嗜酒如命",
    mjsshijiuruming_info: "你可以将杀当作酒打出。",

    mjs_zhaoyun: "赵云",
    mjsqiangchurulong: "枪出如龙",
    mjsqiangchurulong_info: "出杀，摸1张牌；你的闪可以当作杀打出。",
    mjshunshenshidan: "浑身是胆",
    mjshunshenshidan_info: "闪避，你可以立即打出1张杀；你的杀可以当作闪打出。",
    mjsqijinqichu: "七进七出",
    mjsqijinqichu_info: "你每累计打出3张杀或闪后，你的手牌上限+1，每个出牌阶段的出杀次数+1。",

    mjs_zhugeliang: "诸葛亮",
    mjsqimendunjia: "奇门遁甲",
    mjsqimendunjia_info: `回合开始时，你为每名角色翻开1张牌堆顶的牌，然后你可以选择一名角色执行其对应的${get.poptip("mjsqimendunjia_faq")}，然后将其他牌按原顺序放回牌堆。`,
    mjsqimendunjia_faq: "奇门效果",
    mjsqimendunjia_faq_info: "奇门效果包括：<br>点数1-开门：摸2张牌<br>点数2-惊门：随机弃置2张手牌<br>点数3-景门：获得1张战法牌<br>点数4-伤门：受到1点无来源的雷电伤害<br>点数5-杜门：随机弃置1张装备<br>点数6-休门：手牌上限+1<br>点数7-生门：回复1点体力<br>点数8-死门：失去1点体力",
    mjsjinnangmiaoji: "锦囊妙计",
    mjsjinnangmiaoji_info: `出牌阶段开始/结束时，选择添加1张${get.poptip("mjsjinnangmiaoji_faq")}到一名角色的手牌。`,
    mjsjinnangmiaoji_faq: "专属战法牌",
    mjsjinnangmiaoji_faq_info: "专属战法牌包括：<br><li>舌战群儒：本回合每打出1张战法牌，摸1张牌<br><li>草船借箭：抵消即将受到的伤害，并获得即将对你造成伤害的牌<br><li>七星祭风：直到你的下个回合开始，所有火焰伤害+1<br><li>智取华容：标记1个角色，直到你的下回合开始，当其受到伤害后，其他角色若攻击范围内包含该角色，可以立即对其打出1张杀<br><li>七擒七纵：在你即将造成伤害时打出，防止此伤害，改为获得目标2张牌<br><li>空城计：选择一名角色，直到你的下个回合开始，当其没有手牌时，其无法成为手牌和技能的目标<br><li>上方用火：选择1个目标，卜卦，若结果不是♠，对其造成1点火焰伤害<br><li>借尸还魂：可以选择一名阵亡角色，选择获得其1个技能，直到你的下个回合开始",

    mjs_guanyu: "关羽",
    mjswanjunqushou: "万军取首",
    mjswanjunqushou_info: "你的杀攻击范围无限，且目标手牌中每有1张杀，就获得伤害+1。",
    mjswushengyijue: "武圣义绝",
    mjswushengyijue_info: "你可以将任意牌当做杀打出。",
    mjsshuiyanqijun: "水淹七军",
    mjsshuiyanqijun_info: "每个回合限1次，当你打出的杀被闪抵消后，你随机获得1张♠牌。你可以弃置3张♠牌，令一名其他角色弃置所有牌并受到1点伤害，然后你失去此技能。",

    mjs_daqiao: "大乔",
    mjsqiushuiyiren: "秋水伊人",
    mjsqiushuiyiren_info: `${get.poptip("rule_mjs_yingzhan")}，你可以摸1张牌，然后可以弃置1张♠牌，将此杀的目标转移给另一名其他角色。`,
    mjsjunshengbieli: "君生别离",
    mjsjunshengbieli_info: "登场，选择一名其他角色，当其受伤或弃牌后，你可以弃置另外一名其他角色任意区域的1张牌。",

    mjs_ganning: "甘宁",
    mjsbairenyexi: "百人夜袭",
    mjsbairenyexi_info: "当你获得♠牌后，可以弃置一名其他角色的1张牌。",
    mjsjinfanyouxia: "锦帆游侠",
    mjsjinfanyouxia_info: "出牌阶段限1次，你可以将所有手牌的花色变为♠，并洗回牌堆，然后摸等量的牌。",

    mjs_lusu: "鲁肃",
    mjszhiqunxiangzeng: "指囷相赠",
    mjszhiqunxiangzeng_info: "回合开始时，将牌堆顶的4张牌放入粮仓；其他角色回合开始时，你可以令其随机获得粮仓中一半的牌；粮仓中每有1张牌，你的手牌上限",
    mjsjiezhoudimeng: "借州缔盟",
    mjsjiezhoudimeng_info: `出牌阶段限1次，你令两名其他角色进入${get.poptip("mjsjiezhoudimeng_faq")}状态，直到你的下个回合开始。`,
    mjsjiezhoudimeng_faq: "结盟",
    mjsjiezhoudimeng_faq_info: "结盟：结盟状态的两个角色在出牌阶段可以打出本回合开始时对方的手牌。",

    mjs_luxun: "陆逊",
    mjshuopolianying: "火破连营",
    mjshuopolianying_info: "出牌阶段限1次，你可以交给一名其他角色1张牌，然后烧毁其任意区域内与此牌花色相同的所有牌，若烧毁的牌≥3张，对其造成1点火焰伤害。",
    mjsjieyigongwu: "解衣共舞",
    mjsjieyigongwu_info: "当你打出手牌后，若你的手牌数全场最低，摸1张牌。",

    mjs_sunce: "孙策",
    mjshujuyingyang: "虎踞鹰扬",
    mjshujuyingyang_info: "你每损失1点体力，摸牌阶段就额外摸1张牌。",
    mjsxiaobawang: "小霸王",
    mjsxiaobawang_info: "出牌阶段开始/结束时，如果你的手牌数为全场最多，你可以选择一名其他角色进行阵前对决。",

    mjs_sunquan: "孙权",
    mjschengmashehu: "乘马射虎",
    mjschengmashehu_info: "每个回合限1次，其他角色回合内获得4张牌时，你摸1张牌，并且你可以立即打出1张杀。",
    mjsquanxuelishi: "劝学励士",
    mjsquanxuelishi_info: "出牌阶段限1次，你可以弃置至少1张牌然后摸等量牌；其他角色出牌阶段限1次，其可以交给你至少1张手牌，然后你可以交还其任意张手牌。",

    mjs_xiaoqiao: "小乔",
    mjsbingdifurong: "并蒂芙蓉",
    mjsbingdifurong_info: "登场，你选择一名其他角色，每个回合限2次，当其获得牌后，你摸1张牌。",
    mjstaozhiyaoyao: "桃之夭夭",
    mjstaozhiyaoyao_info: `当你获得♣牌后，将其转化为${get.poptip("mjstaohua")}。`,

    mjs_zhouyu: "周瑜",
    mjsxiongziyingfa: "雄姿英发",
    mjsxiongziyingfa_info: "回合开始时，摸2张牌。",
    mjsfanjianchuhuan: "反间除患",
    mjsfanjianchuhuan_info: "每个回合限1次，当其他角色选择你为战法牌的目标时，你可以令此牌无效并回到打出者手牌，若其本回合再次打出此牌，随机弃置2张牌，并进入连环状态。",
    mjsfanjianchuhuan_debuff: "反间",
    mjshuoshaochibi: "火烧赤壁",
    mjshuoshaochibi_info: "出牌阶段开始时，最多卜卦2次，若其中有1次点数为5，你可以弃置所有♥手牌，对一名角色造成等量的火焰伤害，然后失去此技能。",

    mjs_zhangjiao: "张角",
    mjstaipingyaoshu: "太平要术",
    mjstaipingyaoshu_info: `向牌堆中洗入8张${get.poptip("mjsfushui")}，当所有符水都离开牌堆后，你失去技能${get.poptip("mjstaipingdao")}，获得技能${get.poptip("mjshufenghuanyu")}，然后将弃牌堆和8张${get.poptip("mjsfushui")}洗入牌堆。`,
    mjstaipingdao: "太平道",
    mjstaipingdao_info: `其他角色每回合限1次，可以交给你2张牌，然后你令其获得1张${get.poptip("mjsfushui")}。`,
    mjshufenghuanyu: "呼风唤雨",
    mjshufenghuanyu_info: "回合开始时，翻开牌堆顶的3张牌，出牌阶段，你可以打出这3张牌；回合结束时，若这3张牌都没有被打出，你可以对一名角色造成2点雷电伤害。",
};
export default translates;
