//部分巾帼武将台词补充@快乐小雏田，感谢
export default {
  "#ext:名将杀/audio/skill/mjsyueyanxili1": "何须繁辞，一理足矣。",
  "#ext:名将杀/audio/skill/mjsmingjiaoyuedi1": "不须驰骋才智，且享此刻安宁。",
  "#ext:名将杀/audio/skill/mjsmingjiaoyuedi2": "名教自有乐处，何必向外驰求？",
  "#ext:名将杀/audio/skill/mjsmingjiaoyuedi3": "名教之中，自有乐地。",
  "#ext:名将杀/audio/skill/mjsmingjiaoyuedi4": "既见天地，方得一隅。",
  "#ext:名将杀/audio/skill/mjsbeigongsheying1": "疑者病，悟者痊。",
  "#ext:名将杀/audio/skill/mjsbeigongsheying2": "但心安无疚，何惧弓影之疑？",
  "#ext:名将杀/audio/die/mjs_yueguang:die": "何故……陷此樊笼。",
  "#ext:名将杀/audio/die/mjs_yueguang2:die": "主怀猜忌，何以释之？",
  
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi1": "我之风韵，岂是尔等可以触碰。",
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi2": "凡夫俗子，还不退下！",
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi3": "这世间，可有与我同者乎？",
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi4": "何人，能与我比肩？",
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi5": "天之道，损有余而补不足也。",
  "#ext:名将杀/audio/skill/mjsfengshenxiuyi6": "闻君有雅物，可否借来一用？",
  "#ext:名将杀/audio/skill/mjszhuyuzaice1": "与吾并坐，可感自惭形秽否？",
  "#ext:名将杀/audio/skill/mjszhuyuzaice2": "吾为珠玉，尔等皆不过萤火。",
  "#ext:名将杀/audio/skill/mjssimengchengji1": "经月不得，遂以成疾哉。",
  "#ext:名将杀/audio/skill/mjssimengchengji2": "神形所不接而梦，岂是想邪？",
  "#ext:名将杀/audio/die/mjs_weijie:die": "别看，别看了……",
  "#ext:名将杀/audio/die/mjs_weijie2:die": "这乱世，终究还是配不上我。",
  
  "#ext:名将杀/audio/skill/mjstaishixinlv1": "不战而一天下，不备而守太平。",
  "#ext:名将杀/audio/skill/mjstaishixinlv2": "民不见兵戈，库不藏锋镝。",
  "#ext:名将杀/audio/skill/mjstaishixinlv3": "铸剑为犁，泽被千秋。",
  "#ext:名将杀/audio/skill/mjstaishixinlv4": "弓矢不张，骐骥且休。",
  "#ext:名将杀/audio/skill/mjsrongnadangzheng1": "良药利病，谠言无伤。",
  "#ext:名将杀/audio/skill/mjsrongnadangzheng2": "怒火将焚忠骨，容德可开盛世。",
  "#ext:名将杀/audio/skill/mjsrongnadangzheng3": "岂因一时之怒，塞忠良之门？",
  "#ext:名将杀/audio/skill/mjsrongnadangzheng4": "毁誉无惊，天子之度。",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong1": "昔时壮志，今朝何存？",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong2": "承平日久，武备竟弛。",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong3": "尔等聒噪书生，焉知帝王之乐？",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong4": "朕已一统寰宇，何须逆耳之言？",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong5": "削其枝叶，以固根本。",
  "#ext:名将杀/audio/skill/mjsshanshinanzhong6": "拆其梁柱，广我殿宇。",
  "#ext:名将杀/audio/die/mjs_simayan:die": "八王操戈，罪在朕躬……",
  "#ext:名将杀/audio/die/mjs_simayan2:die": "可恨痴儿悍妇，毁我社稷！",
  
  "#ext:名将杀/audio/skill/mjsshierdilv1": "制十二笛律，定黄钟之正。",
  "#ext:名将杀/audio/skill/mjsshierdilv2": "协律吕之和，张清浊之制。",
  "#ext:名将杀/audio/skill/mjsshierdilv3": "一笛一声，十二律成。",
  "#ext:名将杀/audio/skill/mjsshierdilv4": "八音克谐，雅颂不失。",
  "#ext:名将杀/audio/skill/mjssibufenlei1": "纲举目张，群书有归。",
  "#ext:名将杀/audio/skill/mjssibufenlei2": "四部既立，万卷可寻。",
  "#ext:名将杀/audio/skill/mjsxingguanqingxin1": "省官不如省事，省事不如清心。",
  "#ext:名将杀/audio/skill/mjsxingguanqingxin2": "若欲天下清平，根本在于清心。",
  "#ext:名将杀/audio/die/mjs_xunxu:die": "慎密一生，却有此失……",
  "#ext:名将杀/audio/die/mjs_xunxu2:die": "事可成，身难全……",
  
  "#ext:名将杀/audio/skill/mjsshuangjianhualong1": "龙泉澄凝，渊跃之象。",
  "#ext:名将杀/audio/skill/mjsshuangjianhualong2": "太阿在悬，威道自彰。",
  "#ext:名将杀/audio/skill/mjsshuangjianhualong3": "双锋既会，自当无往不利。",
  "#ext:名将杀/audio/skill/mjsshuangjianhualong4": "今御双龙，蚍蜉何足为虑？",
  "#ext:名将杀/audio/skill/mjsbowuzhi1": "山川位象，吉凶有征。",
  "#ext:名将杀/audio/skill/mjsbowuzhi2": "一物既出，万物可推。",
  "#ext:名将杀/audio/skill/mjsbowuzhi3": "次序既正，物理乃明。",
  "#ext:名将杀/audio/skill/mjsbowuzhi4": "正其先后，择善而取。",
  "#ext:名将杀/audio/skill/mjslanaitongfen1": "吾以碧血，焚此朽坏斧钺。",
  "#ext:名将杀/audio/skill/mjslanaitongfen2": "死当以魂火燎原，令兰艾共烬。",
  "#ext:名将杀/audio/die/mjs_zhanghua:die": "臣不爱死，惧王室之难，祸不可测也。",
  "#ext:名将杀/audio/die/mjs_zhanghua2:die": "吾中心如丹，岂可为逆臣鹰犬？",
  
  "#ext:名将杀/audio/skill/mjsyuanqishangqing1": "正气存焉，日增月益。",
  "#ext:名将杀/audio/skill/mjsyuanqishangqing2": "道义在躬，元气自盈。",
  "#ext:名将杀/audio/skill/mjsyuanqishangqing3": "以此清正，泽及同袍。",
  "#ext:名将杀/audio/skill/mjsyuanqishangqing4": "施德于人，共襄正道。",
  "#ext:名将杀/audio/skill/mjsjinzhuzhechi1": "近朱者赤，近墨者黑。",
  "#ext:名将杀/audio/skill/mjsjinzhuzhechi2": "声和则响清，形正则影正。",
  "#ext:名将杀/audio/skill/mjszhengzaiqusi1": "私不去则公道亡。",
  "#ext:名将杀/audio/skill/mjszhengzaiqusi2": "私心灭，公道生。",
  "#ext:名将杀/audio/die/mjs_fuxuan:die": "吾守性以终，又何憾焉？",
  "#ext:名将杀/audio/die/mjs_fuxuan2:die": "台阁生尘，恨未尽扫……",
  
  "#ext:名将杀/audio/skill/mjsqingqiuhuandai1": "轻裘缓带，真当我不通战阵乎？",
  "#ext:名将杀/audio/skill/mjsqingqiuhuandai2": "外披儒衫，内怀宝甲，方为儒将。",
  "#ext:名将杀/audio/skill/mjsqingqiuhuandai3": "将者，在韬略，在攻心。",
  "#ext:名将杀/audio/skill/mjsqingqiuhuandai4": "为将者，何须身披重甲？",
  "#ext:名将杀/audio/skill/mjsdeguansihai1": "兵者，何须以诡道求之？",
  "#ext:名将杀/audio/skill/mjsdeguansihai2": "以德怀远，方可不战而屈人之兵。",
  "#ext:名将杀/audio/skill/mjsdeguansihai3": "吾之良药，汝自可服之。",
  "#ext:名将杀/audio/skill/mjsdeguansihai4": "你我赤诚互战，岂不快哉！",
  "#ext:名将杀/audio/skill/mjsdeguansihai5": "汝之美酒，吾当痛饮。",
  "#ext:名将杀/audio/skill/mjsdeguansihai6": "堂堂正正，方为大丈夫也！",
  "#ext:名将杀/audio/skill/mjsqianmouyuanji1": "天下大势，当步步为营。",
  "#ext:名将杀/audio/skill/mjsqianmouyuanji2": "一退再退，看你能坚持到几时。",
  "#ext:名将杀/audio/die/mjs_yanghu:die": "恨不能亲眼得见，江山一统……",
  "#ext:名将杀/audio/die/mjs_yanghu2:die": "灭吴方略，终不能亲手践之！", 
  
  "#ext:名将杀/audio/skill/mjsduwuku1": "查遗补缺，稳中求胜。",
  "#ext:名将杀/audio/skill/mjsduwuku2": "世间万物，皆在我手中。",
  "#ext:名将杀/audio/skill/mjsduwuku3": "吾之武库，应有尽有。",
  "#ext:名将杀/audio/skill/mjsduwuku4": "取我武库中的宝物来。",
  "#ext:名将杀/audio/skill/mjsshirupozhu1": "竹木之性，安则静，危则动。",
  "#ext:名将杀/audio/skill/mjsshirupozhu2": "今兵威已振，成破竹之势也。",
  "#ext:名将杀/audio/skill/mjsshirupozhu3": "任势者，其战人也，如转木石。",
  "#ext:名将杀/audio/skill/mjsshirupozhu4": "数节之后，皆迎刃而解。",
  "#ext:名将杀/audio/skill/mjslinggucunxun1": "海陆变迁，而吾名，不变。",
  "#ext:名将杀/audio/skill/mjslinggucunxun2": "吾名，当为千万年所知。",
  "#ext:名将杀/audio/skill/mjslinggucunxun3": "焉知此后不为陵谷乎？",
  "#ext:名将杀/audio/skill/mjslinggucunxun4": "不随陵谷变，应只有高名。",
  "#ext:名将杀/audio/die/mjs_duyu:die": "万不可将此事，记录于册……",
  "#ext:名将杀/audio/die/mjs_duyu2:die": "古不合葬，明于终始之理。",
     
  "#ext:名将杀/audio/skill/mjsyuanqingqimi1": "诗缘情而绮靡，赋体物而浏亮。",
  "#ext:名将杀/audio/skill/mjsyuanqingqimi2": "碑披文以相质，诔缠绵而凄怆。",
  "#ext:名将杀/audio/skill/mjslucairuhai1": "收百世之阙文，采千载之遗韵。",
  "#ext:名将杀/audio/skill/mjslucairuhai2": "观古今于须臾，抚四海于一瞬。",
  "#ext:名将杀/audio/skill/mjshuatingheli1": "血沃征衣，智反清明。",
   "#ext:名将杀/audio/skill/mjshuatingheli2": "操斧伐柯，取则不远。",
   "#ext:名将杀/audio/skill/mjshuatingheli3": "法度在我，君受其衡。",
   "#ext:名将杀/audio/skill/mjshuatingheli4": "效颦者拙，自难相较。",
  "#ext:名将杀/audio/die/mjs_luji:die": "华亭鹤唳，不可复闻矣……",
  "#ext:名将杀/audio/die/mjs_luji2:die": "同是流离客，何苦较短长？",
  
  "#ext:名将杀/audio/skill/mjsliuwangchujun1": "今日纳士招贤，来日共清寰宇。", 
  "#ext:名将杀/audio/skill/mjsliuwangchujun2": "遗镞亦堪用，败粟可充仓。",
  "#ext:名将杀/audio/skill/mjsliuwangchujun3": "布衣草芥，皆铸铁甲寒光。",
  "#ext:名将杀/audio/skill/mjsliuwangchujun4": "散卒归心，亦成勤王之师。",
  "#ext:名将杀/audio/skill/mjsshouliweiwang1": "苍生为骨，民心作血。",
  "#ext:名将杀/audio/skill/mjsshouliweiwang2": "既承社稷重担，岂忍黎民倒悬？",
  "#ext:名将杀/audio/skill/mjsfenshenjiumin1": "聚土成岳，汇溪成川。",
  "#ext:名将杀/audio/skill/mjsfenshenjiumin2": "血肉可焚，黎民不可弃。",
  "#ext:名将杀/audio/die/mjs_weijiu:die": "宁可断头而死，不可屈膝而生！",
  "#ext:名将杀/audio/die/mjs_weijiu2:die": "焦土之下，终有新生……",
    
  "#ext:名将杀/audio/skill/mjszuozhuguanju1": "依山起堰，顺陇开渠。",
  "#ext:名将杀/audio/skill/mjszuozhuguanju2": "凿地作脉，引水为筋。",
  "#ext:名将杀/audio/skill/mjspiqinzhiji1": "泾水滔滔，可疲千里之国。",
  "#ext:名将杀/audio/skill/mjspiqinzhiji2": "纵有金石之仓，岂经涓滴消磨？",
  "#ext:名将杀/audio/skill/mjsguanzhongwoye1": "开渠方寸，遗泽千里。",
  "#ext:名将杀/audio/skill/mjsguanzhongwoye2": "稷黍离离，岁无凶年。",
  "#ext:名将杀/audio/die/mjs_zhengguo:die": "渠未竭，民得溉，足矣。",
  "#ext:名将杀/audio/die/mjs_zhengguo2:die": "江涛无尽，吾道不休。",
    
  "#ext:名将杀/audio/skill/mjsqiaoyanjiehuo1": "莫嫌俳语俗，笑谈有玄机。",
  "#ext:名将杀/audio/skill/mjsqiaoyanjiehuo2": "一折博君笑，三折明得失。",
  "#ext:名将杀/audio/skill/mjstouhu1": "用志不分，乃凝于神。",
  "#ext:名将杀/audio/skill/mjstouhu2": "宁搏彩头，不守成物。",
  "#ext:名将杀/audio/skill/mjstouhu3": "投壶之矢，看似坚利，却通圆融。",
  "#ext:名将杀/audio/skill/mjstouhu4": "投壶之法，不赖蛮力，而需巧字。",
  "#ext:名将杀/audio/die/mjs_guosheren:die": "俳优谢幕，换君一笑尔！",
  "#ext:名将杀/audio/die/mjs_guosheren2:die": "哈哈哈哈，此番竟也失手了。",
  
  "#ext:名将杀/audio/skill/mjsbowangnaxian1": "第勿为过，何畏小人构陷！",
  "#ext:名将杀/audio/skill/mjsbowangnaxian2": "君子行正，何须防闲？",
  "#ext:名将杀/audio/skill/mjsbowangnaxian3": "宫闱裁决之事，储君本分而已。",
  "#ext:名将杀/audio/skill/mjsbowangnaxian4": "分忧于父，决事于宫，太子之责也。",
  "#ext:名将杀/audio/skill/mjsjufenchengli1": "父上存亡未知，今唯起兵诛贼！",
  "#ext:名将杀/audio/skill/mjsjufenchengli2": "吾大汉太子也！逆贼欺我太甚！",
  "#ext:名将杀/audio/die/mjs_liuju:die": "今之情势，孩儿无以自明……",
  "#ext:名将杀/audio/die/mjs_liuju2:die": "人言我不类父，诚如此乎……",
   
  "#ext:名将杀/audio/skill/mjsjianghudaochi1": "既有所托，解何敢不为！",
  "#ext:名将杀/audio/skill/mjsjianghudaochi2": "若不护你周全，我有何颜面立于天地之间？",
  "#ext:名将杀/audio/skill/mjsjianghudaochi3": "竖子安敢辱我！",
  "#ext:名将杀/audio/skill/mjsjianghudaochi4": "此仇不报非君子也……",
  "#ext:名将杀/audio/skill/mjsquanxingzhouli1": " 诸君与我共诛此贼！",
  "#ext:名将杀/audio/skill/mjsquanxingzhouli2": "啊哈哈哈哈！你也有今日！",
  "#ext:名将杀/audio/skill/mjsquanxingzhouli3": "刀剑无眼，生死由命！",
  "#ext:名将杀/audio/skill/mjsquanxingzhouli4": "要怪就怪他命数不济！",
  "#ext:名将杀/audio/skill/mjsweixiazhezhong1": "郭解行事，但求问心无愧！",
  "#ext:名将杀/audio/skill/mjsweixiazhezhong2": "我虽身死，侠道犹存！",
  "#ext:名将杀/audio/die/mjs_guojie:die": "郭解行事，但求问心无愧！",
  "#ext:名将杀/audio/die/mjs_guojie2:die": "我虽身死，侠道犹存！",
  
  "#ext:名将杀/audio/skill/mjsxiancetuien1": "斧钺不染血，社稷已归心。",
  "#ext:名将杀/audio/skill/mjsxiancetuien2": "分封子弟，以广圣泽。",
  "#ext:名将杀/audio/skill/mjsxiancetuien3": "天子推恩，如月照万川。",
  "#ext:名将杀/audio/skill/mjsxiancetuien4": "金帛不费，而诸侯自弱。",
  "#ext:名将杀/audio/skill/mjstuhaomaoling1": "散山东积粟，实长安仓廪。",
  "#ext:名将杀/audio/skill/mjstuhaomaoling2": "君有累世之资，正当拱卫王都。",
  "#ext:名将杀/audio/skill/mjstuhaomaoling3": "诸卿家资丰厚，当为天下表率。",
  "#ext:名将杀/audio/skill/mjstuhaomaoling4": "昔年所蓄，今归原主。",
  "#ext:名将杀/audio/skill/mjszhuchengshuofang1": "一砖一石，皆作华夏藩篱。",
  "#ext:名将杀/audio/skill/mjszhuchengshuofang2": "此非穷塞，实乃天赐金汤。",
  "#ext:名将杀/audio/skill/mjszhuchengshuofang3": "十里坚城，更胜十万甲兵。",
  "#ext:名将杀/audio/skill/mjszhuchengshuofang4": "坚城之筑，功在当代，利在千秋。",
  "#ext:名将杀/audio/die/mjs_zhufuyan:die": "人心搏杀，本就险过沙场……",
  "#ext:名将杀/audio/die/mjs_zhufuyan2:die": "丈夫生不五鼎食，死即五鼎烹耳。",

  "#ext:名将杀/audio/skill/mjsxialuxiangfeng1": "狭路相逢，且观汝杀机几重？",
  "#ext:名将杀/audio/skill/mjsxialuxiangfeng2": "两鼠斗于穴中，将勇者胜。",
  "#ext:名将杀/audio/skill/mjsfenggongrufa1": "法理昭昭，清点汝藏。",
  "#ext:名将杀/audio/skill/mjsfenggongrufa2": "逾制之物，当收归国法。",
  "#ext:名将杀/audio/die/mjs_zhaoshe:die": "赵之山河，托付后来人。",
  "#ext:名将杀/audio/die/mjs_zhaoshe2:die": "勇可破阵，法难医国。",
  
  "#ext:名将杀/audio/skill/mjsqiangnuzhimo1": "强弩之极，矢不能穿鲁缟。",
  "#ext:名将杀/audio/skill/mjsqiangnuzhimo2": "冲风之末，力不能飘鸿毛。",
  "#ext:名将杀/audio/skill/ mjsqiangnuzhimo3": "兵不获利，莫如安之。",
  "#ext:名将杀/audio/skill/mjsqiangnuzhimo4": "击之不便，不如和亲。",
  "#ext:名将杀/audio/skill/mjssihuifuran1": "福兮祸兮，死灰独不复燃兮？",
  "#ext:名将杀/audio/skill/mjssihuifuran2": "夫盛之有衰，犹朝之必暮也。",
  "#ext:名将杀/audio/die/mjs_hananguo:die": "将屯亡多，臣甚自愧。",
  "#ext:名将杀/audio/die/mjs_hananguo2:die": "望得归京，竟益东徙……",
  
  "#ext:名将杀/audio/skill/mjsqiru1": "大丈夫西游，出关何须用复传！",
  "#ext:名将杀/audio/skill/mjsqiru2": "既已入长安，但求为大汉建功。",
  "#ext:名将杀/audio/skill/mjsqingying1": "今愿受长缨，必羁越王归！",
  "#ext:名将杀/audio/skill/mjsqingying2": "愿往说越王，举国迁内属。",
  "#ext:名将杀/audio/skill/mjsqingying3": "新改其俗，一用汉法。",
  "#ext:名将杀/audio/skill/mjsqingying4": "天下为一，万里同风。",
  "#ext:名将杀/audio/die/mjs_zhongjun:die": "臣有负天子之命……",
  "#ext:名将杀/audio/die/mjs_zhongjun2:die": "南越内归日，吾目弗及也……",
  
  "#ext:名将杀/audio/skill/mjsyanmenzongmu1": "戍边养士。蓄势待发。",
  "#ext:名将杀/audio/skill/mjsyanmenzongmu2": "伤创愈骨，烽烟励志。",
  "#ext:名将杀/audio/skill/mjsyanmenzongmu3": "雁门铁骑，随我出兵。",
  "#ext:名将杀/audio/skill/mjsyanmenzongmu4": "屯田养锐久，剑出雁门寒。",
  "#ext:名将杀/audio/skill/mjsjiniuxiangshi1": "锋镝所向，皆成齑粉。",
  "#ext:名将杀/audio/skill/mjsjiniuxiangshi2": "慨然之气，破阵摧锋。",
  "#ext:名将杀/audio/die/mjs_limu:die": "长城犹在，臣魂永守。",
  "#ext:名将杀/audio/die/mjs_limu2:die": "未竟戍边志，此身恨难平。",
  
    "#ext:名将杀/audio/skill/mjsqinianrenjia1": "区区小伤，何足为碍。",
    "#ext:名将杀/audio/skill/mjsqinianrenjia2": "垂暮之躯，正堪为薪。",
    "#ext:名将杀/audio/skill/mjsqinianrenjia3": "一息尚存，便是千钧在握。",
    "#ext:名将杀/audio/skill/mjsqinianrenjia4": "残躯化薪，亦可沸腾江海。",
   "#ext:名将杀/audio/skill/mjswuguozongshi1": "五国之师，今皆在我！",
   "#ext:名将杀/audio/skill/mjswuguozongshi2": "四海兵锋，合成其势。",
  "#ext:名将杀/audio/die/mjs_pangnuan:die": "可惜纵横骨血，皆作青山残照。",
  "#ext:名将杀/audio/die/mjs_pangnuan2:die": "这天下，交由少年人守了……",
  
  "#ext:名将杀/audio/skill/mjsqiguantouyi1": "智计若不能济民，不过朽墨枯简耳。",
  "#ext:名将杀/audio/skill/mjsqiguantouyi2": "吾即挂印东向，不奉独夫一人。",
  "#ext:名将杀/audio/skill/mjscezhimingyi1": "借尔刀兵，以破顽敌。",
  "#ext:名将杀/audio/skill/mjscezhimingyi2": "若无决断之勇，焉掌破敌之刃？",
  "#ext:名将杀/audio/skill/mjscezhimingyi3": "直道而行，何须伪诈？",
  "#ext:名将杀/audio/skill/mjscezhimingyi4": "天下诡诈多矣，不及堂堂之师。",
  "#ext:名将杀/audio/die/mjs_chengong:die": "兖州风起了，谁还记得当年……",
  "#ext:名将杀/audio/die/mjs_chengong2:die": "智计虽百，难补天倾！",
  
  "#ext:名将杀/audio/skill/mjssuanwuyice1": "用兵之道，先胜后战。",
  "#ext:名将杀/audio/skill/mjssuanwuyice2": "量敌论将，举无遗策。",
  "#ext:名将杀/audio/skill/mjswenheluanwu1": "善弈者谋势，不善弈者谋子。",
  "#ext:名将杀/audio/skill/mjswenheluanwu2": "谋定而动，不若乘势而行。",
  "#ext:名将杀/audio/skill/mjsdushi1": "执子者痴，观局者狂。",
  "#ext:名将杀/audio/skill/mjsdushi2": "局中血海滔天，唯吾独步于外。",
  "#ext:名将杀/audio/die/mjs_jiaxu:die": "此局虽了，然天下，何曾太平……",
  "#ext:名将杀/audio/die/mjs_jiaxu2:die": "七十局，竟失此一着。",
  
  "#ext:名将杀/audio/skill/mjssusishoucheng1": "保宗庙安宁，去兵革之患。",
  "#ext:名将杀/audio/skill/mjssusishoucheng2": "承先帝遗烈，守蜀地晏安。",
  "#ext:名将杀/audio/skill/mjssusishoucheng3": "不劳案牍，而天下治。",
  "#ext:名将杀/audio/skill/mjssusishoucheng4": "朕但垂衣拱手，为守成之主。",
  "#ext:名将杀/audio/skill/mjslebusishu1": "此间乐，不思蜀也。",
  "#ext:名将杀/audio/skill/mjslebusishu2": "此间之乐，在于无忧。",
  "#ext:名将杀/audio/die/mjs_liushan:die": "天丧我也！",
  "#ext:名将杀/audio/die/mjs_liushan2:die": "鹧鸪声声，犹似锦官城……",
  
  "#ext:名将杀/audio/skill/mjsshujunkeji1": "外自韬隐，内察形便。",
  "#ext:名将杀/audio/skill/mjsshujunkeji2": "能克己者，方能克敌。",
  "#ext:名将杀/audio/skill/mjsduzhifenxue1": "士别三日，当刮目相待。",
  "#ext:名将杀/audio/skill/mjsduzhifenxue2": "吴下阿蒙，今非昔比。",
  "#ext:名将杀/audio/skill/mjsbaiyidujiang1": "白衣渡江处，荆州换旗时。",
  "#ext:名将杀/audio/skill/mjsbaiyidujiang2": "兵者诡道，当奏奇功。",
  "#ext:名将杀/audio/die/mjs_lvmeng:die": "大丈夫战死沙场，幸也！",
  "#ext:名将杀/audio/die/mjs_lvmeng2:die": "成败兴亡，终似一场东风……",
  
  "#ext:名将杀/audio/skill/mjsziwuqimou1": "奇兵出于子午，长安可图也。",
  "#ext:名将杀/audio/skill/mjsziwuqimou2": "直出午谷，长安必惊。",
  "#ext:名将杀/audio/skill/mjsfangunizhan1": "汝等雕虫小技，皆成我之势。",
  "#ext:名将杀/audio/skill/mjsfangunizhan2": "以彼之道，十倍还之。",
  "#ext:名将杀/audio/skill/mjsshuiganshawo1": "兵行险着，方可制胜。",
  "#ext:名将杀/audio/skill/mjsshuiganshawo2": "循规蹈矩，岂是勇者所为？",
  "#ext:名将杀/audio/die/mjs_weiyan:die": "竟亡于小人之手……",
  "#ext:名将杀/audio/die/mjs_weiyan2:die": "谁敢杀我？",
  
  "#ext:名将杀/audio/skill/mjsruxupojun1": "且看某裂浪摧锋，为吴主开江。",
  "#ext:名将杀/audio/skill/mjsruxupojun2": "濡须水赤，方显肝胆。",
  "#ext:名将杀/audio/skill/mjsbailiyicheng1": "疑城江雾里，谈笑退千军。",
  "#ext:名将杀/audio/skill/mjsbailiyicheng2": "有吾在此，休教片帆过境。",
  "#ext:名将杀/audio/die/mjs_xusheng:die": "大厦倾矣，唯望后来者……",
  "#ext:名将杀/audio/die/mjs_xusheng2:die": "酣战至此，吾可瞑目，哈哈哈哈！",
  
  "#ext:名将杀/audio/skill/mjszhujianyishi1": "好利者多奸，好事者难养。",
  "#ext:名将杀/audio/skill/mjszhujianyishi2": "好事之人，宠过必乱，不可疏于戒备。",
  "#ext:名将杀/audio/skill/mjsqianchongjiexia1": "崇俭抑华，怀素守虚。",
  "#ext:名将杀/audio/skill/mjsqianchongjiexia2": "言尊典礼，行合雅风。",
  "#ext:名将杀/audio/skill/mjsgongzhifangji1": "居安享贵，素业亦不能忘。",
  "#ext:名将杀/audio/skill/mjsgongzhifangji2": "躬执纺绩，始知民庶艰难。",
  "#ext:名将杀/audio/die/mjs_wangyuanji:die": "薄殓简葬，不必奢靡厚饰。",
  "#ext:名将杀/audio/die/mjs_wangyuanji2:die": "荣华皆是外物，安世勿忘……",

  "#ext:名将杀/audio/skill/mjsqianguliuyin1": "清音初起，万象更新。",
  "#ext:名将杀/audio/skill/mjsqianguliuyin2": "宫商既起，天地同听。",
  "#ext:名将杀/audio/skill/mjsqianguliuyin3": "移宫换羽，悲欢由心。",
  "#ext:名将杀/audio/skill/mjsqianguliuyin4": "清商变徵须臾间，能使天地同悲欢。",
  "#ext:名将杀/audio/skill/mjsyuyinraoliang1": "身虽灭兮音不绝，余响千年绕栋梁。",
  "#ext:名将杀/audio/skill/mjsyuyinraoliang2": "清歌不绝传后世，此心长留天地间。",
  "#ext:名将杀/audio/die/mjs_hane:die": "长歌已尽，此恨绵绵。",
  "#ext:名将杀/audio/die/mjs_hane2:die": "雍门一曲成绝响，唯余天籁在九霄。",
  
  "#ext:名将杀/audio/skill/mjsyebenxiangru1": "长街月隐，且随君去。",
  "#ext:名将杀/audio/skill/mjsyebenxiangru2": "绿绮弦鸣，当随君子。",
  "#ext:名将杀/audio/skill/mjsyebenxiangru3": "弃锦缎华服，换君心相知。",
  "#ext:名将杀/audio/skill/mjsyebenxiangru4": "抛却千金锁，换得天地宽。",
  "#ext:名将杀/audio/skill/mjsdanglumaijiu1": "妙策佐佳酿，可醉月下仙。",
  "#ext:名将杀/audio/skill/mjsdanglumaijiu2": "君赠琼瑶，妾报芳醪。",
  "#ext:名将杀/audio/skill/mjsbaitouyin1": "唯将心头雪，剪作《白头吟》。",
  "#ext:名将杀/audio/skill/mjsbaitouyin2": "绿绮尚能鸣，覆水已难收。",
  "#ext:名将杀/audio/die/mjs_zhuowenjun:die": "锦水汤汤，与君长诀。",
  "#ext:名将杀/audio/die/mjs_zhuowenjun2:die": "白雪易污，皎月难全。",

  "#ext:名将杀/audio/skill/mjsfengqiuhuang1": "凤飞翱翔兮，四海求凰。",
  "#ext:名将杀/audio/skill/mjsfengqiuhuang2": "凤兮凤兮归故乡，遨游四海求其凰。",
  "#ext:名将杀/audio/skill/mjsfengqiuhuang3": "愿化双飞翼，天涯共知音。",
  "#ext:名将杀/audio/skill/mjsfengqiuhuang4": "赋骨琴音，可安天下，可动芳心。",
  "#ext:名将杀/audio/skill/mjszizhedubi1": "能屈伸者，方为天下利器。",
  "#ext:名将杀/audio/skill/mjszizhedubi2": "市井之中，自有大千世界。",
  "#ext:名将杀/audio/skill/mjsquanbaifengyi1": "铺锦三千丈，藏锋一辞间。",
  "#ext:名将杀/audio/skill/mjsquanbaifengyi2": "剑锋所至，文脉随之。",
  "#ext:名将杀/audio/die/mjs_simaxiangru:die": "人间功名，不过佐酒一笺。",
  "#ext:名将杀/audio/die/mjs_simaxiangru2:die": "可惜长卷未展，弦断难续……",

  "#ext:名将杀/audio/skill/mjswoquancanggou1": "握璇玑者，能窥天命。",
  "#ext:名将杀/audio/skill/mjswoquancanggou2": "藏玉钩者，可改乾坤。",
  "#ext:名将杀/audio/skill/mjswoquancanggou3": "玉钩为契，请入此局。",
  "#ext:名将杀/audio/skill/mjswoquancanggou4": "欲得其果，先种其因。",
  "#ext:名将杀/audio/skill/mjswoquancanggou5": "结琴瑟之好，共百年之惠。",
  "#ext:名将杀/audio/skill/mjswoquancanggou6": "君添一石，妾盈一斛，此谓分辉。",
  "#ext:名将杀/audio/skill/mjsyaomumen1": "玉钩既碎，天命方启。",
  "#ext:名将杀/audio/skill/mjsyaomumen2": "去母留子，天道何仁？",
  "#ext:名将杀/audio/die/mjs_zhaojieyu:die": "掖庭棠花开落，未央宫阙长明。",
  "#ext:名将杀/audio/die/mjs_zhaojieyu2:die": "好一个，云阳仙去……",

  "#ext:名将杀/audio/enter/mjs_liufuling": "社稷之器，当观八方。诸卿方略，皆为朕用。",
  "#ext:名将杀/audio/enter/mjs_liufuling2": "江山之重，在朕与卿。博采众长，以固国本。",
  "#ext:名将杀/audio/skill/mjsyantiezhiyi1": "利不可尽取于民，权亦不可尽放于郡。",
  "#ext:名将杀/audio/skill/mjsyantiezhiyi2": "罢榷酤，专盐铁，取其中道，以安天下。",
  "#ext:名将杀/audio/die/mjs_liufuling:die": "十三载山河无恙，朕又何憾？",
  "#ext:名将杀/audio/die/mjs_liufuling2:die": "来生，愿做长安少年郎。",

  "#ext:名将杀/audio/skill/mjsqingguoqingcheng1": "罗袖动香，踏云逐月。",
  "#ext:名将杀/audio/skill/mjsqingguoqingcheng2": "一顾倾人城，再顾倾人国。",
  "#ext:名将杀/audio/skill/mjsshanshanlaichi1": "长路漫漫，何必匆匆。",
  "#ext:名将杀/audio/skill/mjsshanshanlaichi2": "时日久长，岂耽朝暮？",
  "#ext:名将杀/audio/die/mjs_lifuren:die": "此去巫山云雨散，犹化明月入君怀。",
  "#ext:名将杀/audio/die/mjs_lifuren2:die": "不必招魂，不应执迷……",

  "#ext:名将杀/audio/skill/mjsqiaoshoujiangxin1": "天象舆地，皆在方寸之间。",
  "#ext:名将杀/audio/skill/mjsqiaoshoujiangxin2": "尺规量天地，巧手出造化。",
  "#ext:名将杀/audio/skill/mjsqizhizuomou1": "君掌乾罡，我司巧物。",
  "#ext:名将杀/audio/skill/mjsqizhizuomou2": "藏舟于壑，藏山于泽。",
  "#ext:名将杀/audio/die/mjs_huangyueying:die": "智可谋人事，终难逆天命……",
  "#ext:名将杀/audio/die/mjs_huangyueying2:die": "只恨奇巧未尽，天不假年。",

  "#ext:名将杀/audio/skill/mjszhongzhenganglie1": "休戚与共，方见真章。",
  "#ext:名将杀/audio/skill/mjszhongzhenganglie2": "吾与君，同手足，共命数。",
  "#ext:名将杀/audio/skill/mjssheziquanyi1": "丧元不足为重，况一子哉？",
  "#ext:名将杀/audio/skill/mjssheziquanyi2": "骨肉虽痛，岂碍义之所在？",
  "#ext:名将杀/audio/die/mjs_wangyi:die": "昔年庭槐犹在，不见故人衣冠。",
  "#ext:名将杀/audio/die/mjs_wangyi2:die": "舍身全义，无悔无怨。",

  "#ext:名将杀/audio/skill/mjsjianshuruye1": "璞玉藏于山野，慧眼当破俗尘。",
  "#ext:名将杀/audio/skill/mjsjianshuruye2": "寒门有锦羽，可栖凤凰枝。",
  "#ext:名将杀/audio/skill/mjsjianshuruye3": "金凤鸣时，当念旧音。",
  "#ext:名将杀/audio/skill/mjsjianshuruye4": "昔年一着棋，终报枰外人。",
  "#ext:名将杀/audio/skill/mjsfenglisanchun1": "借君光华，成我春秋。",
  "#ext:名将杀/audio/skill/mjsfenglisanchun2": "既结连理，当知共飨之义。",
  "#ext:名将杀/audio/die/mjs_pingyanggongzhu:die": "侯府草木尚知荣枯，况人乎？",
  "#ext:名将杀/audio/die/mjs_pingyanggongzhu2:die": "也好，不用再盼长安月明……",

  "#ext:名将杀/audio/skill/mjsxingjuyouchang1": "守节秉谊，以安宗庙。",
  "#ext:名将杀/audio/skill/mjsxingjuyouchang2": "出入下殿门，止进有常处。",
  "#ext:名将杀/audio/skill/mjsmangcizaibei1": "战战栗栗，日慎一日……",
  "#ext:名将杀/audio/skill/mjsmangcizaibei2": "如临深渊，如履薄冰……",
  "#ext:名将杀/audio/skill/mjsshanzhuanfeili1": "臣宁负王，不敢负社稷！",
  "#ext:名将杀/audio/skill/mjsshanzhuanfeili2": "大宗亡嗣，择支子孙贤者为嗣！",
  "#ext:名将杀/audio/die/mjs_huoguang:die": "乡使听客之言，不至亡于火患。",
  "#ext:名将杀/audio/die/mjs_huoguang2:die": "悔溺盈溢之欲也……",

  "#ext:名将杀/audio/skill/mjsxiushenjiexing1": "君子抱节，可御千军。",
  "#ext:名将杀/audio/skill/mjsxiushenjiexing2": "吾心皎皎，岂为浊世所污？",
  "#ext:名将杀/audio/skill/mjsshijingyinzhe1": "不历尘俗百态，何以断天下机变？",
  "#ext:名将杀/audio/skill/mjsshijingyinzhe2": "大隐于市，静观风云。",
  "#ext:名将杀/audio/skill/mjsyishenmingzhi1": "今当北乡自刭，以送公子。",
  "#ext:名将杀/audio/skill/mjsyishenmingzhi2": "欲得奇正，先舍形骸。",
  "#ext:名将杀/audio/die/mjs_houying:die": "朽迈之躯，得死于义，幸甚。",
  "#ext:名将杀/audio/die/mjs_houying2:die": "死生幸与不幸，谁人能知？",

  "#ext:名将杀/audio/skill/mjsbujuxiaoli1": "市井屠夫，只识刀锋，不识虚礼。",
  "#ext:名将杀/audio/skill/mjsbujuxiaoli2": "庙堂礼数，不如我袖中铁锤。",
  "#ext:名将杀/audio/skill/mjsshijingguoshi1": "解牛刀亦可屠龙。",
  "#ext:名将杀/audio/skill/mjsshijingguoshi2": "屠刀断肉，铁锤碎鼎。",
  "#ext:名将杀/audio/skill/mjsyishenbohu1": "若惧猛虎凶兽，枉称七尺男儿。",
  "#ext:名将杀/audio/skill/mjsyishenbohu2": "市井操刀多年，早看惯血染衣襟。",
  "#ext:名将杀/audio/die/mjs_zhuhai:die": "丈夫为大义死生，何须涕泣？",
  "#ext:名将杀/audio/die/mjs_zhuhai2:die": "快意恩仇，足矣！",

  "#ext:名将杀/audio/skill/mjsbaimayicong1": "吾有白马千匹，精卒数万。",
  "#ext:名将杀/audio/skill/mjsbaimayicong2": "天下骁锐，皆出我幽燕铁骑。",
  "#ext:名将杀/audio/skill/mjsbaimayicong3": "纵千军万马，亦不能挡我驰骋。",
  "#ext:名将杀/audio/skill/mjsbaimayicong4": "瞬息之间，千骑已至。",
  "#ext:名将杀/audio/skill/mjszhujingzigu1": "积粟百万，睥睨群雄。",
  "#ext:名将杀/audio/skill/mjszhujingzigu2": "筑楼易京，固若金汤。",
  "#ext:名将杀/audio/die/mjs_gongsunzan:die": "天下虽广，欲求安足之地，其可得乎！",
  "#ext:名将杀/audio/die/mjs_gongsunzan2:die": "义从，星散矣……",

  "#ext:名将杀/audio/skill/mjszongmatidao1": "纵余一息，亦当冲阵破敌。",
  "#ext:名将杀/audio/skill/mjszongmatidao2": "效死之时，岂容踌躇？",
  "#ext:名将杀/audio/skill/mjsyuxuefenwei1": "破敌夺械，正合我用。",
  "#ext:名将杀/audio/skill/mjsyuxuefenwei2": "乘势而进，甲兵相续。",
  "#ext:名将杀/audio/die/mjs_lingtong:die": "只恨，未能尽孝全忠……",
  "#ext:名将杀/audio/die/mjs_lingtong2:die": "大丈夫战死沙场，幸也！",

  "#ext:名将杀/audio/skill/mjspoqinfengrui1": "兵戈加身，正合吾意。",
  "#ext:名将杀/audio/skill/mjspoqinfengrui2": "借尔锋芒，砺吾剑戟。",
  "#ext:名将杀/audio/skill/mjschusuisaihu1": "薪火相传，此志不绝。",
  "#ext:名将杀/audio/skill/mjschusuisaihu2": "山河崩摧处，自有擎天脊。",
  "#ext:名将杀/audio/skill/mjschusuisaihu3": "毋妄言，族矣！",
  "#ext:名将杀/audio/skill/mjschusuisaihu4": "项氏世代楚将。",
  "#ext:名将杀/audio/die/mjs_xiangyan:die": "烽烟终散于秋风。",
  "#ext:名将杀/audio/die/mjs_xiangyan2:die": "烽火未熄，恨不能再战一轮。",

  "#ext:名将杀/audio/skill/mjsqingyinwangyou1": "清音涤尘，前缘尽散。",
  "#ext:名将杀/audio/skill/mjsqingyinwangyou2": "阳春化刃，暗渡无痕。",
  "#ext:名将杀/audio/skill/mjsqingyinwangyou3": "卦象更新，天机流转。",
  "#ext:名将杀/audio/skill/mjsqingyinwangyou4": "因果重塑，万象更新。",
  "#ext:名将杀/audio/skill/mjsyangchunbaixue1": "阳春白雪启瑶琴，清音一曲慰风尘。",
  "#ext:名将杀/audio/skill/mjsyangchunbaixue2": "莫愁歌一字，恰恰印心头。",
  "#ext:名将杀/audio/die/mjs_lumochou:die": "人去后，垂杨自碧；歌舞梦，欲寻无迹。",
  "#ext:名将杀/audio/die/mjs_lumochou2:die": "帆去帆来风浩渺，花开花谢春悲凉。",

  "#ext:名将杀/audio/skill/mjsyantieguanying1": "天下之利，当收于官。",
  "#ext:名将杀/audio/skill/mjsyantieguanying2": "山海之利，尽归国库。",
  "#ext:名将杀/audio/skill/mjsjunshupingzhun1": "均输平准，可调万物贵贱。",
  "#ext:名将杀/audio/skill/mjsjunshupingzhun2": "涨落在我，何患不均？",
  "#ext:名将杀/audio/skill/mjssuanmingaomin1": "隐户现形，私产归公。",
  "#ext:名将杀/audio/skill/mjssuanmingaomin2": "坐拥万金而不利国库，与蛀国何异？",
  "#ext:名将杀/audio/die/mjs_sanghongyang:die": "国库充盈，边关安稳，此生，不负……",
  "#ext:名将杀/audio/die/mjs_sanghongyang2:die": "后世毁誉，不过一缕余墨。",

  "#ext:名将杀/audio/skill/mjssanshiliufang1": "万千太平信众，皆为吾之后盾。",
  "#ext:名将杀/audio/skill/mjssanshiliufang2": "三十六方，薪火不绝。",
  "#ext:名将杀/audio/skill/mjssanshiliufang3": "乱世流民，皆以雷鸣为号。",
  "#ext:名将杀/audio/skill/mjssanshiliufang4": "雷动九霄，代天行罚。",
  "#ext:名将杀/audio/skill/mjshuangtianyaofa1": "四方雷煞，听我号令。",
  "#ext:名将杀/audio/skill/mjshuangtianyaofa2": "电母雷公，速降神通。",
  "#ext:名将杀/audio/skill/mjshuangtianyaofa3": "天威过处，皆可为我所用。",
  "#ext:名将杀/audio/skill/mjshuangtianyaofa4": "雷霆者，非只刑杀之器，亦生生之机。",
  "#ext:名将杀/audio/die/mjs_zhangbao:die": "大业未成，奈何天绝我路……",
  "#ext:名将杀/audio/die/mjs_zhangbao2:die": "宁为太平鬼，不作乱世人。",

  "#ext:名将杀/audio/skill/mjsshenliyiji1": "借力黄天，重塑乾坤！",
  "#ext:名将杀/audio/skill/mjsshenliyiji2": "腐朽崩摧，大道开来！",
  "#ext:名将杀/audio/skill/mjshuangtianjingyong1": "黄天之下，岂有孤军？",
  "#ext:名将杀/audio/skill/mjshuangtianjingyong2": "这遍地黎庶，便是滔滔洪流。",
  "#ext:名将杀/audio/die/mjs_zhanglianghuang:die": "身死，道存！",
  "#ext:名将杀/audio/die/mjs_zhanglianghuang2:die": "愿化燎原火，焚此旧山河……",

  "#ext:名将杀/audio/skill/mjsxieyierzhan1": "诛暴乱、禁不义。",
  "#ext:名将杀/audio/skill/mjsxieyierzhan2": "挟义而战者，贵从我起。",
  "#ext:名将杀/audio/skill/mjstianguanbingtan1": "先神先鬼，先稽我智。",
  "#ext:名将杀/audio/skill/mjstianguanbingtan2": "天官时日，不若人事也。",
  "#ext:名将杀/audio/skill/mjstianguanbingtan3": "刑以伐之，德以守之。",
  "#ext:名将杀/audio/skill/mjstianguanbingtan4": "天时不如地利，地利不如人和。",
  "#ext:名将杀/audio/skill/mjszhanweigongquan1": "民不发轫，甲不出暴，而威制天下。",
  "#ext:名将杀/audio/skill/mjszhanweigongquan2": "兵以静胜，国以专胜。",
  "#ext:名将杀/audio/die/mjs_weiliao:die": "兵道无穷，终不敌人心诡诈。",
  "#ext:名将杀/audio/die/mjs_weiliao2:die": "将者心也，心乱则军亡！",

  "#ext:名将杀/audio/skill/mjsliaodihebian1": "专军并锐，触其不意。",
  "#ext:名将杀/audio/skill/mjsliaodihebian2": "计利形势，自然之理。",
  "#ext:名将杀/audio/skill/mjschuqiwuqiong1": "兵以正合，以奇胜。",
  "#ext:名将杀/audio/skill/mjschuqiwuqiong2": "奇正相生，岂有穷尽？",
  "#ext:名将杀/audio/skill/mjsjianmie1": "吾非嗜杀，乃奉天道征伐。",
  "#ext:名将杀/audio/skill/mjsjianmie2": "破国不可复完，死卒不可复生。",
  "#ext:名将杀/audio/die/mjs_baiqi:die": "我有何罪于天乎？",
  "#ext:名将杀/audio/die/mjs_baiqi2:die": "宁伏受重诛而死，不忍为辱军之将。",

  "#ext:名将杀/audio/skill/mjsguoshizhuangyong1": "龙潭虎穴，不过试剑石尔。",
  "#ext:名将杀/audio/skill/mjsguoshizhuangyong2": "天下风云，且待我辈。",
  "#ext:名将杀/audio/skill/mjsyanshuizhuifeng1": "轻骑疾进，方有纵横之机。",
  "#ext:名将杀/audio/skill/mjsyanshuizhuifeng2": "卸甲胄，弃营帐，但求战局在我。",
  "#ext:名将杀/audio/skill/mjsyanshuizhuifeng3": "纵有千军，吾亦往矣。",
  "#ext:名将杀/audio/skill/mjsyanshuizhuifeng4": "三军饱食，再战再捷。",
  "#ext:名将杀/audio/die/mjs_lixin:die": "纵百死，亦无悔。",
  "#ext:名将杀/audio/die/mjs_lixin2:die": "生死寻常事，肝胆照昆仑。",

  "#ext:名将杀/audio/skill/mjschilifeiren1": "侵我疆土，且问过吾手中飞刀？",
  "#ext:名将杀/audio/skill/mjschilifeiren2": "南中飞刃在此，纵一纸亦化千钧。",
  "#ext:名将杀/audio/skill/mjshuoshenzuyi1": "吾乃祝融后裔，岂畏区区凡火？",
  "#ext:名将杀/audio/skill/mjshuoshenzuyi2": "血脉护身，诸炎不侵。",
  "#ext:名将杀/audio/skill/mjshuoshenzuyi3": "千载火脉，今日重燃。",
  "#ext:名将杀/audio/skill/mjshuoshenzuyi4": "炎羽破空，贯日逐风。",
  "#ext:名将杀/audio/die/mjs_zhurongfuren:die": "竟中宵小之计……",
  "#ext:名将杀/audio/die/mjs_zhurongfuren2:die": "连天焰火，终有烬时。",

  "#ext:名将杀/audio/skill/mjsziqingsuoyu1": "燕士重诺，当以血肉报知己！",
  "#ext:名将杀/audio/skill/mjsziqingsuoyu2": "险境已至，请以此为继。",
  "#ext:名将杀/audio/skill/mjsyishuicuxing1": "白衣胜雪，击筑如泣。",
  "#ext:名将杀/audio/skill/mjsyishuicuxing2": "以此残躯，为君辟路。",
  "#ext:名将杀/audio/die/mjs_taizidan:die": "宏图未竟，国仇未雪，恨难平……",
  "#ext:名将杀/audio/die/mjs_taizidan2:die": "以一人之力，逆天下之势，终是一场空。",

  "#ext:名将杀/audio/skill/mjsxiongyubaishou1": "山君听我号令，鹰隼为我前锋。",
  "#ext:名将杀/audio/skill/mjsxiongyubaishou2": "百兽随行，裂石断金！",
  "#ext:名将杀/audio/skill/mjsnanzhongzhizhu1": "赤水为脉，哀牢为骨。",
  "#ext:名将杀/audio/skill/mjsnanzhongzhizhu2": "醉卧藤枕听象鼓，方是吾乡真风流。",
  "#ext:名将杀/audio/die/mjs_menghuo:die": "吾今误中诡计，死不瞑目！",
  "#ext:名将杀/audio/die/mjs_menghuo2:die": "南中永不臣服……",

  "#ext:名将杀/audio/skill/mjsyitongliuhe1": "六合之内，皆为大秦疆土。",
  "#ext:名将杀/audio/skill/mjsyitongliuhe2": "扫清六合，如拂棋枰。",
  "#ext:名将杀/audio/skill/mjsqinnuqishe1": "进若雷霆，退如山峙。",
  "#ext:名将杀/audio/skill/mjsqinnuqishe2": "长城为弓弩，驰道作惊弦。",
  "#ext:名将杀/audio/skill/mjsqinnuqishe3": "黑云蔽日，大秦风鸣！",
  "#ext:名将杀/audio/skill/mjsqinnuqishe4": "九霄云裂，万镞摧城！",
  "#ext:名将杀/audio/skill/mjsqinnuqishe5": "跖劲弩，带利剑。",
  "#ext:名将杀/audio/skill/mjsqinnuqishe6": "修障隧备塞之具，厉长戟劲弩之械。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng1": "用制险塞，折冲万里。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng2": "胡马不窥于长城，羽檄不行于中国。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng3": "长城巨防，足以为塞。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng4": "延袤万里，四夷宾服。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng5": "发边戍，筑长城，修关梁，设障塞。",
  "#ext:名将杀/audio/skill/mjswanlichangcheng6": "筑长城于戎境，以备胡、越。",
  "#ext:名将杀/audio/die/mjs_yingzheng:die": "东海仙药，原是虚妄……",
  "#ext:名将杀/audio/die/mjs_yingzheng2:die": "若天命绝朕于此，便教山河作殉！",

  "#ext:名将杀/audio/skill/mjshengsaosanjin1": "弓弩蓄势，剑戟向前。",
  "#ext:名将杀/audio/skill/mjshengsaosanjin2": "列阵如磐，进止如山。",
  "#ext:名将杀/audio/skill/mjsqingtian1": "大王必不得已用臣，非六十万人不可。",
  "#ext:名将杀/audio/skill/mjsqingtian2": "为将者，非求赫赫之功，惟求万全之策。",
  "#ext:名将杀/audio/skill/mjschiduancunchang1": "尺有所短，寸有所长。",
  "#ext:名将杀/audio/skill/mjschiduancunchang2": "智有所不明，神有所不通。",
  "#ext:名将杀/audio/die/mjs_wangjian:die": "三十余载无败绩，今日竟……",
  "#ext:名将杀/audio/die/mjs_wangjian2:die": "非畏死，但未见四海升平，华夏永宁。",

  "#ext:名将杀/audio/skill/mjsfudingjianxie1": "冕旒之重，不在其冠，而在其权。",
  "#ext:名将杀/audio/skill/mjsfudingjianxie2": "天子之威，可借不可夺。",
  "#ext:名将杀/audio/skill/mjsyidaizhao1": "朕承天命，岂可坐视奸雄裂我山河？",
  "#ext:名将杀/audio/skill/mjsyidaizhao2": "卿无作威福，放兵纵横，欲何为乎？",
  "#ext:名将杀/audio/skill/mjsyidaizhao3": "除汉贼者，重赏。",
  "#ext:名将杀/audio/skill/mjsyidaizhao4": "天下义士，与朕共诛之！",
  "#ext:名将杀/audio/skill/mjsyidaizhao5": "国贼已除，神器归位。",
  "#ext:名将杀/audio/skill/mjsyidaizhao6": "权柄既归，朕当亲揽乾坤。",
  "#ext:名将杀/audio/die/mjs_liuxie:die": "四百载汉室社稷，竟亡于朕手……",
  "#ext:名将杀/audio/die/mjs_liuxie2:die": "乱世，才刚刚开始。",

  "#ext:名将杀/audio/skill/mjszishoudaishi1": "雍容荆楚，坐观时变。",
  "#ext:名将杀/audio/skill/mjszishoudaishi2": "当保境安民，以待天时。",
  "#ext:名将杀/audio/skill/mjspiananjingxiang1": "虽无逐鹿之志，亦有守土之方。",
  "#ext:名将杀/audio/skill/mjspiananjingxiang2": "纵中原逐鹿，我自安九郡。",
  "#ext:名将杀/audio/die/mjs_liubiao:die": "偏安自守，终是画地为牢……",
  "#ext:名将杀/audio/die/mjs_liubiao2:die": "可叹满架诗书，未能救得乱世。",

  "#ext:名将杀/audio/skill/mjsjizhuerge1": "筑声未绝，壮心不休。",
  "#ext:名将杀/audio/skill/mjsjizhuerge2": "筑为兵刃，曲作锋镝。",
  "#ext:名将杀/audio/skill/mjsjizhuerge3": "闻此音律，当再续宫商。",
  "#ext:名将杀/audio/skill/mjsjizhuerge4": "余韵将歇，理当再兴一曲。",
  "#ext:名将杀/audio/skill/mjsbianzhizhisheng1": "变徵之声，可裂金石。",
  "#ext:名将杀/audio/skill/mjsbianzhizhisheng2": "变徵既起，天地同悲。",
  "#ext:名将杀/audio/skill/mjsbianzhizhisheng3": "连音既成，自当再续清商。",
  "#ext:名将杀/audio/skill/mjsbianzhizhisheng4": "弦如易水寒，歌作雷霆怒。",
  "#ext:名将杀/audio/skill/mjszhuangshiquxi1": "易水寒彻，此恨不绝",
  "#ext:名将杀/audio/skill/mjszhuangshiquxi2": "宫商绝响，唯余兵戈之声！",
  "#ext:名将杀/audio/die/mjs_gaojianli:die": "铅筑既摧，肝胆谁剖？",
  "#ext:名将杀/audio/die/mjs_gaojianli2:die": "这最后一曲，再无人和……",

  "#ext:名将杀/audio/skill/mjslikangwancheng1": "帝者坐拥天下，清亦自有河山。",
  "#ext:名将杀/audio/skill/mjslikangwancheng2": "守一方基业，护万千生计。",
  "#ext:名将杀/audio/skill/mjsdanshanvwang1": "朱砂铸金城，赤心守家邦。",
  "#ext:名将杀/audio/skill/mjsdanshanvwang2": "凭此赤色，可绘江山。",
  "#ext:名将杀/audio/skill/mjshuaiqingtai1": "巴蜀山水犹在，此身可归矣。",
  "#ext:名将杀/audio/skill/mjshuaiqingtai2": "千金总散尽，繁华终为尘……",
  "#ext:名将杀/audio/die/mjs_baqing:die": "巴蜀山水犹在，此身可归矣。",
  "#ext:名将杀/audio/die/mjs_baqing2:die": "千金总散尽，繁华终为尘……",

  "#ext:名将杀/audio/skill/mjstiesuolianzhou1": "潮生潮落，风浪不息。",
  "#ext:名将杀/audio/skill/mjstiesuolianzhou2": "乘此而行，风浪潮水上下，复何惧哉？",
  "#ext:名将杀/audio/skill/mjsyuhuochongsheng1": "浴火重生，再展经纶！",
  "#ext:名将杀/audio/skill/mjsyuhuochongsheng2": "烈火涅槃，再定乾坤！",
  "#ext:名将杀/audio/die/mjs_pangtong:die": "壮士临阵，不死带伤，理之自然也。",
  "#ext:名将杀/audio/die/mjs_pangtong2:die": "肝脑涂地，方称本心。",

  "#ext:名将杀/audio/skill/mjstugaodaihan1": "代汉者，当涂高也。",
  "#ext:名将杀/audio/skill/mjstugaodaihan2": "传国玉玺在此，天命归于仲氏。",
  "#ext:名将杀/audio/skill/mjssishisangong_mjs_yuanshu1": "树恩四世，岂为蚍蜉（pí fú）所撼？",
  "#ext:名将杀/audio/skill/mjssishisangong_mjs_yuanshu2": "累世公卿，自有根基。",
  "#ext:名将杀/audio/skill/mjswangzizunda1": "淮南带甲百万，江淮尽入吾彀。",
  "#ext:名将杀/audio/skill/mjswangzizunda2": "江山若无袁氏，何异于枯木散沙。",
  "#ext:名将杀/audio/die/mjs_yuanshu:die": "汉室已朽，吾不过代天行替……",
  "#ext:名将杀/audio/die/mjs_yuanshu2:die": "九五之尊，竟是黄粱一梦。",

  "#ext:名将杀/audio/skill/mjsyibudiqin1": "秦虽虎狼，不足惧也。",
  "#ext:名将杀/audio/skill/mjsyibudiqin2": "宁蹈东海，不拜咸阳。",
  "#ext:名将杀/audio/skill/mjsyijiandingliao1": "弃忿悁之节，定累世之功。",
  "#ext:名将杀/audio/skill/mjsyijiandingliao2": "去感忿之怨，立终身之名。",
  "#ext:名将杀/audio/skill/mjszhumingshuojin1": "非金非玉，惟寸心明澈。",
  "#ext:名将杀/audio/skill/mjszhumingshuojin2": "明珠不暗投，良策赠英雄。",
  "#ext:名将杀/audio/die/mjs_luzhonglian:die": "吾将与白云同游，不必复寻。",
  "#ext:名将杀/audio/die/mjs_luzhonglian2:die": "清风沧浪，终难洗尽兵尘……",

  "#ext:名将杀/audio/skill/mjshuiyanshilang1": "市井藏龙，待我慧眼识之。",
  "#ext:名将杀/audio/skill/mjshuiyanshilang2": "众里寻他，终遇栋梁之材。",
  "#ext:名将杀/audio/skill/mjshuiyanshilang3": "心意相通，方能福祸与共。",
  "#ext:名将杀/audio/skill/mjshuiyanshilang4": "风云共济，气运同享！",
  "#ext:名将杀/audio/skill/mjsshiqinjinshen1": "示弱藏锋，以待天时。",
  "#ext:名将杀/audio/skill/mjsshiqinjinshen2": "韬光养晦，以固国本。",
  "#ext:名将杀/audio/skill/mjsqiaojieyuhuan1": "此环既解，请君自尝其果！",
  "#ext:名将杀/audio/skill/mjsqiaojieyuhuan2": "雕虫小技，也敢班门弄斧？",
  "#ext:名将杀/audio/die/mjs_junwanghou:die": "玉碎连环前尘尽，唯见残阳映齐宫。",
  "#ext:名将杀/audio/die/mjs_junwanghou2:die": "不见海岱清平，空余长叹声声。",

  "#ext:名将杀/audio/skill/mjsrenhuifuxia1": "不争一时之锋，但求百世之安。",
  "#ext:名将杀/audio/skill/mjsrenhuifuxia2": "慈心为引，仁术为方。",
  "#ext:名将杀/audio/skill/mjsguanchonghouting1": "松柏之固，不在枝繁，而在根深。",
  "#ext:名将杀/audio/skill/mjsguanchonghouting2": "须知世间荣华，不及相知朝夕。",
  "#ext:名将杀/audio/skill/mjszhuicezhonggong1": "君以诚待我，我以心奉君。",
  "#ext:名将杀/audio/skill/mjszhuicezhonggong2": "君为乔木，妾作丝萝。风雨来时，必当共担。",
  "#ext:名将杀/audio/die/mjs_bulianshi:die": "生死，不过如是……",
  "#ext:名将杀/audio/die/mjs_bulianshi2:die": "春雨如丝，正似那年初见。",

  "#ext:名将杀/audio/skill/mjsyuanbishanshe1": "守备既空，胜负已定。",
  "#ext:名将杀/audio/skill/mjsyuanbishanshe2": "弓矢在手，贯甲穿杨。",
  "#ext:名将杀/audio/skill/mjsyuanbishanshe3": "一退一进，方为破敌之道。",
  "#ext:名将杀/audio/skill/mjsyuanbishanshe4": "区区雕虫小技。",
  "#ext:名将杀/audio/skill/mjsshentinghanzzhan1": "只我二人，今日一决雄雌！",
  "#ext:名将杀/audio/skill/mjsshentinghanzzhan2": "可敢与某纵马一战？",
  "#ext:名将杀/audio/die/mjs_taishici:die": "矢尽弓折，惟负主公厚恩。",
  "#ext:名将杀/audio/die/mjs_taishici2:die": "所志未遂，奈何死乎！",

  "#ext:名将杀/audio/skill/mjsjuehaoshanwu1": "君前流云袖，掌上回雪腰。",
  "#ext:名将杀/audio/skill/mjsjuehaoshanwu2": "日暖笙歌彻，六宫拜牡丹。",
  "#ext:名将杀/audio/skill/mjsjuehaoshanwu3": "得失予夺，皆蕴不定之机。",
  "#ext:名将杀/audio/skill/mjsjuehaoshanwu4": "掷却残香万骑生。。",
  "#ext:名将杀/audio/skill/mjsyinguiganquan1": "缚得玲珑茧，方成锦绣衣。",
  "#ext:名将杀/audio/skill/mjsyinguiganquan2": "妾身一局棋，可换凌霄梯。",
  "#ext:名将杀/audio/die/mjs_zhaoji:die": "半生困樊笼，梦里人不归。",
  "#ext:名将杀/audio/die/mjs_zhaoji2:die": "朱颜色褪，青史斑驳，奈何奈何……",

  "#ext:名将杀/audio/skill/mjsqihuokeju1": "奇货可居，非常之利也。",
  "#ext:名将杀/audio/skill/mjsqihuokeju2": "世人见珠玉，吾独见江山。",
  "#ext:名将杀/audio/skill/mjsqihuokeju3": "天不再与，时不久留。",
  "#ext:名将杀/audio/skill/mjsqihuokeju4": "流水不腐，户枢不蠹。",
  "#ext:名将杀/audio/skill/mjsyiziqianjin1": "兼儒墨，合名法。",
  "#ext:名将杀/audio/skill/mjsyiziqianjin2": "汇集百家，方成不朽。",
  "#ext:名将杀/audio/die/mjs_lvbuwei:die": "半生经营，竟似黄粱一梦……",
  "#ext:名将杀/audio/die/mjs_lvbuwei2:die": "谋划三十载，却是吕氏春秋，赵氏天下。",

  "#ext:名将杀/audio/skill/mjstianshuiqiliner1": "愿请精兵三千，伏于要路。",
  "#ext:名将杀/audio/skill/mjstianshuiqiliner2": "兵势如水，避实击虚。",
  "#ext:名将杀/audio/skill/mjsjiufazhongyuan1": "纵使九度挥师，亦要叩问中原！",
  "#ext:名将杀/audio/skill/mjsjiufazhongyuan2": "进取中原，重兴汉室！",
  "#ext:名将杀/audio/skill/mjsshizhikuanghan1": "若有未捷，杀身以报。",
  "#ext:名将杀/audio/skill/mjsshizhikuanghan2": "这一着险棋，我下定了。",
  "#ext:名将杀/audio/skill/mjsshizhikuanghan3": "纵天命难违，吾亦九死未悔。",
  "#ext:名将杀/audio/skill/mjsshizhikuanghan4": "若得汉祚重光，何惧燃为星烬？",
  "#ext:名将杀/audio/die/mjs_jiangwei:die": "人生如白驹过隙，何日恢复中原？",
  "#ext:名将杀/audio/die/mjs_jiangwei2:die": "利害未明，而见机之不早也……",

  "#ext:名将杀/audio/skill/mjsqihuacesuan1": "天机虽隐，亦有迹可循。",
  "#ext:名将杀/audio/skill/mjsqihuacesuan2": "观星见微，察气知变。",
  "#ext:名将杀/audio/skill/mjsyazibibao1": "此乃反客为主之法。",
  "#ext:名将杀/audio/skill/mjsyazibibao2": "睚眦必酬，恩德必报。",
  "#ext:名将杀/audio/die/mjs_fazheng:die": "竟漏算了这一着……",
  "#ext:名将杀/audio/die/mjs_fazheng2:die": "快意恩仇，此生无憾。",

  "#ext:名将杀/audio/skill/mjstuqiongbijian1": "此非刺客之刃，乃万民之志！",
  "#ext:名将杀/audio/skill/mjstuqiongbijian2": "图穷终现匕，易水有余寒！",
  "#ext:名将杀/audio/skill/mjsbaxiuerzhen1": "天下轻重，尽在尺刃之间！",
  "#ext:名将杀/audio/skill/mjsbaxiuerzhen2": "近身咫尺，取命方寸！",
  "#ext:名将杀/audio/skill/mjschibizhizhu1": "往而不返者，竖子也！",
  "#ext:名将杀/audio/skill/mjschibizhizhu2": "一击不中，犹可掷柱！",
  "#ext:名将杀/audio/die/mjs_jingke:die": "剑出无回，此身亦无回。",
  "#ext:名将杀/audio/die/mjs_jingke2:die": "易水曲别，终成绝响。",

  "#ext:名将杀/audio/skill/mjsfengxiaxiantu1": "燕地山川尽在，只待展图细观。",
  "#ext:名将杀/audio/skill/mjsfengxiaxiantu2": "山川形胜，尽在尺素。",
  "#ext:名将杀/audio/skill/mjsyanyouyongshi1": "天下谁人不可杀？",
  "#ext:名将杀/audio/skill/mjsyanyouyongshi2": "汝等可识得燕地秦舞阳？",
  "#ext:名将杀/audio/skill/mjssebianzhenkong1": "血作酒，骨为薪！",
  "#ext:名将杀/audio/skill/mjssebianzhenkong2": "断肠蚀骨，又有何妨？",
  "#ext:名将杀/audio/die/mjs_qinwuyang:die": "终是，负了故人之约……",
  "#ext:名将杀/audio/die/mjs_qinwuyang2:die": "魂归易水，不负少年行。",

  "#ext:名将杀/audio/skill/mjsjieliangfenzi1": "用兵之道，溃其腹心，摧其爪牙。",
  "#ext:名将杀/audio/skill/mjsjieliangfenzi2": "截粮如断脊，焚辋若折翼。",
  "#ext:名将杀/audio/skill/mjsfupochongwei1": "纵有坚盾，亦难周全！",
  "#ext:名将杀/audio/skill/mjsfupochongwei2": "用兵如弈，一着未竟，一着复生。",
  "#ext:名将杀/audio/die/mjs_xuhuang:die": "晃再不能为前驱了……",
  "#ext:名将杀/audio/die/mjs_xuhuang2:die": "将军死战，幸也！",

  "#ext:名将杀/audio/skill/mjshualuojueqing1": "此痛，请君一同品鉴。",
  "#ext:名将杀/audio/skill/mjshualuojueqing2": "血债，需以血偿。",
  "#ext:名将杀/audio/skill/mjstongshuishangshi1": "芳魂自损，化成锋芒。",
  "#ext:名将杀/audio/skill/mjstongshuishangshi2": "落红终是无情之物。",
  "#ext:名将杀/audio/die/mjs_zhangchunhua:die": "花终落，人终散。",
  "#ext:名将杀/audio/die/mjs_zhangchunhua2:die": "只恨未能扫清后患。",

  "#ext:名将杀/audio/skill/mjsmenghuxiaolin1": "猛虎登山，何惧险峰？",
  "#ext:名将杀/audio/skill/mjsmenghuxiaolin2": "虎啸中原，谁人可当？",
  "#ext:名将杀/audio/skill/mjskuajiangjibiao1": "舳舻千里，跨江而来，誓擒此獠！",
  "#ext:名将杀/audio/skill/mjskuajiangjibiao2": "荆襄九郡，已在囊中！",
  "#ext:名将杀/audio/skill/mjshundingjiangdong1": "江东子弟岂甘做池中之物？",
  "#ext:名将杀/audio/skill/mjshundingjiangdong2": "霸业之路，交由尔等前行了。",
  "#ext:名将杀/audio/die/mjs_sunjian:die": "可叹万民涂炭，贼臣乱国……",
  "#ext:名将杀/audio/die/mjs_sunjian2:die": "大丈夫纵死沙场，犹胜屈膝苟活！",

  "#ext:名将杀/audio/skill/mjskurouji1": "人不自害，受害必真。",
  "#ext:名将杀/audio/skill/mjskurouji2": "若不忍些小伤小痛，焉成大事？",
  "#ext:名将杀/audio/skill/mjszhaxiangfenzhou1": "不如弃甲倒戈，北面而降之。",
  "#ext:名将杀/audio/skill/mjszhaxiangfenzhou2": "信而安之，阴以图之，备而后动。",
  "#ext:名将杀/audio/die/mjs_huanggai:die": "某死亦无怨。",
  "#ext:名将杀/audio/die/mjs_huanggai2:die": "江水赤，乃吾最后战袍……",

  "#ext:名将杀/audio/skill/mjsganluzhaoqin1": "天下英雄，非唯鞍马之能，更需胸中丘壑。",
  "#ext:名将杀/audio/skill/mjsganluzhaoqin2": "识大体，知权变，方为栋梁之材。",
  "#ext:名将杀/audio/skill/mjsdaofucangen1": "太平二字，重逾千钧。",
  "#ext:名将杀/audio/skill/mjsdaofucangen2": "心思澄明，方能用好神兵利器。",
  "#ext:名将杀/audio/die/mjs_wuguotai:die": "江东数载，竟要止步于此么……",
  "#ext:名将杀/audio/die/mjs_wuguotai2:die": " 这一生，如大江奔流，足矣。",

  "#ext:名将杀/audio/skill/mjsshimengjushou1": "草木砾石，皆可为垒。",
  "#ext:名将杀/audio/skill/mjsshimengjushou2": "坚壁列阵，可御十万师。",
  "#ext:名将杀/audio/skill/mjsshimengjushou3": "善守者，百战砺甲，疮痍自复。",
  "#ext:名将杀/audio/skill/mjsshimengjushou4": "愈摧愈坚，方显魏将风骨。",
  "#ext:名将杀/audio/skill/mjsfengfaxingling1": "军中无戏言，麾下无二令。",
  "#ext:名将杀/audio/skill/mjsfengfaxingling2": "乱行列者，必以军法裁之。",
  "#ext:名将杀/audio/skill/mjsfengfaxingling3": "功必赏，过必刑。",
  "#ext:名将杀/audio/skill/mjstianrenjiangjun1": "危困若此，岂能独善其身？",
  "#ext:名将杀/audio/skill/mjstianrenjiangjun2": "大将者，当与士卒同命。",
  "#ext:名将杀/audio/die/mjs_caoren:die": "尚能……再战……",
  "#ext:名将杀/audio/die/mjs_caoren2:die": "守土报恩，仁无愧于心。",

  "#ext:名将杀/audio/skill/mjsbashidanjing1": "父精母血，不可弃也！",
  "#ext:名将杀/audio/skill/mjsbashidanjing2": "血债血偿！",
  "#ext:名将杀/audio/skill/mjsbashidanjing3": "不妨以血洗血！",
  "#ext:名将杀/audio/skill/mjsbashidanjing4": "枯目为刃，即行用锋。",
  "#ext:名将杀/audio/skill/mjsqingjianzunshi1": "金石之禄不可受。",
  "#ext:名将杀/audio/skill/mjsqingjianzunshi2": "家无余财，皆与铸兵。",
  "#ext:名将杀/audio/die/mjs_xiahoudun:die": "我会一直看着，大魏江山。",
  "#ext:名将杀/audio/die/mjs_xiahoudun2:die": "终于能阖眼长眠……",

  "#ext:名将杀/audio/skill/mjsqiaobianshanzhan1": "地势险峻处，正可设奇兵。",
  "#ext:名将杀/audio/skill/mjsqiaobianshanzhan2": "出与不出，皆在吾预料之中。",
  "#ext:名将杀/audio/skill/mjsyingshibuzhen1": "后发先至，兵形之妙也。",
  "#ext:名将杀/audio/skill/mjsyingshibuzhen2": "既已伤我，岂能全身而还？",
  "#ext:名将杀/audio/skill/mjshuhuhanjiang1": "刀锋饮血，方显悍将本色。",
  "#ext:名将杀/audio/skill/mjshuhuhanjiang2": "效虓虎之威，破万马千军。",
  "#ext:名将杀/audio/die/mjs_zhanghe:die": "身经百战，难逃命数。",
  "#ext:名将杀/audio/die/mjs_zhanghe2:die": "末将再不能为前驱矣……",

  "#ext:名将杀/audio/skill/mjssichengweiwu1": "弓马虽烈，今皆入朕武库。",
  "#ext:名将杀/audio/skill/mjssichengweiwu2": "刃之所至，反攫其锋。",
  "#ext:名将杀/audio/skill/mjsyangexingyin1": "燕歌疗疮痍，清商愈断肠。",
  "#ext:名将杀/audio/skill/mjsyangexingyin2": "展诗清歌，乐往哀来。",
  "#ext:名将杀/audio/skill/mjsshanrangshoufeng1": "揽彼菁华，铸我皇基。",
  "#ext:名将杀/audio/skill/mjsshanrangshoufeng2": "纳群雄遗风，聚九州气运。",
  "#ext:名将杀/audio/die/mjs_caopi:die": "人生如寄，多忧何为？",
  "#ext:名将杀/audio/die/mjs_caopi2:die": "山河未统，朕不甘，不甘啊！",

  "#ext:名将杀/audio/skill/mjscaigaobadou1": "驾超野之驷，乘追风之舆。",
  "#ext:名将杀/audio/skill/mjscaigaobadou2": "墨池倾酒，诗成惊鸿。",
  "#ext:名将杀/audio/skill/mjsqibuqiai1": "煮豆燃豆萁，豆在釜中泣。",
  "#ext:名将杀/audio/skill/mjsqibuqiai2": "花草亦能醉人，何须杜康？",
  "#ext:名将杀/audio/skill/mjsqibuqiai3": "此乃损益之道。",
  "#ext:名将杀/audio/skill/mjsqibuqiai4": "舍故纳新，天道循环。",
  "#ext:名将杀/audio/die/mjs_caozhi:die": "吾志不果，吾道不行……",
  "#ext:名将杀/audio/die/mjs_caozhi2:die": "捐躯赴国难，视死忽如归。",

  "#ext:名将杀/audio/skill/mjszhidaohuanglong1": "犁庭扫穴，复我河山。",
  "#ext:名将杀/audio/skill/mjszhidaohuanglong2": "直捣龙城，破灭千军。",
  "#ext:名将杀/audio/skill/mjscheqihezhan1": "武刚车者，为先驱。",
  "#ext:名将杀/audio/skill/mjscheqihezhan2": "轻车之制，以武刚车为殿",
  "#ext:名将杀/audio/skill/mjscheqihezhan3": "夹左右，并驾驷。",
  "#ext:名将杀/audio/skill/mjscheqihezhan4": "厩中有良马千匹。",
  "#ext:名将杀/audio/die/mjs_weiqing:die": "臣本鞍马奴仆，幸得拔擢，敢不以死报国？",
  "#ext:名将杀/audio/die/mjs_weiqing2:die": "将士用命，无生念也!",

  "#ext:名将杀/audio/skill/mjsheyijiawei1": "匈奴未灭，无以家为。",
  "#ext:名将杀/audio/skill/mjsheyijiawei2": "胡尘不扫，何以家为?",
  "#ext:名将杀/audio/skill/mjsfenglangjuxu1": "马踏焉支，剑指祁连！",
  "#ext:名将杀/audio/skill/mjsfenglangjuxu2": "归我大汉疆界，为我大汉子民。",
  "#ext:名将杀/audio/skill/mjsyinmahanhai1": "金人未碎，铁蹄不休!",
  "#ext:名将杀/audio/skill/mjsyinmahanhai2": "棱威瀚海，绝幕居延！",
  "#ext:名将杀/audio/die/mjs_huoqubing:die": "击鼓……再战……",
  "#ext:名将杀/audio/die/mjs_huoqubing2:die": "河西未固，焉能长眠？",

  "#ext:名将杀/audio/skill/mjstuienling1": "不行黜陟，而藩国自析。",
  "#ext:名将杀/audio/skill/mjstuienling2": "普天之下，皆受皇恩。",
  "#ext:名将杀/audio/skill/mjsgongshoushiyi1": "避其锐气，击其惰归。",
  "#ext:名将杀/audio/skill/mjsgongshoushiyi2": "故善战者，致人而不致于人。",
  "#ext:名将杀/audio/skill/mjsluntaizuiji1": "军士死略离散，悲痛常在朕心。",
  "#ext:名将杀/audio/skill/mjsluntaizuiji2": "当今务，在禁苛暴，止擅赋，力本农。",
  "#ext:名将杀/audio/die/mjs_liuche:die": "终究是方士诳语……",
  "#ext:名将杀/audio/die/mjs_liuche2:die": "泰山崩颓，谁之过欤？",

  "#ext:名将杀/audio/skill/mjspingyanouzhe1": "抚长剑兮玉珥，缪锵鸣兮琳琅。",
  "#ext:名将杀/audio/skill/mjspingyanouzhe2": "疏缓节兮安歌，陈竽瑟兮浩倡。",
  "#ext:名将杀/audio/skill/mjspingyanouzhe3": "我有嘉宾，鼓瑟吹笙。",
  "#ext:名将杀/audio/skill/mjspingyanouzhe4": "我有嘉宾，鼓瑟鼓琴。",
  "#ext:名将杀/audio/skill/mjsjiafuderuosi1": "审时收锋芒，藏玉韫椟中。",
  "#ext:名将杀/audio/skill/mjsjiafuderuosi2": "同心合璧，山河永固。",
  "#ext:名将杀/audio/die/mjs_weizifu:die": "奈何未央柳老，甘泉萤稀。",
  "#ext:名将杀/audio/die/mjs_weizifu2:die": "来世愿平阳采桑，不复帝王宫阙。",

  "#ext:名将杀/audio/skill/mjssichouzhilu1": "丝帛西行，胡物东来。",
  "#ext:名将杀/audio/skill/mjssichouzhilu2": "物通有无，利泽在民。",
  "#ext:名将杀/audio/skill/mjszaokongxiyu1": "玉门之外，当有更西之西。",
  "#ext:名将杀/audio/skill/mjszaokongxiyu2": "竟以为吾持节儒生，不谙弓马乎?",
  "#ext:名将杀/audio/die/mjs_zhangqian:die": "执节没身，不屈王命。",
  "#ext:名将杀/audio/die/mjs_zhangqian2:die": "身毒未至，月氏未盟，此憾矣……",

  "#ext:名将杀/audio/skill/mjsbachubaijia1": "推明孔氏，抑黜百家。",
  "#ext:名将杀/audio/skill/mjsbachubaijia2": "罢黜百家，独尊儒术。",
  "#ext:名将杀/audio/skill/mjstianrenganying1": "德不孤，必有邻。",
  "#ext:名将杀/audio/skill/mjstianrenganying2": "一人有庆，兆民赖之。",
  "#ext:名将杀/audio/skill/mjstianrenganying3": "天人之征，古今之道也。",
  "#ext:名将杀/audio/skill/mjstianrenganying4": "天人相感，阴阳相和。",
  "#ext:名将杀/audio/skill/mjschunqiufanlu1": "循天之道，以养其身。",
  "#ext:名将杀/audio/skill/mjschunqiufanlu2": "君子察物之异，以求天意。",
  "#ext:名将杀/audio/die/mjs_dongzhongshu:die": "时来曷迟，去之速矣。",
  "#ext:名将杀/audio/die/mjs_dongzhongshu2:die": "命者天之令也……",

  "#ext:名将杀/audio/skill/mjsfeijiangshelu1": "大丈夫当如鹰隼击风，岂效狐兔藏穴!",
  "#ext:名将杀/audio/skill/mjsfeijiangshelu2": "吾骑所向，烽烟自起。",
  "#ext:名将杀/audio/skill/mjssheshibohu1": "石乎？虎乎？但贯颅耳!",
  "#ext:名将杀/audio/skill/mjssheshibohu2": "射石没羽，箭锋尤利。",
  "#ext:名将杀/audio/die/mjs_liguang:die": "广年六十徐，终不能复对刀笔之吏矣!",
  "#ext:名将杀/audio/die/mjs_liguang2:die": "部行回远，又迷失道，岂非天哉!",

  "#ext:名将杀/audio/skill/mjschushuruqin1": "楚鼎作佩，秦剑为簪。",
  "#ext:名将杀/audio/skill/mjschushuruqin2": "区区小创，安能阻我掌中局？",
  "#ext:名将杀/audio/skill/mjschushuruqin3": "楚云既散，秦日新升。",
  "#ext:名将杀/audio/skill/mjschushuruqin4": "楚水悠悠，终入秦川。",
  "#ext:名将杀/audio/skill/mjsyidingmingfeng1": "牝鸡司晨？此乃社稷自择其主。",
  "#ext:名将杀/audio/skill/mjsyidingmingfeng2": "山川归我疆域，日月入我彀中。",
  "#ext:名将杀/audio/skill/mjsyidingmingfeng3": "既入咸阳道，共擎嬴秦旗。",
  "#ext:名将杀/audio/skill/mjsyidingmingfeng4": "百川归海，经纬共织。",
  "#ext:名将杀/audio/skill/mjsquanyusigui1": "诸君剑锋，当指我所向！",
  "#ext:名将杀/audio/skill/mjsquanyusigui2": "暂借卿手，为我弋猎九州。",
  "#ext:名将杀/audio/die/mjs_mibazi:die": "三十载啸咤风云，竟败于匹夫竖子！",
  "#ext:名将杀/audio/die/mjs_mibazi2:die": "魂溯湘水去，犹唱《阳阿》归……",

  "#ext:名将杀/audio/skill/mjsqianjinmaifu1": "赋成之日，百镒黄金不为贵!",
  "#ext:名将杀/audio/skill/mjsqianjinmaifu2": "若得陛下一顾，当以金山润笔。",
  "#ext:名将杀/audio/skill/mjsjinwucangjiao1": "予我金屋者，我予其天下。",
  "#ext:名将杀/audio/skill/mjsjinwucangjiao2": "金屋藏娇时，斧钺已铮铮。",
  "#ext:名将杀/audio/die/mjs_chenajiao:die": "长门宫月，可照得见白头人。",
  "#ext:名将杀/audio/die/mjs_chenajiao2:die": "金凤之躯岂与蓬蒿同腐……",

  "#ext:名将杀/audio/skill/mjsshiyibeibian1": "世异则事异，事异则备变。",
  "#ext:名将杀/audio/skill/mjsshiyibeibian2": "君子见几而作，不俟终日。",
  "#ext:名将杀/audio/skill/mjsbuqixiugu1": "不期修古，不法常可。",
  "#ext:名将杀/audio/skill/mjsbuqixiugu2": "论世之事，因为之备。",
  "#ext:名将杀/audio/skill/mjsfabuagui1": "刑过不避大臣，赏善不遗匹夫。",
  "#ext:名将杀/audio/skill/mjsfabuagui2": "智者弗能辞，勇者弗敢争。",
  "#ext:名将杀/audio/die/mjs_hanfei:die": "吾道不孤，后世必行。",
  "#ext:名将杀/audio/die/mjs_hanfei2:die": "法如日月，岂因一人晦明?",

  "#ext:名将杀/audio/skill/mjszijianzhenxi1": "倾国色与倾国策，孰重？",
  "#ext:名将杀/audio/skill/mjszijianzhenxi2": "能擎社稷者，方为良配。",
  "#ext:名将杀/audio/skill/mjszijianzhenxi3": "吾有山河之计陪嫁。",
  "#ext:名将杀/audio/skill/mjszijianzhenxi4": "有妾为助，社稷无忧矣。",
  "#ext:名将杀/audio/skill/mjszhiyongdingqi1": "蛾眉皓齿易逝，庙堂自有千秋！",
  "#ext:名将杀/audio/skill/mjszhiyongdingqi2": "嫁与江山日，红妆换戎装。",
  "#ext:名将杀/audio/skill/mjszhiyongdingqi3": "无盐女子，亦能定国安邦。",
  "#ext:名将杀/audio/skill/mjszhiyongdingqi4": "外修诸侯之礼，内秉国家之政。",
  "#ext:名将杀/audio/die/mjs_zhongwuyan:die": "可惜未睹四海升平……",
  "#ext:名将杀/audio/die/mjs_zhongwuyan2:die": "鼓声绝时，且听民声。",

  "#ext:名将杀/audio/skill/mjsqianjinshigu1": "死马且市之五百金，况生马乎？",
  "#ext:名将杀/audio/skill/mjsqianjinshigu2": "千金非为朽骨，志在千里骏骑。",
  "#ext:名将杀/audio/skill/mjsqingziweishi1": "王诚欲兴道，隗请为天下之士开路。",
  "#ext:名将杀/audio/skill/mjsqingziweishi2": "王诚欲必致士，请从隗始。",
  "#ext:名将杀/audio/skill/mjsqingziweishi3": "隗且见事，况贤于隗者乎？",
  "#ext:名将杀/audio/skill/mjsqingziweishi4": "贤于隗者，岂远千里哉！",
  "#ext:名将杀/audio/die/mjs_guowei:die": "得遇明主，老朽此生足矣！",
  "#ext:名将杀/audio/die/mjs_guowei2:die": "愿后来者，踏吾骨，登金台……",

  "#ext:名将杀/audio/skill/mjsbaizhanwujie1": "前有千军万马，何曾后退半步？?",
  "#ext:名将杀/audio/skill/mjsbaizhanwujie2": "弓弩虽利，能挡吾辈死士乎？?",
  "#ext:名将杀/audio/skill/mjsluzhanfenghui1": "虎狼眈眈相向，吾等必枕戈待旦!",
  "#ext:名将杀/audio/skill/mjsluzhanfenghui2": "虚招诱敌，真刃在此。",
  "#ext:名将杀/audio/skill/mjsxuruizhuizhan1": "乱军之中，孰为吾刃所指？",
  "#ext:名将杀/audio/skill/mjsxuruizhuizhan2": "天命难测，且看分晓。",
  "#ext:名将杀/audio/die/mjs_baoyuan:die": "非战之罪，是天不佑……",
  "#ext:名将杀/audio/die/mjs_baoyuan2:die": "马革裹尸，亦无悔矣！",

  "#ext:名将杀/audio/skill/mjsyishuyuguo1": "法立则国强，术行则令通。",
  "#ext:名将杀/audio/skill/mjsyishuyuguo2": "独视者谓明，独听者谓聪。",
  "#ext:名将杀/audio/skill/mjschangyuwushi1": "藏于无知，匿于无为。",
  "#ext:名将杀/audio/skill/mjschangyuwushi2": "慎而言也，慎而行也。",
  "#ext:名将杀/audio/skill/mjsjuncaoqibing1": "见功而与赏，因能而受官。",
  "#ext:名将杀/audio/skill/mjsjuncaoqibing2": "君驭臣下，当如鹰隼临空。",
  "#ext:名将杀/audio/die/mjs_shenbuhai:die": "弊政未除，吾难瞑目……",
  "#ext:名将杀/audio/die/mjs_shenbuhai2:die": "此天意乎？",

  "#ext:名将杀/audio/skill/mjsxiuzhujintai1": "得贤者则安昌，失之者则危亡。",
  "#ext:名将杀/audio/skill/mjsxiuzhujintai2": "欲复强燕，非聚天下英才不可。",
  "#ext:名将杀/audio/skill/mjsxiuzhujintai3": "天下贤士，皆入金台！",
  "#ext:名将杀/audio/skill/mjsxiuzhujintai4": "英才豪杰，共襄盛举！",
  "#ext:名将杀/audio/skill/mjsxiuzhujintai5": "千金易得，一士难求！",
  "#ext:名将杀/audio/skill/mjsxiuzhujintai6": "幸得诸君，成此鸿业。",
  "#ext:名将杀/audio/skill/mjsqiangbingfaqi1": "正当秣马厉兵，积蓄实力。",
  "#ext:名将杀/audio/skill/mjsqiangbingfaqi2": "强兵利器在手，兴师只待来日。",
  "#ext:名将杀/audio/skill/mjsqiangbingfaqi3": "甲胄已利，士卒已锐！",
  "#ext:名将杀/audio/skill/mjsqiangbingfaqi4": "复国雪耻，再造强燕！",
  "#ext:名将杀/audio/die/mjs_yanzhaowang:die": "身可陨，志长存……",
  "#ext:名将杀/audio/die/mjs_yanzhaowang2:die": "天何薄于我大燕？",

  "#ext:名将杀/audio/skill/mjsgujunlianke1": "纵无援军，吾刃犹锋。",
  "#ext:名将杀/audio/skill/mjsgujunlianke2": "千里悬军，兵锋直入。",
  "#ext:名将杀/audio/skill/mjsfeikeshunmin1": "循法令，顺庶孽。",
  "#ext:名将杀/audio/skill/mjsfeikeshunmin2": "废苛政、施仁术。",
  "#ext:名将杀/audio/skill/mjsbaohuiwangshu1": "察能而授官者，成功之君也。",
  "#ext:名将杀/audio/skill/mjsbaohuiwangshu2": "论行而结交者，立名之士也。",
  "#ext:名将杀/audio/die/mjs_yueyi:die": "善作者不必善成，善始者不必善终。",
  "#ext:名将杀/audio/die/mjs_yueyi2:die": "奈何谗言惑主，大业将倾……",

  "#ext:名将杀/audio/skill/mjszhiziweibing1": "质子居外，以作驰援之备。",
  "#ext:名将杀/audio/skill/mjszhiziweibing2": "孤刃在敌，为我策应。",
  "#ext:名将杀/audio/skill/mjswuminheyoujun1": "岁亦无恙耶，民亦无恙耶？",
  "#ext:名将杀/audio/skill/mjswuminheyoujun2": "无岁则无民，无民则无君。",
  "#ext:名将杀/audio/die/mjs_zhaoweihou:die": "可无太后，不可误秋收。",
  "#ext:名将杀/audio/die/mjs_zhaoweihou2:die": "但使百姓安定，何惜一己死生。",

  "#ext:名将杀/audio/skill/mjswanbiguizhao1": "城入赵而壁留秦，城不入则壁碎矣。",
  "#ext:名将杀/audio/skill/mjswanbiguizhao2": "城不入赵境，壁不入秦宫。",
  "#ext:名将杀/audio/skill/mjsmianchizhihui1": "秦王善为秦声，请奏缶以相乐。",
  "#ext:名将杀/audio/skill/mjsmianchizhihui2": "以秦之咸阳为赵王寿。",
  "#ext:名将杀/audio/skill/mjsjiangxianghe1": "两虎共斗，其势不俱生。",
  "#ext:名将杀/audio/skill/mjsjiangxianghe2": "将相和，则国安。",
  "#ext:名将杀/audio/die/mjs_linxiangru:die": "臣尽力矣，愿山河无恙……",
  "#ext:名将杀/audio/die/mjs_linxiangru2:die": "社稷未安，此身何惜。",

  "#ext:名将杀/audio/skill/mjsfujingqingzui1": "卸尔甲胃，收尔箭囊。",
  "#ext:名将杀/audio/skill/mjsfujingqingzui2": "借尔兵戈一用。",
  "#ext:名将杀/audio/skill/mjsfujingqingzui3": "若为社稷，甘受鞭答。",
  "#ext:名将杀/audio/skill/mjsfujingqingzui4": "此身可负荆，此心照日月。",
  "#ext:名将杀/audio/skill/mjsshangnengfanfou1": "吾虽老矣，犹能饭斗米，肉十斤。",
  "#ext:名将杀/audio/skill/mjsshangnengfanfou2": "吾虽老，尚能开三石之弓。",
  "#ext:名将杀/audio/die/mjs_lianpo:die": "白首可断，旗不可倾。",
  "#ext:名将杀/audio/die/mjs_lianpo2:die": "可惜山河末复……",

  "#ext:名将杀/audio/skill/mjsyanruoshaorong1": "我坐华堂上，不必麋鹿姿。",
  "#ext:名将杀/audio/skill/mjsyanruoshaorong2": "凌霄何自名，缘木与俱生。",
  "#ext:名将杀/audio/skill/mjsguseerge1": "雉朝飞兮鸣相和，雌雄群游兮山阿。",
  "#ext:名将杀/audio/skill/mjsguseerge2": "鼓琴瑟兮清角，降嘉福兮穰穰。",
  "#ext:名将杀/audio/die/mjs_mengyao:die": "君见阶前雪，可知是棠梨落尽？",
  "#ext:名将杀/audio/die/mjs_mengyao2:die": "星夜将近，妾何处归……",

  "#ext:名将杀/audio/skill/mjszhanxiaolixin1": "爱妾虽怜，岂重于国士？",
  "#ext:名将杀/audio/skill/mjszhanxiaolixin2": "美人易得，而国士难求。",
  "#ext:名将杀/audio/skill/mjszhanxiaolixin3": "门庭若市，贵在其心。",
  "#ext:名将杀/audio/skill/mjszhanxiaolixin4": "四方豪杰，入我门庭。",
  "#ext:名将杀/audio/skill/mjslilingzhihun1": "天降膏腴数千里，不费兵甲入舆图。",
  "#ext:名将杀/audio/skill/mjslilingzhihun2": "天赐赵土，岂有不纳之理？",
  "#ext:名将杀/audio/die/mjs_pingyuanjun:die": "纵万箭加身，不向虎狼低头！",
  "#ext:名将杀/audio/die/mjs_pingyuanjun2:die": "玉山倾兮血染裘……",

  "#ext:名将杀/audio/skill/mjshezong1": "玄铁尚需千锤百炼，况人乎？",
  "#ext:名将杀/audio/skill/mjshezong2": "以锥刺股，可破倦意；以谋问天，能易命局。",
  "##ext:名将杀/audio/skill/mjsliuguoxiangyin1": "吾有六国缰绳在手！",
  "#ext:名将杀/audio/skill/mjsliuguoxiangyin2": "使我有洛阳二顷田，安能佩六国相印！",
  "#ext:名将杀/audio/skill/mjscigu1": "并立而攻，则必破矣。",
  "#ext:名将杀/audio/skill/mjscigu2": "安民之本，在于择交。",
  "#ext:名将杀/audio/die/mjs_suqin:die": "此身早许天下策，何惜骨血荐轩辕！",
  "#ext:名将杀/audio/die/mjs_suqin2:die": "裂苏秦易，裂天下难！",

  "#ext:名将杀/audio/skill/mjsyinzhangshierqu1": "灌以漳水，成为膏腴。",
  "#ext:名将杀/audio/skill/mjsyinzhangshierqu2": "凿渠十二道，沃野千里平。",
  "#ext:名将杀/audio/skill/mjshouminboku1": "王主富民，亡国富库。",
  "#ext:名将杀/audio/skill/mjshouminboku2": "与民约信，非一日之积也。",
  "#ext:名将杀/audio/skill/mjsrubaohebo1": "今投诸水中，何久不归？",
  "#ext:名将杀/audio/skill/mjsrubaohebo2": "且请大巫为河伯传话！",
  "#ext:名将杀/audio/die/mjs_ximenbao:die": "漳流不尽，民心可安……",
  "#ext:名将杀/audio/die/mjs_ximenbao2:die": "不信鬼神之人，不赖天命施予。",

  "#ext:名将杀/audio/skill/mjsshikesanqian1": "食客三千，明珠岂止一二？",
  "#ext:名将杀/audio/skill/mjsshikesanqian2": "四海之内，皆可为友。",
  "#ext:名将杀/audio/skill/mjsshikesanqian3": "市井藏龙虎，布衣画乾坤。",
  "#ext:名将杀/audio/skill/mjsshikesanqian4": "执辔迎贤，何论尊卑？",
  "#ext:名将杀/audio/skill/mjsdaofucijiang1": "虎符在此，时不我待。",
  "#ext:名将杀/audio/skill/mjsdaofucijiang2": "千斤之锤，当为吾断此大难！",
  "#ext:名将杀/audio/skill/mjsdaofucijiang3": "纵无王命，亦当仗剑而行！",
  "#ext:名将杀/audio/skill/mjsdaofucijiang4": "此符所至，三军俯首。",
  "#ext:名将杀/audio/skill/mjsweisishi1": "吾有蛰伏之士。",
  "#ext:名将杀/audio/skill/mjsweisishi2": "可设暗室之谋。",
  "#ext:名将杀/audio/skill/mjsweisishi3": "欲破强敌，岂独堂堂之阵？",
  "#ext:名将杀/audio/skill/mjsweisishi4": "非常之时，当行非常之事？",
  "#ext:名将杀/audio/die/mjs_xinlingjun:die": "独恨灯枯木朽，不见山河同晖。",
  "#ext:名将杀/audio/die/mjs_xinlingjun2:die": "醇酒可醉人，难醉凌云志……",

  "#ext:名将杀/audio/skill/mjsqiefujiuzhao1": "六国舆图裂，一符星斗移。",
  "#ext:名将杀/audio/skill/mjsqiefujiuzhao2": "兵家死生，原在方寸玲珑心。",
  "#ext:名将杀/audio/skill/mjsxianhuanshibao1": "雪仇大恩，岂可不报？",
  "#ext:名将杀/audio/skill/mjsxianhuanshibao2": "青丝裁青锋，送君入邯郸。",
  "#ext:名将杀/audio/die/mjs_ruji:die": "妾虽碎尸万段，亦何所恨？",
  "#ext:名将杀/audio/die/mjs_ruji2:die": "可惜未见春雪消融……",

  "#ext:名将杀/audio/skill/mjsyanxiugongchan1": "新花算艳，难敌风霜。",
  "#ext:名将杀/audio/skill/mjsyanxiugongchan2": "国色尚在，岂容异卉争芳？",
  "#ext:名将杀/audio/skill/mjsyinduquanshi1": "若令贤才裹足，熟为吾等筹谋？",
  "#ext:名将杀/audio/skill/mjsyinduquanshi2": "或可周旋，以缓兵锋。",
  "#ext:名将杀/audio/skill/mjsyinduquanshi3": "同舟共济，方得始终。",
  "#ext:名将杀/audio/skill/mjsyinduquanshi4": "君之力，即妾之力。",
  "#ext:名将杀/audio/die/mjs_zhengxiu:die": "深宫王权，皆是虚妄……",
  "#ext:名将杀/audio/die/mjs_zhengxiu2:die": "害我者，必遭天谴！",

  "#ext:名将杀/audio/skill/mjsqugaohegua1": "曲弥高者，其和弥寡。",
  "#ext:名将杀/audio/skill/mjsqugaohegua2": "鸟有风而鱼有鲸。",
  "#ext:名将杀/audio/skill/mjsjiubian1": "骐骥伏匿，凤凰高飞。",
  "#ext:名将杀/audio/skill/mjsjiubian2": "忠照愿见，皓日显形。",
  "#ext:名将杀/audio/die/mjs_songyu:die": "岁乎乎而道尽，恐余寿之弗将。",
  "#ext:名将杀/audio/die/mjs_songyu2:die": "白驹易逝，朝露易晞……",

  "#ext:名将杀/audio/skill/mjsyihuajiemu1": "移花接木，谁识真伪？",
  "#ext:名将杀/audio/skill/mjsyihuajiemu2": "以彼之木，成吾之华。",
  "#ext:名将杀/audio/skill/mjswuwangzhizai1": "何谓无妄之福，何谓无妄之祸？",
  "#ext:名将杀/audio/skill/mjswuwangzhizai2": "世有无妄之福，又有无妄之祸。",
  "#ext:名将杀/audio/die/mjs_chunshenjun:die": "只恨未听朱英……",
  "#ext:名将杀/audio/die/mjs_chunshenjun2:die": "黄泉..……候尔！",

  "#ext:名将杀/audio/skill/mjshuoniuzhen1": "缚刃于角，束矩于尾。",
  "#ext:名将杀/audio/skill/mjshuoniuzhen2": "不如爱惜人力，以群牛为锋。",
  "#ext:名将杀/audio/skill/mjshuoniuzhen3": "火牛夜出，燕垒必摧！",
  "#ext:名将杀/audio/skill/mjshuoniuzhen4": "火牛之威，能摧千军！",
  "#ext:名将杀/audio/skill/mjsjieqiujiuren1": "朔风裂骨，岂忍士卒单衣？",
  "#ext:名将杀/audio/skill/mjsjieqiujiuren2": "士心所向，胜得百裘！",
  "#ext:名将杀/audio/die/mjs_tiandan:die": "恨只恨，未睹山河尽复。",
  "#ext:名将杀/audio/die/mjs_tiandan2:die": "将军死国，常事耳！",

  "#ext:名将杀/audio/skill/mjsfenquanshiyi1": "千金如鹅毛，民心抵万钧。",
  "#ext:名将杀/audio/skill/mjsfenquanshiyi2": "市义何须珠玉，一炬可照肝胆。",
  "#ext:名将杀/audio/skill/mjsfenquanshiyi3": "门下无债户，民心即金匮。",
  "#ext:名将杀/audio/skill/mjsfenquanshiyi4": "焚尽锱铢债，换得万户生。",
  "#ext:名将杀/audio/skill/mjsjiaotusanku1": "一窟易覆，三窟难倾。",
  "#ext:名将杀/audio/skill/mjsjiaotusanku2": "暂借君势，必有奉还。",
  "#ext:名将杀/audio/skill/mjsjiaotusanku3": "三窟已就，可高枕而卧矣。",
  "#ext:名将杀/audio/skill/mjsjiaotusanku4": "兔尚有三窟避祸，况英雄乎？",
  "#ext:名将杀/audio/skill/mjsjiminggoudao1": "鸡鸣启函谷，韬略破重关。",
  "#ext:名将杀/audio/skill/mjsjiminggoudao2": "人可以伪恩动，则天亦可巧诈应也。",
  "#ext:名将杀/audio/skill/mjsjiminggoudao3": "吠犬开险道，鸡鸣裂重城。",
  "#ext:名将杀/audio/skill/mjsjiminggoudao4": "方寸之术，可通乾坤。",
  "#ext:名将杀/audio/die/mjs_mengchangjun:die": "山河路远，各觅青山去……",
  "#ext:名将杀/audio/die/mjs_mengchangjun2:die": "三千珠履客，终作孤鸿身。",

  "#ext:名将杀/audio/skill/mjslianheng1": "合纵之间，不敌连横之力。",
  "#ext:名将杀/audio/skill/mjslianheng2": "欲得生天，当附强者。",
  "#ext:名将杀/audio/skill/mjszhongkoushuojin1": "积羽沉舟，群轻折轴。",
  "#ext:名将杀/audio/skill/mjszhongkoushuojin2": "众口烁金，积毁销骨。",
  "#ext:名将杀/audio/skill/mjszhezhu1": "焉吾有折竹之攻，焉有有不习之术",
  "#ext:名将杀/audio/skill/mjszhezhu2": "竹刀刻纵横，笔墨画山河。",
  "#ext:名将杀/audio/die/mjs_zhangyi:die": "大争之世，本无常道。",
  "#ext:名将杀/audio/die/mjs_zhangyi2:die": "弈局劫争，落子无悔。",

  "#ext:名将杀/audio/skill/mjswuguibaixiang1": "天下智谋之士，舍我其谁？",
  "#ext:名将杀/audio/skill/mjswuguibaixiang2": "吾策所向，乾坤自定。",
  "#ext:名将杀/audio/skill/mjswuguibaixiang3": "无能者不敢当职，有能者亦不得蔽隐。",
  "#ext:名将杀/audio/skill/mjswuguibaixiang4": "有功者不得不赏，有能者不得不官。",
  "#ext:名将杀/audio/skill/mjsyuanjiaojingong1": "近者寸土必争，远者金帛以盟。",
  "#ext:名将杀/audio/skill/mjsyuanjiaojingong2": "交远以固后，攻近以拓疆！",
  "#ext:名将杀/audio/skill/mjsqingyunzhishang1": "布衣寒士至卿相，岂赖天命？",
  "#ext:名将杀/audio/skill/mjsqingyunzhishang2": "当年阶下囚，今日座上卿！",
  "#ext:名将杀/audio/die/mjs_fanju:die": "羁旅之臣，尚有何念……",
  "#ext:名将杀/audio/die/mjs_fanju2:die": "算尽诸事，仍难敌天算。",

  "#ext:名将杀/audio/skill/mjsshanyoufusu1": "成卒厂骨未寒，岂可驱民以饰边？",
  "#ext:名将杀/audio/skill/mjsshanyoufusu2": "纵逐匈奴三千里，玉宇不知闾巷寒。",
  "#ext:名将杀/audio/skill/mjsshanyoufusu3": "山有扶苏，隰有荷华。",
  "#ext:名将杀/audio/skill/mjsshanyoufusu4": "春播不误，秋收方得。",
  "#ext:名将杀/audio/skill/mjsxianwenyumin1": "他日荧惑守心，是我叩阊阖为黔首请命。",
  "#ext:名将杀/audio/skill/mjsxianwenyumin2": "若使士卒免遭屠戮，何惜此身？",
  "#ext:名将杀/audio/die/mjs_fusu:die": "他日荧惑守心，是我寇阊阖为黔首请命。",
  "#ext:名将杀/audio/die/mjs_fusu2:die": "若使士卒免遭屠戮，何惜此身。",

  "#ext:名将杀/audio/skill/mjsfanshumingfa1": "天下敢有藏诗、书、百家语者，悉烧之。",
  "#ext:名将杀/audio/skill/mjsfanshumingfa2": "偶语诗书者弃市，以古非今者族。",
  "#ext:名将杀/audio/skill/mjsjianzhizhuke1": "太山不让土壤，故能成其大。",
  "#ext:名将杀/audio/skill/mjsjianzhizhuke2": "河海不择细流，故能就其深。",
  "#ext:名将杀/audio/die/mjs_lisi:die": "物极则衰，吾未知所税价也。",
  "#ext:名将杀/audio/die/mjs_lisi2:die": "若斯之为臣者，罪足以死固久矣。",

  "#ext:名将杀/audio/skill/mjsmodaiqinwang1": "席卷天下，包举宇内。",
  "#ext:名将杀/audio/skill/mjsmodaiqinwang2": "囊括四海，并吞八荒。",
  "#ext:名将杀/audio/skill/mjsmodaiqinwang3": "昔收天下之兵，今斩木为兵者百万。",
  "#ext:名将杀/audio/skill/mjsmodaiqinwang4": "金城千里，一朝齑粉。",
  "#ext:名将杀/audio/skill/mjstuimiaozhujian1": "卧疾待斩指鹿人。",
  "#ext:名将杀/audio/skill/mjstuimiaozhujian2": "鄙刃已在匣中鸣。",
  "#ext:名将杀/audio/skill/mjstuimiaozhujian1": "万世基业，成此一击。",
  "#ext:名将杀/audio/skill/mjstuimiaozhujian2": "为诛窃鼎之徒，有何所惜。",
  "#ext:名将杀/audio/die/mjs_ziying:die": "赢氏自犬丘而兴，今复归于尘，亦天数软？",
  "#ext:名将杀/audio/die/mjs_ziying2:die": "六国烽火，已燎原矣。",

  "#ext:名将杀/audio/skill/mjsshetushoubing1": "远水不救近火，不若因地制之。",
  "#ext:名将杀/audio/skill/mjsshetushoubing2": "郦山徒多，请赦之，授兵以击之。",
  "#ext:名将杀/audio/skill/mjsxianmei1": "伏兵披甲，勒马衔枚。",
  "#ext:名将杀/audio/skill/mjsxianmei2": "衔枚蔽行，待有利之机。",
  "#ext:名将杀/audio/die/mjs_zhanghan:die": "贪夫徇财，烈士徇名。",
  "#ext:名将杀/audio/die/mjs_zhanghan2:die": "死生，命也！",

  "#ext:名将杀/audio/skill/mjsneimoufazhi1": "令则行，禁则止。",
  "#ext:名将杀/audio/skill/mjsneimoufazhi2": "法不阿贵，绳不挠曲。",
  "#ext:名将杀/audio/skill/mjszhongxin_mjs_mengyi1": "今毅之宗，世无二心。",
  "#ext:名将杀/audio/skill/mjszhongxin_mjs_mengyi2": "忠信而不谀，谏争而不谄。",
  "#ext:名将杀/audio/die/mjs_mengyi:die": "带长剑兮挟秦弓，首身离兮心不惩。",
  "#ext:名将杀/audio/die/mjs_mengyi2:die": "祷祠山川又有何益……",

  "#ext:名将杀/audio/skill/mjszhuchenshoufan1": "起临洮属之辽东，城堑万馀里。",
  "#ext:名将杀/audio/skill/mjszhuchenshoufan2": "巨龙卧野，胡马安得南窥。",
  "#ext:名将杀/audio/skill/mjszhongxin1": "今恬之宗，世无二心。",
  "#ext:名将杀/audio/skill/mjszhongxin2": "必死而守义，不敢辱先人之教。",
  "#ext:名将杀/audio/die/mjs_mengtian:die": "愿魂归长城之下，永守边疆……",
  "#ext:名将杀/audio/die/mjs_mengtian2:die": "我何罪于天，无过而死乎？",

  "#ext:名将杀/audio/skill/mjsqitianfeizhu1": "为者则己，有者则士。",
  "#ext:名将杀/audio/skill/mjsqitianfeizhu2": "天下事在我！我今为之，谁敢不从？",
  "#ext:名将杀/audio/skill/mjscangbaoumeiwu1": "积天下奇珍。",
  "#ext:名将杀/audio/skill/mjscangbaoumeiwu2": "皆入我私苑。",
  "#ext:名将杀/audio/die/mjs_dongzhuo:die": "操柄数载，终不过黄土一抔。",
  "#ext:名将杀/audio/die/mjs_dongzhuo2:die": "今虽身死，西凉铁骑犹在……",

  "#ext:名将杀/audio/skill/mjshujiashibapai1": "胡笳动兮边马鸣。",
  "#ext:名将杀/audio/skill/mjshujiashibapai2": "胡音粗砺，如何能不念中原。",
  "#ext:名将杀/audio/skill/mjsbeifenlichou1": "天不仁兮降乱离，地不仁兮使我逢此时。",
  "#ext:名将杀/audio/skill/mjsbeifenlichou2": "还顾邈冥冥，肝胆为烂腐。",
  "#ext:名将杀/audio/die/mjs_caiwenji:die": "生冀（jì）归桑梓，死当埋骨还。",
  "#ext:名将杀/audio/die/mjs_caiwenji2:die": "终于不用再漂泊流离……",

  "#ext:名将杀/audio/skill/mjsguaguliaodu1": "欲治重疾，必为常人所不敢为。",
  "#ext:名将杀/audio/skill/mjsguaguliaodu2": "痛虽在骨，但忍之，可保性命。",
  "#ext:名将杀/audio/skill/mjsqingnangmiaoshou1": "法阴阳乾坤，顺日月四时，万物生而天人合。",
  "#ext:名将杀/audio/skill/mjsqingnangmiaoshou2": "集吾平生所成，济苍生之万一。",
  "#ext:名将杀/audio/die/mjs_huatuo:die": "独眠梦魂好，人间忧愁长。",
  "#ext:名将杀/audio/die/mjs_huatuo2:die": "医者终难自医。",

  "#ext:名将杀/audio/skill/mjszhibeixicao1": "吉凶见，故善否(fǒu)著。虚实荡，故万物缠。",
  "#ext:名将杀/audio/skill/mjszhibeixicao2": "等闲施设神仙术，点悟曹瞒不转头。",
  "#ext:名将杀/audio/skill/mjsdunjiatianshu1": "腾云跨风，飞升太虚。",
  "#ext:名将杀/audio/skill/mjsdunjiatianshu2": "云游四海，藏形变身。",
  "#ext:名将杀/audio/skill/mjsfeishengtaixu1": "太虚寥廓，肇基化元，万物资始，五运终天。",
  "#ext:名将杀/audio/skill/mjsfeishengtaixu2": "游鸾凭泰虚，腾鳞托浮宵。",
  "#ext:名将杀/audio/die/mjs_zuoci:die": "生也死之徒，死也生之始。",
  "#ext:名将杀/audio/die/mjs_zuoci2:die": "大道既成!",

  "#ext:名将杀/audio/skill/mjsgeliansongmu1": "即为貂蝉倾心，何妨执戟一战？",
  "#ext:名将杀/audio/skill/mjsgeliansongmu2": "愿将军可怜妾身。",
  "#ext:名将杀/audio/skill/mjsbiyuezhizi1": "素月敛光华，星辰失颜色。",
  "#ext:名将杀/audio/skill/mjsbiyuezhizi2": "纵无皎皎月辉，亦可孤光自照。",
  "#ext:名将杀/audio/die/mjs_diaochan:die": "浮生梦短，先觉未尝不是幸事。",
  "#ext:名将杀/audio/die/mjs_diaochan2:die": "如此英雄之世，竟容不下薄命女子。",

  "#ext:名将杀/audio/skill/mjssishisangong1": "树恩四世，岂为蚍蜉（pí fú）所撼？",
  "#ext:名将杀/audio/skill/mjssishisangong2": "累世公卿，自有根基。",
  "#ext:名将杀/audio/skill/mjsbaiwanxiongbing1": "横大河之北，合四州之地。",
  "#ext:名将杀/audio/skill/mjsbaiwanxiongbing2": "收英雄之才，拥百万之众。",
  "#ext:名将杀/audio/skill/mjsfujinfengliu1": "幅巾单衣，引八百余骑。",
  "#ext:名将杀/audio/skill/mjsfujinfengliu2": "尽去王服，自成风流！",
  "#ext:名将杀/audio/die/mjs_yuanshao:die": "大丈夫愿临阵斗死，岂可入墙而望活！",
  "#ext:名将杀/audio/die/mjs_yuanshao2:die": "袁氏绝不能断送在我手中……",

  "#ext:名将杀/audio/skill/mjswushuangfeijiang1": "四海之内，唯我温侯独步！",
  "#ext:名将杀/audio/skill/mjswushuangfeijiang2": "山川草木，皆我兵刃。",
  "#ext:名将杀/audio/skill/mjswushuangfeijiang3": "量你区区小卒，也敢螳臂当车？",
  "#ext:名将杀/audio/skill/mjswushuangfeijiang4": "就凭尔等，也配与我一战？",
  "#ext:名将杀/audio/skill/mjslangziyexin1": "汉家城池，诸人有份，偏尔合得？",
  "#ext:名将杀/audio/skill/mjslangziyexin2": "向我俯首称臣，如何？",
  "#ext:名将杀/audio/skill/mjslangziyexin3": "霸业雄心吾自求之，岂为虚伪忠义所挟？",
  "#ext:名将杀/audio/skill/mjslangziyexin4": "十八路诸侯，吾视之为草芥。",
  "#ext:名将杀/audio/skill/mjsyuanmensheji1": "布平生不好斗，惟好解斗。",
  "#ext:名将杀/audio/skill/mjsyuanmensheji2": "吾箭既中，尔等即刻退兵！",
  "#ext:名将杀/audio/die/mjs_lvbu:die": "大丈夫征战沙场，何惧一死？",
  "#ext:名将杀/audio/die/mjs_lvbu2:die": "吾岂能败？到黄泉再战！",

  "#ext:名将杀/audio/skill/mjsgouhuohuming1": "大楚兴，陈胜王。",
  "#ext:名将杀/audio/skill/mjsningyouzhonghu1": "哼！王侯将相宁有种乎！",
  "#ext:名将杀/audio/skill/mjsningyouzhonghu2": "戈矛所向非秦天下，乃百千年贵胄冢也！",
  "#ext:名将杀/audio/skill/mjsjieganerqi1": "壮士不死即已，死即举大名耳！",
  "#ext:名将杀/audio/skill/mjsjieganerqi2": "斩木为兵，揭竿为旗。",
  "#ext:名将杀/audio/skill/mjsfawudao1": "伐无道，诛暴秦！",
  "#ext:名将杀/audio/die/mjs_chensheng:die": "等死，死国可乎！",
  "#ext:名将杀/audio/die/mjs_chensheng2:die": "宁鸣而死，不默而生！",

  "#ext:名将杀/audio/skill/mjsxiaozouwange1": "呜呼哀哉，逢时不祥。",
  "#ext:名将杀/audio/skill/mjsxiaozouwange2": "昊天不弔，上玄降祸。",
  "#ext:名将杀/audio/skill/mjsxuepingzhulv1": "保绥社稷，削平诸吕。",
  "#ext:名将杀/audio/skill/mjsxuepingzhulv2": "汉室不可倾，吕氏不可纵！",
  "#ext:名将杀/audio/die/mjs_zhoubo:die": "剑折尚有腰间骨！",
  "#ext:名将杀/audio/die/mjs_zhoubo2:die": "吾尝将百万军，岂料今日……",

  "#ext:名将杀/audio/skill/mjsxiandeng1": "先登陷阵，赴死严敌。",
  "#ext:名将杀/audio/skill/mjsxiandeng2": "前蒙矢石者，自能斩将搴旗。",
  "#ext:名将杀/audio/skill/mjsxiandeng3": "待重整旗鼓，必再冲阵！",
  "#ext:名将杀/audio/skill/mjspaitazhiru1": "大事急矣，岂顾得门闾之礼！",
  "#ext:名将杀/audio/skill/mjspaitazhiru2": "诚义勇者，不顾斧钺之诛。",
  "#ext:名将杀/audio/die/mjs_fankuai:die": "可恶，竟使小人得意。",
  "#ext:名将杀/audio/die/mjs_fankuai2:die": "壮士行，当尽忠死节。",

  "#ext:名将杀/audio/skill/mjsliuchuqiji1": "出奇制胜。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji2": "上兵伐谋。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji3": "间其君臣，以疑其心。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji4": "去其骨鲠，夺其藩盾。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji5": "诳楚为王，可以间出。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji6": "汉方不利，宁能禁信之王（wàng）乎？",
  "#ext:名将杀/audio/skill/mjsliuchuqiji7": "此特一力士之事耳。",
  "#ext:名将杀/audio/skill/mjsliuchuqiji8": "以利诱之，以情动之。",
  "#ext:名将杀/audio/skill/mjsguaxiweimen1": "布衣草履，不减志之高远。",
  "#ext:名将杀/audio/skill/mjsguaxiweimen2": "身居陋室，心怀天下。",
  "#ext:名将杀/audio/die/mjs_chenping:die": "终不能复起，以吾多阴祸也。",
  "#ext:名将杀/audio/die/mjs_chenping2:die": "大汉功业已历三世，吾事毕矣。",

  "#ext:名将杀/audio/skill/mjsshimianmaifu1": "伏兵十队，使做困兽之斗。",
  "#ext:名将杀/audio/skill/mjsshimianmaifu2": "以利动之，以卒待之。",
  "#ext:名将杀/audio/skill/mjsbeishuiyizhan1": "陷之死地而后生，置之亡地而后存。",
  "#ext:名将杀/audio/skill/mjsbeishuiyizhan2": "及其锋而用之。",
  "#ext:名将杀/audio/skill/mjsdengtanbaijiang1": "壮士精兵，入我麾下！",
  "#ext:名将杀/audio/skill/mjsdengtanbaijiang2": "拜将非荣，用兵唯实。",
  "#ext:名将杀/audio/die/mjs_hanxin:die": "功高震主，终须一死。",
  "#ext:名将杀/audio/die/mjs_hanxin2:die": "天下已定，我固当烹。",

  "#ext:名将杀/audio/skill/mjszhansheqiyi1": "未诛秦时鹿，先斩沛中蛇。",
  "#ext:名将杀/audio/skill/mjszhansheqiyi2": "四海横行无立草，妖蛇那得阻前驱。",
  "#ext:名将杀/audio/skill/mjszhansheqiyi3": "随我共图大业！",
  "#ext:名将杀/audio/skill/mjszhansheqiyi4": "壮士行，何畏！",
  "#ext:名将杀/audio/skill/mjsdafengge1": "大风起兮云飞扬!",
  "#ext:名将杀/audio/skill/mjsdafengge2": "按剑清八极，归酣歌大风。",
  "#ext:名将杀/audio/skill/mjsdafengge3": "安得猛士兮守四方！",
  "#ext:名将杀/audio/skill/mjsdafengge4": "羽翮（hé）已就，横绝四海！",
  "#ext:名将杀/audio/skill/mjsyuefasanzhang1": "杀人者死，伤人及盗抵罪。",
  "#ext:名将杀/audio/skill/mjsyuefasanzhang2": "杀人者死，伤人者刑。",
  "#ext:名将杀/audio/die/mjs_liubang:die": "命乃在天，虽扁鹊何益！",
  "#ext:名将杀/audio/die/mjs_liubang2:die": "游子悲故乡，万岁后吾魂魄犹乐思沛。",

  "#ext:名将杀/audio/skill/mjslinchaochengzhi1": "诸卿浮沉、荣辱，皆在我掌中。",
  "#ext:名将杀/audio/skill/mjslinchaochengzhi2": "翻覆风云，整饬（chì）山河。",
  "#ext:名将杀/audio/skill/mjszhulvweiwang1": "社稷江山，皆冠我姓。",
  "#ext:名将杀/audio/skill/mjszhulvweiwang2": "若无吕家，何来汉室天下？",
  "#ext:名将杀/audio/die/mjs_lvzhi:die": "可惜这天下，无法再守了……",
  "#ext:名将杀/audio/die/mjs_lvzhi2:die": "不过区区苍犬……（疼痛呻吟）",

  "#ext:名将杀/audio/skill/mjsjuxianweijiang1": "有力者疾以助人，有道者劝以教人。",
  "#ext:名将杀/audio/skill/mjsjuxianweijiang2": "君子成人之美。",
  "#ext:名将杀/audio/skill/mjsjizhaoyouzhu1": "忧患生于所忽，祸起于细微。",
  "#ext:名将杀/audio/skill/mjsjizhaoyouzhu2": "阻其图，夺其虑，乘其惧。",
  "#ext:名将杀/audio/die/mjs_xiaohe:die": "功未成，已作枯骨……",
  "#ext:名将杀/audio/die/mjs_xiaohe2:die": "社稷安危，又待托付何人？",

  "#ext:名将杀/audio/skill/mjsbolangzhuiqin1": "天不佑秦，此椎当为天下先！",
  "#ext:名将杀/audio/skill/mjsbolangzhuiqin2": "铸重椎以破暴秦。",
  "#ext:名将杀/audio/skill/mjsyunchouweiwo1": "不如因而立之，使自为守。",
  "#ext:名将杀/audio/skill/mjsyunchouweiwo2": "臣请借前箸而筹之。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu1": "天道自然，故图书自成。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu2": "自然之化，固疑难知，外若有为，内实自然。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu3": "按名督实，选才考能。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu4": "无取天下者，天下利之。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu5": "惊乱其军而疾击之，可以横行。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu6": "白刃始合，士争先赴。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu7": "发我车骑，冲其左右。",
  "#ext:名将杀/audio/skill/mjsyiqiaoshoushu8": "变见则击之，敌人必败。",
  "#ext:名将杀/audio/die/mjs_zhangliang:die": "身归黄土，魂入九州，已无憾矣。",
  "#ext:名将杀/audio/die/mjs_zhangliang2:die": "权位何可贪，不如逍遥去。",

  "#ext:名将杀/audio/skill/mjsjiangmenlichu1": "借楚帜以聚人心。",
  "#ext:名将杀/audio/skill/mjsjiangmenlichu2": "立楚为王，某自掌兵符可矣。",
  "#ext:名将杀/audio/skill/mjsxianfazhiren1": "先发制人，后发制于人。",
  "#ext:名将杀/audio/skill/mjsxianfazhiren2": "先即制人，后则为人所制。",
  "#ext:名将杀/audio/skill/mjsxianfazhiren3": "今枭首举帜，乃天授时也！",
  "#ext:名将杀/audio/skill/mjsxianfazhiren4": "据仓廪，铸兵甲，以应天下！",
  "#ext:名将杀/audio/die/mjs_xiangliang:die": "为将者当知天时！",
  "#ext:名将杀/audio/die/mjs_xiangliang2:die": "不该大意轻敌……",

  "#ext:名将杀/audio/skill/mjsyinuoqianjin1": "得黄金百斤，不如季布一诺。",
  "#ext:名将杀/audio/skill/mjsyinuoqianjin2": "布衣一诺九鼎重，公侯千金鸿毛轻。",
  "#ext:名将杀/audio/skill/mjsyinuoqianjin3": "重诺不许无义之人。",
  "#ext:名将杀/audio/skill/mjsyinuoqianjin4": "吾非市恩贾（gǔ）义之徒。",
  "#ext:名将杀/audio/skill/mjsweiqirenxia1": "非敢矜勇，唯守义耳！",
  "#ext:名将杀/audio/skill/mjsweiqirenxia2": "侠之大者，为国为民。",
  "#ext:名将杀/audio/die/mjs_jibu:die": "丈夫在世，俯仰皆战场。",
  "#ext:名将杀/audio/die/mjs_jibu2:die": "天下创痍未瘳，布焉能独全？",

  "#ext:名将杀/audio/skill/mjswangqinbichu1": "楚虽三户，亡秦必楚。",
  "#ext:名将杀/audio/skill/mjswangqinbichu2": "秦之天下，必归于楚。",
  "#ext:名将杀/audio/skill/mjshongmenyan1": "宴启，请诸君入席。",
  "#ext:名将杀/audio/skill/mjshongmenyan2": "江山焉能分秋色，决计鸿门一会间。",
  "#ext:名将杀/audio/skill/mjshongmenyan3": "竖子不足与谋！",
  "#ext:名将杀/audio/die/mjs_fanzeng:die": "天下事大定矣……",
  "#ext:名将杀/audio/die/mjs_fanzeng2:die": "愿赐骸骨归卒伍！",

  "#ext:名将杀/audio/skill/mjszhongyongshiwu1": "不舍小伤，何以得胜机？",
  "#ext:名将杀/audio/skill/mjszhongyongshiwu2": "当以身为盾，以血为锋。",
  "#ext:名将杀/audio/skill/mjsanyingzhulei1": "养精蓄锐，待时而动。",
  "#ext:名将杀/audio/skill/mjsanyingzhulei2": "战事劳顿久矣，不如生火造饭，饱食安眠。",
  "#ext:名将杀/audio/skill/mjsanyingzhulei3": "江东子弟，岂畏豺狼之阵？",
  "#ext:名将杀/audio/skill/mjsanyingzhulei4": "吾身所向，千军辟易！",
  "#ext:名将杀/audio/die/mjs_longqie:die": "生死须臾，亦不足惧！",
  "#ext:名将杀/audio/die/mjs_longqie2:die": "然未竟之业，未酬之志，如何了结……",

  "#ext:名将杀/audio/skill/mjspofuchenzhou1": "破釜沉舟，百二秦关终属楚。",
  "#ext:名将杀/audio/skill/mjspofuchenzhou2": "今以必死之心，求破敌之功。",
  "#ext:名将杀/audio/skill/mjsbawang1": "始皇又如何。彼可取而代也！",
  "#ext:名将杀/audio/skill/mjsbawang2": "吾历七十余战，未尝败北。",
  "#ext:名将杀/audio/die/mjs_xiangyu:die": "骓不逝兮可奈何！",
  "#ext:名将杀/audio/die/mjs_xiangyu2:die": "（咳嗽声）天之亡我，我何渡为！",

  "#ext:名将杀/audio/skill/mjsgongguanzhuhou1": "吾有彪炳功业，虽诸侯不能及。",
  "#ext:名将杀/audio/skill/mjsgongguanzhuhou2": "计功而行赏，程能而授事。",
  "#ext:名将杀/audio/skill/mjsdaxiguowang1": "哈哈哈哈哈甚合吾意！",
  "#ext:名将杀/audio/skill/mjsdaxiguowang2": "据有先机，更胜所愿。",
  "#ext:名将杀/audio/die/mjs_yingbu:die": "总好过烹而醢(hǎi)之……",
  "#ext:名将杀/audio/die/mjs_yingbu2:die": "欲为帝王，何错之有？",

  "#ext:名将杀/audio/skill/mjsmeiren1": "美人从来配英雄。",
  "#ext:名将杀/audio/skill/mjsmeiren2": "死生契阔，与子成说。",
  "#ext:名将杀/audio/skill/mjsmeiren3": "多谢相救。",
  "#ext:名将杀/audio/skill/mjsmeiren4": "有劳将军。",
  "#ext:名将杀/audio/skill/mjsmeiren5": "相濡以沫，死生相随。",
  "#ext:名将杀/audio/skill/mjsmeiren6": "乱世相携，还（huán）报君恩。",
  "#ext:名将杀/audio/skill/mjsbawangbieji1": "此去经年，永矢弗谖（xuān）。",
  "#ext:名将杀/audio/skill/mjsbawangbieji2": "替我看看安稳盛世……",
  "#ext:名将杀/audio/die/mjs_yuji:die": "大王意气尽，贱妾何聊生！",
  "#ext:名将杀/audio/die/mjs_yuji2:die": "这便是我的终曲吗？",

  "#ext:名将杀/audio/skill/mjsfeilianshi1": "此乃一石二鸟之器。",
  "#ext:名将杀/audio/skill/mjsfeilianshi2": "一矢贯双雕，何人敢直撄吾锋！",
  "#ext:名将杀/audio/skill/mjsfeilianshi3": "惜哉，此良弓矢。",
  "#ext:名将杀/audio/skill/mjsgugengzhichen1": "股肱良哉，庶事康哉！",
  "#ext:名将杀/audio/skill/mjsgugengzhichen2": "必穷智竭力，以匡天下。",
  "#ext:名将杀/audio/die/mjs_zhonglimo:die": "死生穷达，天命难违矣！",
  "#ext:名将杀/audio/die/mjs_zhonglimo2:die": "一子着错，满盘皆输。",

  "#ext:名将杀/audio/skill/mjserhujingshi1": "一山岂容二虎?",
  "#ext:名将杀/audio/skill/mjserhujingshi2": "二虎相争，必有一伤。",
  "#ext:名将杀/audio/skill/mjsquhutunlang1": "先使二兽相斗。",
  "#ext:名将杀/audio/skill/mjsquhutunlang2": "两边相并，必生异心。",
  "#ext:名将杀/audio/skill/mjsquhutunlang3": "驱虎入林，吞狼于野。",
  "#ext:名将杀/audio/skill/mjsquhutunlang4": "驱凶猛之辈，吞狡黠（xiá）之属。",
  "#ext:名将杀/audio/skill/mjsxunlingliuxiang1": "秉忠贞之诚，守退让之实。",
  "#ext:名将杀/audio/skill/mjsxunlingliuxiang2": "秉忠贞之志，守谦退之节。",
  "#ext:名将杀/audio/die/mjs_xunyu:die": "死亦全节，汉祚（zuò）永续！",
  "#ext:名将杀/audio/die/mjs_xunyu2:die": "一生穷智竭力，竟逆汉室而行……",

  "#ext:名将杀/audio/skill/mjstianbufuwo1": "乱世何来君子，唯有英雄耳！",
  "#ext:名将杀/audio/skill/mjstianbufuwo2": "天下英雄，唯使君与操耳！",
  "#ext:名将杀/audio/skill/mjstianbufuwo3": "宁教我负天下人，休教天下人负我！",
  "#ext:名将杀/audio/skill/mjstianbufuwo4": "吾任天下之智力，以道御之，无所不可。",
  "#ext:名将杀/audio/skill/mjstianbufuwo5": "智者为吾算筹，豪杰为吾鹰犬。",
  "#ext:名将杀/audio/skill/mjstianbufuwo6": "天下攘攘，唯力可匡！",
  "#ext:名将杀/audio/skill/mjsxietianyiling1": "群雄何在？为我擒拿逆贼！",
  "#ext:名将杀/audio/skill/mjsxietianyiling2": "设使国家无有孤，不知当几人称帝，几人称王。",
  "#ext:名将杀/audio/skill/mjstianxiaguixin1": "周公吐哺，天下归心！",
  "#ext:名将杀/audio/skill/mjstianxiaguixin2": "吾有周公之心，可驱天下之士。",
  "#ext:名将杀/audio/die/mjs_caocao:die": "虽未竟一统，然志在千里，功在千秋。",
  "#ext:名将杀/audio/die/mjs_caocao2:die": "神龟虽寿，犹有竟时。腾蛇乘雾，终为土灰……",

  "#ext:名将杀/audio/skill/mjsguzhielai1": "啊……",
  "#ext:名将杀/audio/skill/mjsguzhielai2": "踏石留痕，气彻长虹！",
  "#ext:名将杀/audio/skill/mjsguzhielai3": "生捕咒虎，指画杀人!",
  "#ext:名将杀/audio/skill/mjsguzhielai4": "以万钓之力，护主公周全！",
  "#ext:名将杀/audio/skill/mjszhuhuguojian1": "深涧险谷，吾如履平地。",
  "#ext:名将杀/audio/skill/mjszhuhuguojian2": "气势压雷霆，迅猛追疾风。",
  "#ext:名将杀/audio/skill/mjszhuhuguojian3": "鞭驰骏骑，龙腾逍遥。",
  "#ext:名将杀/audio/skill/mjszhuhuguojian4": "虎啸山林，也要退避三舍。",
  "#ext:名将杀/audio/die/mjs_dianwei:die": "身为武夫，何惧生死！",
  "#ext:名将杀/audio/die/mjs_dianwei2:die": "沙场本就是吾之归宿。",

  "#ext:名将杀/audio/skill/mjsshishengshibai1": "谋断之间，先机已定，胜负已分。",
  "#ext:名将杀/audio/skill/mjsshishengshibai2": "谋智铸兵甲，经史砺锋刃。",
  "#ext:名将杀/audio/skill/mjsshishengshibai3": "乘其无备，卒然击之，必可破也。",
  "#ext:名将杀/audio/skill/mjsshishengshibai4": "世事云谲波诡，伪强者不足为惧。",
  "#ext:名将杀/audio/skill/mjstianduyingcai1": "某有一计，胜于二十万师。",
  "#ext:名将杀/audio/skill/mjstianduyingcai2": "便有功过毁誉，嘉意自若。",
  "#ext:名将杀/audio/skill/mjstianduyingcai3": "安危之机，不可不察。",
  "#ext:名将杀/audio/skill/mjstianduyingcai4": "皓月照夜，忽遭云蔽，天妒其光。",
  "#ext:名将杀/audio/skill/mjsyicepingliao1": "尚有一计可助丞相。",
  "#ext:名将杀/audio/skill/mjsyicepingliao2": "辽东事定矣！",
  "#ext:名将杀/audio/die/mjs_guojia:die": "某感丞相大恩，虽死不能报万一。",
  "#ext:名将杀/audio/die/mjs_guojia2:die": "吾料天下诸般，终不能与天命相搏。",

  "#ext:名将杀/audio/skill/mjslangguyingshi1": "匿于暗处静待时机。",
  "#ext:名将杀/audio/skill/mjslangguyingshi2": "死士伏待，如利剑在鞘。",
  "#ext:名将杀/audio/skill/mjslangguyingshi3": "孤狼四顾，饥鹰盘桓。",
  "#ext:名将杀/audio/skill/mjsren1": "为人者，有大度成大器。",
  "#ext:名将杀/audio/skill/mjsren2": "处世之道，应变之术，岂可偏执一端？",
  "#ext:名将杀/audio/die/mjs_simayi:die": "天不假年，时也，命也。",
  "#ext:名将杀/audio/die/mjs_simayi2:die": "但以朽迈之躯，筑我天下基业。",

  "#ext:名将杀/audio/skill/mjshuchi1": "……可恶！",
  "#ext:名将杀/audio/skill/mjshuchi2": "出阵与我一战！",
  "#ext:名将杀/audio/skill/mjsxiejiahanzhan1": "衣衫甲胃，皆为冗赘。",
  "#ext:名将杀/audio/skill/mjsxiejiahanzhan2": "不如卸甲解衣，屡战数场！",
  "#ext:名将杀/audio/die/mjs_xuchu:die": "……吾等千生万死，身冒血战，竟至这般",
  "#ext:名将杀/audio/die/mjs_xuchu2:die": "某誓与死战！",

  "#ext:名将杀/audio/skill/mjsxiaoyaozhiti1": "江东十万，吾亦来去自如。",
  "#ext:名将杀/audio/skill/mjsxiaoyaozhiti2": "铁骑踏江东，小儿岂敢啼？",
  "#ext:名将杀/audio/skill/mjsbailangchihui1": "主公授麾，勇者得前耳！",
  "#ext:名将杀/audio/skill/mjsbailangchihui2": "望麾而进，不闻令而擅前后左右者斩。",
  "#ext:名将杀/audio/die/mjs_zhangliao:die": "死则死耳，何惧之有！",
  "#ext:名将杀/audio/die/mjs_zhangliao2:die": "今虽就死，死得其所！",

  "#ext:名将杀/audio/skill/mjspianruojinghong1": "翩若惊鸿，婉若游龙。",
  "#ext:名将杀/audio/skill/mjspianruojinghong2": "披罗衣之璀璨，珥瑶碧之华琚。",
  "#ext:名将杀/audio/skill/mjsluoshenfu1": "漾洛水之微波，通诚素而先达",
  "#ext:名将杀/audio/skill/mjsluoshenfu2": "洛灵感焉，神光离合。",
  "#ext:名将杀/audio/die/mjs_zhenfu:die": "念君去我时，独愁常苦悲。",
  "#ext:名将杀/audio/die/mjs_zhenfu2:die": "与其生离，莫若死别。",

  "#ext:名将杀/audio/skill/mjsbaodaoweilao1": "取我刀来!",
  "#ext:名将杀/audio/skill/mjsbaodaoweilao2": "再拭刀锋！",
  "#ext:名将杀/audio/skill/mjsbaodaoweilao3": "看吾斩将，老也不老！",
  "#ext:名将杀/audio/skill/mjsbaodaoweilao4": "汝说吾老，敢与我比试武艺么？",
  "#ext:名将杀/audio/skill/mjsbaibuchuanyang1": "去柳叶百步而穿之，百发百中。",
  "#ext:名将杀/audio/skill/mjsbaibuchuanyang2": "百步之外，不偏毫厘。",
  "#ext:名将杀/audio/skill/mjsjiaobingzhiji1": "当一鼓作气，勿失良机。",
  "#ext:名将杀/audio/skill/mjsjiaobingzhiji2": "奉不可失，敌不可纵。",
  "#ext:名将杀/audio/die/mjs_huangzhong:die": "久不上阵，故有此失。",
  "#ext:名将杀/audio/die/mjs_huangzhong2:die": "臣今年七十有五，寿亦足矣。",

  "#ext:名将杀/audio/skill/mjsweixianweide1": "举大事者，必以人为本。",
  "#ext:名将杀/audio/skill/mjsweixianweide2": "惟贤惟德，能服于人。",
  "#ext:名将杀/audio/skill/mjssangumaolu1": "逐鹿之势，惟贤者能挽天助。",
  "#ext:名将杀/audio/skill/mjssangumaolu2": "汉祚虽危，德在生民。",
  "#ext:名将杀/audio/skill/mjsxiemindujiang1": "同心协力，救困扶危。",
  "#ext:名将杀/audio/skill/mjsxiemindujiang2": "单丝不成线，独木难成林。",
  "#ext:名将杀/audio/die/mjs_liubei:die": "宁可马革裹尸，不忍髀里肉生。",
  "#ext:名将杀/audio/die/mjs_liubei2:die": "可惜汉室之业未尽。",

  "#ext:名将杀/audio/skill/mjsliangzhoutieji1": "朔风掣长缨，铁马踏冰河。",
  "#ext:名将杀/audio/skill/mjsliangzhoutieji2": "银盔照白夜，铁骑荡沧溟。",
  "#ext:名将杀/audio/skill/mjsliangzhoutieji3": "纵无良驹，却有精兵。",
  "#ext:名将杀/audio/skill/mjsliangzhoutieji4": "壮士精兵尽归麾下！",
  "#ext:名将杀/audio/skill/mjsjinshizi1": "锦衣不夜行。",
  "#ext:名将杀/audio/skill/mjsjinshizi2": "锦绣河山，当有锦绣之才。",
  "#ext:名将杀/audio/die/mjs_machao:die": "不知魂归何处……",
  "#ext:名将杀/audio/die/mjs_machao2:die": "战鼓噤声，悲哉！痛哉！",

  "#ext:名将杀/audio/skill/mjsxiaojiniangniang1": "腰间白羽箭，东风为张弓。",
  "#ext:名将杀/audio/skill/mjsxiaojiniangniang2": "擂鼓鸣金皆梦呓，烽烟翻覆绕指柔。",
  "#ext:名将杀/audio/skill/mjsxiaojiniangniang3": "山河破碎，焉能闺中红妆。",
  "#ext:名将杀/audio/skill/mjsxiaojiniangniang4": "我江东女子，绝非孱弱娇嗔之辈。",
  "#ext:名将杀/audio/skill/mjsxiaojiniangniang5": "策马上阵，不输男儿。",
  "#ext:名将杀/audio/skill/mjsxiaojiniangniang6": "大丈夫之志，应如长江东奔大海。",
  "#ext:名将杀/audio/skill/mjsdaojianqingyuan1": "终身所约，永结为好。",
  "#ext:名将杀/audio/skill/mjsdaojianqingyuan2": "玄铁为琴，青锋做谱，与君和鸣。",
  "#ext:名将杀/audio/die/mjs_sunshangxiang:die": "枕戈寝甲多年，战死亦是巾帼豪杰！",
  "#ext:名将杀/audio/die/mjs_sunshangxiang2:die": "愿化清风细雨，早日魂归江东……",

  "#ext:名将杀/audio/skill/mjswanrendi1": "当立不世之功!",
  "#ext:名将杀/audio/skill/mjswanrendi2": "誓死不回!",
  "#ext:名将杀/audio/skill/mjsheduandangyang1": "谁敢与我决一死战？",
  "#ext:名将杀/audio/skill/mjsheduandangyang2": "桥既可断，更况尔首！",
  "#ext:名将杀/audio/skill/mjsshijiuruming1": "拿酒来!",
  "#ext:名将杀/audio/skill/mjsshijiuruming2": "厮杀汉如何不饮酒？",
  "#ext:名将杀/audio/die/mjs_zhangfei:die": "哈哈哈哈哈哈，死又何惧！",
  "#ext:名将杀/audio/die/mjs_zhangfei2:die": "痛快！只恨不能多杀几个！",

  "#ext:名将杀/audio/skill/mjsqiangchurulong1": "乘龙兮辚辚，高驰兮冲天。",
  "#ext:名将杀/audio/skill/mjsqiangchurulong2": "潜龙出渊，枪啸龙吟。",
  "#ext:名将杀/audio/skill/mjshunshenshidan1": "孤身纵马何所惧，赤血肝胆照乾坤。",
  "#ext:名将杀/audio/skill/mjshunshenshidan2": "绝处逢生，再易攻守之势。",
  "#ext:名将杀/audio/skill/mjshunshenshidan3": "马蹄惊雷处，把酒酹东风。",
  "#ext:名将杀/audio/skill/mjshunshenshidan4": "攻乃守之上策。",
  "#ext:名将杀/audio/skill/mjsqijinqichu1": "七进七出，吾志不移。",
  "#ext:名将杀/audio/skill/mjsqijinqichu2": "血未尽，战不休！",
  "#ext:名将杀/audio/die/mjs_zhaoyun:die": "臣之忠义如泰山，奈何性命若鸿毛。",
  "#ext:名将杀/audio/die/mjs_zhaoyun2:die": "今朝身陨，不能再护主尽忠……",

  "#ext:名将杀/audio/skill/mjsqimendunjia1": "窥幽微之道，启众妙之门。",
  "#ext:名将杀/audio/skill/mjsqimendunjia2": "观乎天文，以察时变。",
  "#ext:名将杀/audio/skill/mjsqimendunjia3": "与天地合其德，与日月合其明。",
  "#ext:名将杀/audio/skill/mjsqimendunjia4": "天地作棋局，万物可为兵。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji1": "心藏九州经纬，手握乾坤奥秘。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji2": "斡旋天地，补缀乾坤。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji3": "见机而变，决不有误。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji4": "重雾迷江，万箭自投。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji5": "呼风唤雨，役鬼驱神。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji6": "以奇乱正，伏兵待命。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji7": "欲擒故纵，更战心服。",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji8": "藏火于谷，烈焰伺兵。 ",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji9": "登楼鸣琴，虚实相生。 ",
  "#ext:名将杀/audio/skill/mjsjinnangmiaoji10": "借不能用者而用之。",
  "#ext:名将杀/audio/die/mjs_zhugeliang:die": "鞠躬尽瘁，死而后已！",
  "#ext:名将杀/audio/die/mjs_zhugeliang2:die": "此身已付苍生，青山白骨无悔。",

  "#ext:名将杀/audio/skill/mjswanjunqushou1": "篡汉鼠辈，尽在吾刀下！",
  "#ext:名将杀/audio/skill/mjswanjunqushou2": "某虽不才，愿去万军中取其首级！",
  "#ext:名将杀/audio/skill/mjswushengyijue1": "酒且斟下，某去便来。",
  "#ext:名将杀/audio/skill/mjswushengyijue2": "龙潭虎穴吾自来去，何须鏖兵！",
  "#ext:名将杀/audio/skill/mjsshuiyanqijun1": "水伯天吴，助我忠义之师！",
  "#ext:名将杀/audio/skill/mjsshuiyanqijun2": "广布润泽，辅佐雷公！",
  "#ext:名将杀/audio/skill/mjsshuiyanqijun3": "汉水滔天，尔等已无归路！",
  "#ext:名将杀/audio/skill/mjsshuiyanqijun4": "教尔等知我江汉之威！",
  "#ext:名将杀/audio/die/mjs_guanyu:die": "胜负兵家之常，何可自隳其志！",
  "#ext:名将杀/audio/die/mjs_guanyu2:die": "今日马革裹尸，不枉男儿九尺之躯。",

  "#ext:名将杀/audio/skill/mjsqiushuiyiren1": "妾生如此世，国色有谁怜？",
  "#ext:名将杀/audio/skill/mjsqiushuiyiren2": "薄命空负倾国色，孤影独对镜中寒。",
  "#ext:名将杀/audio/skill/mjsqiushuiyiren3": "那便仰仗将军了。",
  "#ext:名将杀/audio/skill/mjsqiushuiyiren4": "多谢怜爱。",
  "#ext:名将杀/audio/skill/mjsjunshengbieli1": "思君令人老，岁月忽已晚。",
  "#ext:名将杀/audio/skill/mjsjunshengbieli2": "行行重行行，与君生别离。",
  "#ext:名将杀/audio/die/mjs_daqiao:die": "终于可以长夜安眠……",
  "#ext:名将杀/audio/die/mjs_daqiao2:die": "于嗟阔兮，不我活兮。",

  "#ext:名将杀/audio/skill/mjsbairenyexi1": "只须百骑，便可破敌，何必三千？",
  "#ext:名将杀/audio/skill/mjsbairenyexi2": "我为上将，且不惜命，汝等何得迟疑！",
  "#ext:名将杀/audio/skill/mjsjinfanyouxia1": "上等绮缎布帛，正宜制帆。",
  "#ext:名将杀/audio/skill/mjsjinfanyouxia2": "江波之上，任我遨游！",
  "#ext:名将杀/audio/die/mjs_ganning:die": "只要江东之水奔流，帆倾舟沉又何妨？",
  "#ext:名将杀/audio/die/mjs_ganning2:die": "当年少年群聚，虎士千余，今又何在……",

  "#ext:名将杀/audio/skill/mjszhiqunxiangzeng1": "筑仓廪(lǐn)以备饥馑之患。",
  "#ext:名将杀/audio/skill/mjszhiqunxiangzeng2": "仓廪(lǐn)实而天下安。",
  "#ext:名将杀/audio/skill/mjszhiqunxiangzeng3": "千金散尽不足惜！",
  "#ext:名将杀/audio/skill/mjszhiqunxiangzeng4": "开仓与友，以济困厄。",
  "#ext:名将杀/audio/skill/mjsjiezhoudimeng1": "协心齐同，与结盟好。",
  "#ext:名将杀/audio/skill/mjsjiezhoudimeng2": "戮力一心，分灾共庆。",
  "#ext:名将杀/audio/die/mjs_lusu:die": "一生忠直，虽死何憾。",
  "#ext:名将杀/audio/die/mjs_lusu2:die": "吾似闻江东昌盛喧哗之声……",

  "#ext:名将杀/audio/skill/mjshuopolianying1": "今出其不意，自可擒制。",
  "#ext:名将杀/audio/skill/mjshuopolianying2": "吾已晓破之之术。",
  "#ext:名将杀/audio/skill/mjsjieyigongwu1": "裙帽金环带，鼯裘赠书生。",
  "#ext:名将杀/audio/skill/mjsjieyigongwu2": "锦衣貂裘不足为意。",
  "#ext:名将杀/audio/die/mjs_luxun:die": "戎马一生，竟落得这般……",
  "#ext:名将杀/audio/die/mjs_luxun2:die": "朽迈之躯，死复何恨。",

  "#ext:名将杀/audio/skill/mjshujuyingyang1": "鼠辈安敢与吾相等！",
  "#ext:名将杀/audio/skill/mjshujuyingyang2": "神人佑我，吾何惧焉！",
  "#ext:名将杀/audio/skill/mjsxiaobawang1": "方今天下风翻云涌，舍我其谁？",
  "#ext:名将杀/audio/skill/mjsxiaobawang2": "我若怕你，非孙伯符也！",
  "#ext:名将杀/audio/skill/mjsxiaobawang3": "吾今到此，你如何不降?",
  "#ext:名将杀/audio/skill/mjsxiaobawang4": "此丈夫之志也。",
  "#ext:名将杀/audio/die/mjs_sunce:die": "吾命在天，非妖人为祸。",
  "#ext:名将杀/audio/die/mjs_sunce2:die": "面如此，尚可复建功立事乎……",

  "#ext:名将杀/audio/skill/mjschengmashehu1": "何须避猛虎，跨马取肝胆。",
  "#ext:名将杀/audio/skill/mjschengmashehu2": "轻骑利箭在孤，可搏白额将军。",
  "#ext:名将杀/audio/skill/mjschengmashehu3": "（射箭声）",
  "#ext:名将杀/audio/skill/mjschengmashehu4": "正合孤意！",
  "#ext:名将杀/audio/skill/mjsquanxuelishi1": "存不忘亡，安必虑危。",
  "#ext:名将杀/audio/skill/mjsquanxuelishi2": "见微知著，睹始知终。",
  "#ext:名将杀/audio/skill/mjsquanxuelishi3": "共定大业，整齐天下。",
  "#ext:名将杀/audio/skill/mjsquanxuelishi4": "将与勠力，共定海内。",
  "#ext:名将杀/audio/die/mjs_sunquan:die": "举贤任能，以保江东，无负兄长之托。",
  "#ext:名将杀/audio/die/mjs_sunquan2:die": "雄图未竟，天命忽至……",

  "#ext:名将杀/audio/skill/mjsbingdifurong1": "池生双芙蓉，发绾同心结。",
  "#ext:名将杀/audio/skill/mjsbingdifurong2": "琴瑟在御，鸾凤和鸣。",
  "#ext:名将杀/audio/skill/mjsbingdifurong3": "清梦连根蒂，叶下宿鸳鸯。",
  "#ext:名将杀/audio/skill/mjsbingdifurong4": "秋水藏眉宇，灵思绕指尖。",
  "#ext:名将杀/audio/skill/mjstaozhiyaoyao1": "桃之夭夭，灼灼其华。",
  "#ext:名将杀/audio/skill/mjstaozhiyaoyao2": "春华初茂，应时逢君。",
  "#ext:名将杀/audio/die/mjs_xiaoqiao:die": "花开花落不过寻常事……",
  "#ext:名将杀/audio/die/mjs_xiaoqiao2:die": "宿命难违，生死亦在其中。",

  "#ext:名将杀/audio/skill/mjsxiongziyingfa1": "上窥青天，下潜黄泉，挥斥八极，卫我吴疆。",
  "#ext:名将杀/audio/skill/mjsxiongziyingfa2": "交兵不假挥长剑，已挫英雄百万师。",
  "#ext:名将杀/audio/skill/mjsfanjianchuhuan1": "比之自内，不自失也。",
  "#ext:名将杀/audio/skill/mjsfanjianchuhuan2": "间者，使敌自相疑忌也。",
  "#ext:名将杀/audio/skill/mjsfanjianchuhuan3": "反间计，疑中之疑。",
  "#ext:名将杀/audio/skill/mjsfanjianchuhuan4": "反间者，因其敌间而用之。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi1": "东风不与，为之奈何。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi2": "天时不可违，也罢。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi3": "此计已成，定鼎乾坤。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi4": "百舸竞发，借吾东风！。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi5": "烈火燎原，破贼瞬息。",
  "#ext:名将杀/audio/skill/mjshuoshaochibi6": "烈焰炽盛，愈燃愈烈！",
  "#ext:名将杀/audio/die/mjs_zhouyu:die": "箭矢已尽，命数已至……",
  "#ext:名将杀/audio/die/mjs_zhouyu2:die": "人生有死，修短命矣，诚不足惜。",

  "#ext:名将杀/audio/skill/mjstaipingyaoshu1": "潜龙勿用坎为纪。",
  "#ext:名将杀/audio/skill/mjstaipingyaoshu2": "奉天地、顺五行。",
  "#ext:名将杀/audio/skill/mjstaipingyaoshu3": "烧符化水，趋吉避凶。",
  "#ext:名将杀/audio/skill/mjstaipingyaoshu4": "天地人本同一元气。",
  "#ext:名将杀/audio/skill/mjstaipingyaoshu5": "得其治者昌，失其治者乱。",
  "#ext:名将杀/audio/skill/mjstaipingyaoshu6": "所以能安天下者，各因天下之心而安之。",
  "#ext:名将杀/audio/skill/mjstaipingdao1": "吾道太平！",
  "#ext:名将杀/audio/skill/mjstaipingdao2": "黄天庇佑！",
  "#ext:名将杀/audio/skill/mjshufenghuanyu1": "北斗七星，灌注雷霆，天罡所指，五雷急起。",
  "#ext:名将杀/audio/skill/mjshufenghuanyu2": "收阳降雨顷刻生，驱龙掣电出玄泓。",
  "#ext:名将杀/audio/die/mjs_zhangjiao:die": "一死不过殉道黄天。",
  "#ext:名将杀/audio/die/mjs_zhangjiao2:die": "哈哈哈……天公亦非仙家！",
};
