const cardPile = [
	// 行动
	["spade", 1, "sha"],
	["spade", 2, "sha"],
	["spade", 3, "sha"],
	["spade", 3, "sha"],
	["spade", 3, "sha"],
	["spade", 3, "sha"],
	["spade", 3, "sha"],
	["spade", 4, "sha", "thunder"],
	["spade", 4, "sha", "thunder"],
	["spade", 4, "sha", "thunder"],
	["spade", 4, "sha", "thunder"],
	["spade", 5, "sha"],
	["spade", 6, "sha"],
	["spade", 6, "sha"],
	["spade", 6, "sha"],
	["spade", 8, "sha"],
	["spade", 8, "sha"],
	["spade", 8, "sha"],

	["club", 1, "tao"],
	["club", 1, "tao"],
	["club", 3, "nu"],
	["club", 3, "nu"],
	["club", 4, "nu"],
	["club", 4, "nu"],
	["club", 4, "nu"],
	["club", 4, "nu"],
	["club", 4, "nu"],
	["club", 6, "tao"],
	["club", 6, "nu"],
	["club", 6, "tao"],
	["club", 7, "tao"],
	["club", 7, "tao"],
	["club", 7, "tao"],
	["club", 7, "nu"],
	["club", 8, "tao"],
	["club", 8, "tao"],
	["club", 8, "tao"],
	["club", 8, "tao"],
	["club", 8, "tao"],
	["club", 8, "tao"],

	["spade", 2, "shan"],
	["spade", 2, "shan"],
	["spade", 2, "shan"],
	["spade", 2, "shan"],
	["spade", 2, "shan"],
	["spade", 3, "shan"],
	["spade", 3, "shan"],
	["spade", 3, "shan"],
	["spade", 3, "shan"],
	["spade", 3, "shan"],
	["spade", 4, "shan"],
	["spade", 4, "shan"],
	["spade", 4, "shan"],
	["spade", 4, "shan"],
	["spade", 4, "shan"],
	["spade", 7, "shan"],
	["spade", 7, "shan"],
	["spade", 7, "shan"],
	["spade", 7, "shan"],
	["spade", 7, "shan"],
	["spade", 8, "shan"],
	["spade", 8, "shan"],

	["heart", 1, "sha", "fire"],
	["heart", 1, "sha", "fire"],
	["heart", 2, "sha", "fire"],
	["heart", 2, "sha", "fire"],
	["heart", 2, "sha", "fire"],
	["heart", 2, "sha", "fire"],
	["heart", 2, "sha", "fire"],
	["heart", 3, "sha", "fire"],
	["heart", 4, "sha", "fire"],
	["heart", 4, "sha", "fire"],
	["heart", 4, "sha", "fire"],
	["heart", 4, "sha", "fire"],
	["heart", 4, "sha", "fire"],
	["heart", 5, "sha", "fire"],
	["heart", 6, "sha", "fire"],
	["heart", 6, "sha", "fire"],
	["heart", 6, "sha", "fire"],
	["heart", 6, "sha", "fire"],
	["heart", 7, "sha", "fire"],
	["heart", 7, "sha", "fire"],
	["heart", 7, "sha", "fire"],
	["heart", 7, "sha", "fire"],
	["heart", 7, "sha", "fire"],
	["heart", 8, "sha", "fire"],
	["heart", 8, "sha", "fire"],
	["heart", 8, "sha", "fire"],
	["heart", 8, "sha", "fire"],

	["taiji", 8, "yi"],
	["taiji", 8, "yi"],

	// 战法
	["diamond", 1, "mjsjianyuqishe"],
	["diamond", 5, "mjszhenqianduijue"],
	["diamond", 5, "mjszhenqianduijue"],
	["diamond", 5, "mjszhenqianduijue"],
	["diamond", 6, "mjsdiaobingqianjiang"],
	["diamond", 6, "mjsdiaobingqianjiang"],
	["diamond", 7, "mjslianhuan"],
	["diamond", 7, "mjslianhuan"],
	["diamond", 7, "mjslianhuan"],
	["diamond", 7, "mjslianhuan"],
	["diamond", 7, "mjslianhuan"],

	["club", 1, "mjsxiuyangshengxi"],
	["club", 1, "mjstianlei"],
	["club", 2, "mjsduoduoyishan"],
	["club", 2, "mjsduoduoyishan"],
	["club", 2, "mjsduoduoyishan"],
	["club", 2, "mjsduoduoyishan"],
	["club", 2, "mjsduoduoyishan"],
	["club", 3, "mjsjiuhan"],
	["club", 3, "mjsjiuhan"],
	["club", 5, "mjsxianbatouchou"],
	["club", 5, "mjsxianbatouchou"],

	["spade", 1, "wuxie"],
	["spade", 1, "wuxie"],
	["spade", 1, "wuxie"],
	["spade", 1, "wuxie"],
	["spade", 1, "wuxie"],
	["spade", 5, "mjsduoliangjieying"],
	["spade", 5, "mjsduoliangjieying"],
	["spade", 5, "mjsduoliangjieying"],
	["spade", 5, "mjsduoliangjieying"],
	["spade", 5, "mjsduoliangjieying"],
	["spade", 6, "mjspozhenxiejia"],
	["spade", 6, "mjspozhenxiejia"],
	["spade", 6, "mjspozhenxiejia"],
	["spade", 6, "mjspozhenxiejia"],
	["spade", 6, "mjspozhenxiejia"],
	["spade", 8, "mjsshuangdong"],
	["spade", 8, "mjsshuangdong"],

	["heart", 3, "mjsliehuofencheng"],
	["heart", 3, "mjsliehuofencheng"],
	["heart", 3, "mjsliehuofencheng"],
	["heart", 5, "mjsfenghuolangyan"],
	["heart", 5, "mjsfenghuolangyan"],
	["heart", 5, "mjsfenghuolangyan"],
	["heart", 8, "mjsdihuo"],
	
	// 装备
	["diamond", 1, "mjsxuanyuanjian"],
	["diamond", 1, "mjsfangtianhuaji"],
	["diamond", 1, "mjsyinshikui"],
	["diamond", 2, "mjsliangyinqiang"],
	["diamond", 2, "mjsganjiangmoye"],
	["diamond", 2, "mjszhangbashemao"],
	["diamond", 2, "mjszhugeliannu"],
	["diamond", 4, "mjsqinglongyanyuedao"],
	["diamond", 5, "mjsjingyugong"],
	["diamond", 8, "mjskaishanfu"],
	["diamond", 8, "mjsminghongdao"],

	["club", 1, "mjszhuahuangfeidian"],
	["club", 3, "mjstengjia"],
	["club", 5, "mjsdaoli"],
	["club", 5, "mjsbaitiwu"],
	["club", 5, "mjsjueying"],
	["club", 6, "mjsdilu"],
	["club", 6, "mjswuzhui"],
	["club", 7, "mjssaluzi"],

	["spade", 8, "mjsyunjinpao"],
	["heart", 1, "mjsfengyukui"],
	["heart", 1, "mjsbaguadun"],
	["heart", 1, "mjslongshegong"],
	["heart", 3, "mjsyushan"],
	["heart", 5, "mjschitu"],
	["heart", 6, "mjsxuanwudun"],
	
];

export default cardPile;
