// Generated by node scripts/sync-hlhj-theme.mjs; paths are relative to theme/.
export const themes = {
    "bamboo": {
        "name": "潇湘竹影",
        "image": "xiaoxiang-garden.png",
        "album": "竹窗听雨",
        "tracks": [
            "竹窗听雨/竹窗听雨1.mp3",
            "竹窗听雨/竹窗听雨2.mp3"
        ]
    },
    "dream": {
        "name": "绛珠归梦",
        "image": "jiangzhu-dream-garden.png",
        "album": "绛珠归梦",
        "tracks": [
            "绛珠归梦/绛珠归梦1.mp3",
            "绛珠归梦/绛珠归梦2.mp3",
            "绛珠归梦/绛珠归梦3.m4a"
        ]
    }
};
